#!/usr/bin/env bun

/**
 * Genera PT_PORT_MAP con los puertos válidos de cada modelo.
 * Se embeberá en runtime.js para validación en tiempo de ejecución.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { routerCatalog, switchCatalog, wirelessCatalog } from '../../../core/src/catalog/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface PortDefinition {
  type: string;
  prefix: string;
  module: number;
  range: [number, number];
  speed: number;
  connector: string;
}

interface DeviceCatalogEntry {
  model: string;
  fixedPorts: PortDefinition[];
}

interface PortInfo {
  name: string;
  connector: string;
}

function expandPorts(device: DeviceCatalogEntry): PortInfo[] {
  const ports: PortInfo[] = [];
  for (const port of device.fixedPorts || []) {
    if (port.type === 'Console') continue;
    const type = port.type;
    const range = port.range || [0, 0];
    const mod = port.module || 0;
    const connector = port.connector || 'rj45';
    for (let i = range[0]; i <= range[1]; i++) {
      const portName = `${type}${mod}/${i}`;
      ports.push({ name: portName, connector: connector });
    }
  }
  return ports;
}

const MODEL_ALIASES: Record<string, string> = {
  '2960-24TT-L': '2960-24TT',
  '2960-24TC-L': '2960-24TC',
  '3560-24PS-L': '3560-24PS',
  'Linksys-WRT300N': 'WRT300N',
  'AccessPoint-PT-N': 'AP-PT-N',
  'AccessPoint-PT-A': 'AP-PT-A',
  'AccessPoint-PT-AC': 'AP-PT-AC',
};

const PT_MODEL_ALIASES: Record<string, string> = {
  'wrt300n': 'Linksys-WRT300N',
  'ap-pt-n': 'AccessPoint-PT-N',
  'ap-pt-a': 'AccessPoint-PT-A',
  'ap-pt-ac': 'AccessPoint-PT-AC',
};

function generatePortMap(): Record<string, Record<string, string>> {
  const portMap: Record<string, Record<string, string>> = {};

  const allDevices = [...routerCatalog, ...switchCatalog, ...wirelessCatalog];
  for (const device of allDevices) {
    const modelName = MODEL_ALIASES[device.model] || device.model;
    const portInfos = expandPorts(device);
    const portObj: Record<string, string> = {};
    for (const p of portInfos) {
      portObj[p.name.toLowerCase()] = p.connector;
    }
    portMap[modelName] = portObj;
    
    var ptAlias = PT_MODEL_ALIASES[modelName.toLowerCase()];
    if (ptAlias) {
      portMap[ptAlias] = portObj;
    }
  }

  return portMap;
}

const portMap = generatePortMap();

const outputPath = join(__dirname, '../templates/generated-port-map.ts');

const code = `// ============================================================================
// AUTO-GENERATED PORT MAP - DO NOT EDIT MANUALLY
// Generated by: generate-port-map.ts
// Source: @cisco-ai/catalog (routers.ts, switches.ts)
//
// Mapeo de modelo -> puertos válidos según catálogo oficial
// ============================================================================

var PT_PORT_MAP = ${JSON.stringify(portMap, null, 2)};
`;

writeFileSync(outputPath, code);

console.log('✅ Generated port map with', Object.keys(portMap).length, 'models');
console.log('📁 Output:', outputPath);

// Mostrar ejemplo
console.log('\n📋 Ejemplo - Puertos del 2811:', portMap['2811']);
console.log('📋 Ejemplo - Puertos del 2960-24TT:', portMap['2960-24TT']);
console.log('📋 Ejemplo - Puertos del Linksys-WRT300N:', portMap['Linksys-WRT300N']);
