#!/usr/bin/env bun

/**
 * Script para generar PT_MODEL_MAP desde la fuente de verdad tipada
 * 
 * Usa VERIFIED_MODELS de verified-models.ts como única fuente de verdad.
 * Los errores se detectan en compile-time, no en runtime.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateES5ModelMap, listVerifiedModels, getVerifiedModel, PTDeviceTypeNames, listModelsByCategory } from '../verified-models';

const __dirname = dirname(fileURLToPath(import.meta.url));

console.log('🔍 Generando PT_MODEL_MAP desde verified-models.ts (fuente de verdad tipada)...\n');

// Generar mapa ES5 desde la fuente tipada
const es5Code = generateES5ModelMap();

// Escribir archivo generado
const outputPath = join(__dirname, '../templates/generated-model-map.ts');
writeFileSync(outputPath, `// ============================================================================
// AUTO-GENERATED MODEL MAP - DO NOT EDIT MANUALLY
// Generated by: generate-model-map.ts
// Source: verified-models.ts (ÚNICA fuente de verdad)
// 
// Los modelos se validan en compile-time con TypeScript.
// Si un modelo no está en VERIFIED_MODELS, falla en el compilador.
// ============================================================================

` + es5Code);

// Obtener lista de modelos verificados
const verifiedModels = listVerifiedModels();

console.log('✅ Archivo generado:', outputPath);
console.log(`📊 Total de modelos verificados: ${verifiedModels.length}`);
console.log('\n📋 Modelos verificados por categoría:');

// Mostrar modelos organizados por categoría
const categories = ['routers', 'switches', 'wireless', 'endDevices'] as const;

for (const category of categories) {
  console.log(`\n   ${category.toUpperCase()}:`);
  
  const models = listModelsByCategory(category);
  
  models.forEach((model: string) => {
    const info = getVerifiedModel(model as any);
    const typeName = info ? PTDeviceTypeNames[info.type] : 'unknown';
    console.log(`      - ${model.padEnd(20)} (type: ${typeName})`);
  });
}

console.log('\n⚠️  IMPORTANTE:');
console.log('   - Este archivo se genera automáticamente desde verified-models.ts');
console.log('   - NO editar generated-model-map.ts manualmente');
console.log('   - Para agregar modelos, editar verified-models.ts y verificar en PT primero');
console.log('   - Los errores de modelos inválidos se detectan en compile-time');

console.log('\n✨ Modelo map generado exitosamente!');

// Mostrar ejemplo de uso tipado
console.log('\n📝 Ejemplo de uso con validación en compile-time:');
console.log(`
   import { getVerifiedModel, isVerifiedModel } from '../verified-models';
   
   // ✅ Funciona - modelo verificado
   const info = getVerifiedModel('2960-24TT');
   
   // ❌ Error en compile-time - modelo no verificado
   const invalid = getVerifiedModel('2960-24TT-L');  // ERROR!
   
   // Validación en runtime
   if (isVerifiedModel('2960')) {
     // Usar modelo
   }
`);
