#!/usr/bin/env bun

/**
 * Genera PT_MODULE_MAP con información de módulos válidos y sus slots.
 * Seembeberá en runtime.js para validación en tiempo de ejecución.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { moduleCatalog } from '../../../core/src/catalog/index.js';
import { routerCatalog } from '../../../core/src/catalog/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface ModuleSlotInfo {
  type: string;
  count: number;
  supportedModules: string[];
}

interface ModuleInfo {
  code: string;
  slotType: string;
  name: string;
}

function generateModuleCatalogMap(): Record<string, ModuleInfo> {
  const moduleMap: Record<string, ModuleInfo> = {};
  
  for (const mod of moduleCatalog) {
    moduleMap[mod.code] = {
      code: mod.code,
      slotType: mod.slotType,
      name: mod.name,
    };
  }
  
  return moduleMap;
}

function generateDeviceModuleSlotsMap(): Record<string, ModuleSlotInfo[]> {
  const slotMap: Record<string, ModuleSlotInfo[]> = {};
  
  for (const router of routerCatalog) {
    if (router.moduleSlots && router.moduleSlots.length > 0) {
      slotMap[router.model] = router.moduleSlots.map(slot => ({
        type: slot.type,
        count: slot.count,
        supportedModules: slot.supportedModules || [],
      }));
    }
  }
  
  return slotMap;
}

const moduleMap = generateModuleCatalogMap();
const slotMap = generateDeviceModuleSlotsMap();

const outputPath = join(__dirname, '../templates/generated-module-map.ts');

const code = `// ============================================================================
// AUTO-GENERATED MODULE MAP - DO NOT EDIT MANUALLY
// Generated by: generate-module-map.ts
// Source: @cisco-ai/catalog (modules.ts, routers.ts)
//
// Mapeo de módulos válidos y slots por modelo
// ============================================================================

var PT_MODULE_CATALOG = ${JSON.stringify(moduleMap, null, 2)};

var PT_DEVICE_MODULE_SLOTS = ${JSON.stringify(slotMap, null, 2)};
`;

writeFileSync(outputPath, code);

console.log('✅ Generated module map with', Object.keys(moduleMap).length, 'modules');
console.log('📁 Output:', outputPath);
console.log('\n📋 Ejemplo - HWIC-4ESW:', moduleMap['HWIC-4ESW']);
console.log('📋 Ejemplo - Slots del 2811:', slotMap['2811']);
console.log('📋 Ejemplo - Slots del ISR4331:', slotMap['ISR4331']);