#!/usr/bin/env bun

/**
 * Genera PT_PORT_MAP con los puertos válidos de cada modelo.
 * Se embeberá en runtime.js para validación en tiempo de ejecución.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildPtPortMap } from '../../../core/src/catalog/pt-registry.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const portMap = buildPtPortMap();

const outputPath = join(__dirname, '../templates/generated-port-map.ts');

const code = `// ============================================================================
// AUTO-GENERATED PORT MAP - DO NOT EDIT MANUALLY
// Generated by: generate-port-map.ts
// Source: packages/core/src/catalog/
//
// Mapeo de modelo -> puertos válidos según catálogo oficial
// ============================================================================

var PT_PORT_MAP = ${JSON.stringify(portMap, null, 2)};
`;

writeFileSync(outputPath, code);

console.log('✅ Generated port map with', Object.keys(portMap).length, 'models');
console.log('📁 Output:', outputPath);

// Mostrar ejemplo
console.log('\n📋 Ejemplo - Puertos del 2811:', portMap['2811']);
console.log('📋 Ejemplo - Puertos del 2960-24TT:', portMap['2960-24TT']);
console.log('📋 Ejemplo - Puertos del Linksys-WRT300N:', portMap['Linksys-WRT300N']);
