// ============================================================================
// Runtime Composer - Assembles handlers into executable runtime.js
// ============================================================================

import { CABLE_TYPES, DEVICE_TYPES, MODEL_ALIASES, CABLE_TYPE_NAMES } from "./utils/constants";
import { generateParserCode } from "./utils/parser-generator";
import {
  resolveModel,
  getDeviceTypeForModel,
  getDeviceTypeCandidates,
  createDeviceWithFallback,
  type PTLogicalWorkspace,
  type PTNetwork,
  type PTDevice,
  type PTPort,
  type PTCommandLine,
  type HandlerDeps,
  type HandlerResult,
} from "./utils/helpers";
import {
  handleAddDevice,
  handleRemoveDevice,
  handleListDevices,
  handleRenameDevice,
} from "./handlers/device";
import { handleAddLink, handleRemoveLink } from "./handlers/link";
import { handleConfigHost, handleConfigIos, handleExecIos } from "./handlers/config";
import { handleInspect, handleSnapshot } from "./handlers/inspect";
import { handleAddModule, handleRemoveModule } from "./handlers/module";
import { handleListCanvasRects, handleGetRect, handleDevicesInRect } from "./handlers/canvas";

// ============================================================================
// Handler Map Type
// ============================================================================

type HandlerFn = (payload: Record<string, unknown>, deps: HandlerDeps) => HandlerResult;

interface HandlerMap {
  [key: string]: HandlerFn;
}

// ============================================================================
// Compose Runtime
// ============================================================================

/**
 * Validate generated JavaScript code has correct syntax
 * Throws descriptive error if invalid
 */
function validateRuntimeCode(code: string): void {
  // Check minimum size (empty or tiny files are suspicious)
  if (code.length < 500) {
    throw new Error(
      `Generated runtime.js is suspiciously small (${code.length} bytes). ` +
      `Probably missing code or generation failed.`
    );
  }

  // Check for essential handlers
  const essentialHandlers = [
    "handleAddDevice",
    "handleSnapshot",
    "handleExecIos",
    "handleListDevices",
  ];

  for (const handler of essentialHandlers) {
    if (code.indexOf(`function ${handler}(`) === -1) {
      throw new Error(`Generated runtime.js is missing essential handler: ${handler}`);
    }
  }

  // Try to parse the code (won't catch all runtime errors, but catches syntax)
  try {
    new Function("payload", "ipc", "dprint", code);
  } catch (e) {
    const err = e as Error;
    throw new Error(
      `Generated runtime.js has syntax error: ${err.message}\n` +
      `This means the code generator produced invalid JavaScript.\n` +
      `Check compose.ts and parser-generator.ts for errors.`
    );
  }
}

/**
 * Generate the complete runtime.js code
 * This function creates a self-contained JavaScript string that runs in PT
 */
export function composeRuntime(): string {
  const code = String.raw`/**
 * PT Control V2 - Runtime
 *
 * Auto-generated by compose.ts - DO NOT EDIT MANUALLY
 * This code runs inside Packet Tracer Script Engine with full IPC access.
 */

// ============================================================================
// Constants
// ============================================================================

var CABLE_TYPES = ${JSON.stringify(CABLE_TYPES)};

var DEVICE_TYPES = ${JSON.stringify(DEVICE_TYPES)};

var MODEL_ALIASES = ${JSON.stringify(MODEL_ALIASES)};

var CABLE_TYPE_NAMES = ${JSON.stringify(CABLE_TYPE_NAMES)};

// ============================================================================
// Helpers
// ============================================================================

function getLW() {
  return ipc.appWindow().getActiveWorkspace().getLogicalWorkspace();
}

function getNet() {
  return ipc.network();
}

function resolveModel(model) {
  if (!model) return "2911";
  var key = model.toLowerCase();
  return MODEL_ALIASES[key] || model;
}

function getDeviceTypeForModel(model) {
  var name = (model || "").toLowerCase();
  if (name.indexOf("2960") === 0 || name.indexOf("3560") === 0 || name.indexOf("switch") >= 0) return DEVICE_TYPES.switch;
  if (name.indexOf("pc") === 0 || name.indexOf("laptop") === 0) return DEVICE_TYPES.pc;
  if (name.indexOf("server") === 0) return DEVICE_TYPES.server;
  if (name.indexOf("accesspoint") >= 0 || name.indexOf("wireless") >= 0) return DEVICE_TYPES.wireless;
  if (name.indexOf("cloud") >= 0) return DEVICE_TYPES.cloud;
  return DEVICE_TYPES.router;
}

function getDeviceTypeCandidates(model) {
  var normalized = (model || "").toLowerCase();
  
  if (normalized.indexOf("2960") === 0 || normalized.indexOf("3560") === 0 || normalized.indexOf("switch") >= 0) {
    return [DEVICE_TYPES.switch, DEVICE_TYPES.router];
  }
  
  if (normalized.indexOf("pc") === 0 || normalized.indexOf("laptop") === 0) {
    var candidates = [DEVICE_TYPES.pc, DEVICE_TYPES.end];
    for (var t = 8; t <= 60; t++) {
      if (candidates.indexOf(t) === -1) candidates.push(t);
    }
    return candidates;
  }
  
  if (normalized.indexOf("server") === 0) {
    var serverCandidates = [DEVICE_TYPES.server, DEVICE_TYPES.end];
    for (var s = 8; s <= 60; s++) {
      if (serverCandidates.indexOf(s) === -1) serverCandidates.push(s);
    }
    return serverCandidates;
  }
  
  return [DEVICE_TYPES.router, DEVICE_TYPES.switch, DEVICE_TYPES.pc];
}

function createDeviceWithFallback(model, x, y, typeList, lw, net) {
  for (var i = 0; i < typeList.length; i++) {
    var typeId = typeList[i];
    var autoName = lw.addDevice(typeId, model, x, y);
    if (!autoName) continue;
    
    var device = net.getDevice(autoName);
    if (!device) {
      lw.removeDevice(autoName);
      continue;
    }
    
    var deviceModel = "";
    try { deviceModel = (device.getModel && device.getModel()) || ""; } catch (e) {}
    
    if (deviceModel && deviceModel.toLowerCase() === model.toLowerCase()) {
      return { autoName: autoName, device: device, typeId: typeId };
    }
    
    lw.removeDevice(autoName);
  }
  return null;
}

// ============================================================================
// IOS Output Parsers
// ============================================================================

${generateParserCode()}

// ============================================================================
// IOS Session State Management (with filesystem persistence)
// Tracks mode, paging, and confirmation state per device across commands
// Includes automatic cleanup to prevent memory leaks
// Sessions persist across PT hot-reloads via filesystem
// ============================================================================

var IOS_SESSIONS = {};
var SESSION_DIRTY = false; // Track if sessions need saving
var LAST_CLEANUP_TIME = 0;
var CLEANUP_INTERVAL_MS = 30000; // Every 30 seconds
var SESSION_ACCESS_COUNT = 0;
var SESSION_MAX_AGE_MS = 300000; // 5 minutes
var MAX_SESSIONS = 200; // Increased from 50 to support larger labs
var SESSIONS_FILE = DEV_DIR + "/sessions/ios-sessions.json";
var HEARTBEAT_FILE = DEV_DIR + "/sessions/heartbeat.json";

function isSessionStale() {
  try {
    if (!fm.fileExists(HEARTBEAT_FILE)) {
      return true; // No heartbeat = definitely stale
    }
    var content = fm.getFileContents(HEARTBEAT_FILE);
    var heartbeat = JSON.parse(content);
    var age = Date.now() - heartbeat.ts;
    return age > 15000; // Stale if no heartbeat for > 15 seconds
  } catch (e) {
    dprint("[Sessions] Heartbeat check failed, assuming stale: " + e);
    return true;
  }
}

function loadSessionsFromDisk() {
  try {
    // Check if sessions are stale (PT reopened after crash)
    if (isSessionStale()) {
      dprint("[Sessions] Sessions are stale (PT was restarted), clearing ios-sessions.json");
      fm.writePlainTextToFile(SESSIONS_FILE, JSON.stringify({}));
      return;
    }

    if (fm.fileExists(SESSIONS_FILE)) {
      var content = fm.getFileContents(SESSIONS_FILE);
      var loaded = JSON.parse(content);
      var now = Date.now();
      var loadedCount = 0;

      for (var key in loaded) {
        if (loaded[key] && loaded[key].lastUsed && (now - loaded[key].lastUsed < SESSION_MAX_AGE_MS)) {
          IOS_SESSIONS[key] = loaded[key];
          loadedCount++;
        }
      }

      dprint("[Sessions] Loaded " + loadedCount + " sessions from disk");
    }
  } catch (e) {
    dprint("[Sessions] Failed to load from disk: " + e);
  }
}

function saveSessionsToDisk() {
  if (!SESSION_DIRTY) return;
  try {
    var tempFile = SESSIONS_FILE + ".tmp";
    fm.writeFile(tempFile, JSON.stringify(IOS_SESSIONS, null, 2));
    fm.renameFile(tempFile, SESSIONS_FILE);
    SESSION_DIRTY = false;
  } catch (e) {
    dprint("[Sessions] Failed to save to disk: " + e);
  }
}

function cleanupStaleSessions() {
  var now = Date.now();
  var timeSinceCleanup = now - LAST_CLEANUP_TIME;
  var shouldCleanupByTime = timeSinceCleanup >= CLEANUP_INTERVAL_MS;
  var shouldCleanupByCount = SESSION_ACCESS_COUNT >= 10;

  if (!shouldCleanupByTime && !shouldCleanupByCount) return;

  LAST_CLEANUP_TIME = now;
  SESSION_ACCESS_COUNT = 0;

  var keys = Object.keys(IOS_SESSIONS);
  var activeKeys = [];

  // Evict by age first
  for (var i = 0; i < keys.length; i++) {
    var key = keys[i];
    var session = IOS_SESSIONS[key];
    if (session && session.lastUsed) {
      var age = now - session.lastUsed;
      if (age > SESSION_MAX_AGE_MS) {
        delete IOS_SESSIONS[key];
        SESSION_DIRTY = true;
      } else {
        activeKeys.push(key);
      }
    } else {
      delete IOS_SESSIONS[key];
      SESSION_DIRTY = true;
    }
  }

  // Evict excess by LRU (keep most recently used)
  if (activeKeys.length > MAX_SESSIONS) {
    activeKeys.sort(function(a, b) {
      var aTime = IOS_SESSIONS[a] && IOS_SESSIONS[a].lastUsed || 0;
      var bTime = IOS_SESSIONS[b] && IOS_SESSIONS[b].lastUsed || 0;
      return aTime - bTime;
    });

    var toRemove = activeKeys.length - MAX_SESSIONS;
    for (var j = 0; j < toRemove; j++) {
      dprint("[Sessions] Evicting session for " + activeKeys[j] + " (LRU)");
      delete IOS_SESSIONS[activeKeys[j]];
      SESSION_DIRTY = true;
    }
  }

  if (SESSION_DIRTY) {
    try {
      var tempFile = SESSIONS_FILE + ".tmp";
      fm.writeFile(tempFile, JSON.stringify(IOS_SESSIONS, null, 2));
      fm.renameFile(tempFile, SESSIONS_FILE);
      SESSION_DIRTY = false;
    } catch (e) { dprint("[Sessions] Save failed: " + e); }
  }
}

function getOrCreateSession(deviceName, term) {
  // Load from disk on first access if not yet loaded
  if (Object.keys(IOS_SESSIONS).length === 0) {
    loadSessionsFromDisk();
  }

  SESSION_ACCESS_COUNT++;
  cleanupStaleSessions();

  if (!IOS_SESSIONS[deviceName]) {
    IOS_SESSIONS[deviceName] = {
      mode: "user-exec",
      paging: false,
      awaitingConfirm: false,
      deviceName: deviceName,
      lastUsed: Date.now(),
      createdAt: Date.now()
    };
    SESSION_DIRTY = true;
    saveSessionsToDisk(); // Only save new sessions immediately
  } else {
    IOS_SESSIONS[deviceName].lastUsed = Date.now();
  }

  return IOS_SESSIONS[deviceName];
}

function inferPromptMode(output) {
  var lastLine = "";
  var lines = output.split("\n");
  for (var i = lines.length - 1; i >= 0; i--) {
    var line = lines[i].trim();
    if (line) {
      lastLine = line;
      break;
    }
  }

  if (/--More--/i.test(lastLine) || /\x1B\?D/.test(lastLine)) {
    return "paging";
  }
  if (/^\[confirm\]/i.test(lastLine)) {
    return "awaiting-confirm";
  }
  if (/^Password:/i.test(lastLine)) {
    return "awaiting-password";
  }

  var promptMatchers = [
    { pattern: /\(config-router\)#$/, mode: "config-router" },
    { pattern: /\(config-line\)#$/, mode: "config-line" },
    { pattern: /\(config-if\)#$/, mode: "config-if" },
    { pattern: /\(config\)#$/, mode: "config" },
    { pattern: /#$/, mode: "priv-exec" },
    { pattern: />$/, mode: "user-exec" },
  ];

  for (var i = 0; i < promptMatchers.length; i++) {
    if (promptMatchers[i].pattern.test(lastLine)) {
      return promptMatchers[i].mode;
    }
  }

  return "unknown";
}

function isPrivilegedMode(mode) {
  return mode === "priv-exec" || mode === "config" ||
         mode === "config-if" || mode === "config-line" || mode === "config-router";
}

function isConfigMode(mode) {
  return mode && mode.indexOf("config") === 0;
}

function updateSessionFromOutput(session, output, term) {
  var mode = inferPromptMode(output);

  if (mode === "paging") {
    session.paging = true;
    return;
  }
  session.paging = false;

  if (mode === "awaiting-confirm") {
    session.awaitingConfirm = true;
    return;
  }
  session.awaitingConfirm = false;

  if (mode === "awaiting-password") {
    return;
  }

  if (mode !== "unknown") {
    session.mode = mode;
  }
}

function executeIosCommand(term, cmd, session) {
  var response = term.enterCommand(cmd);
  if (!response || !response[0]) {
    updateSessionFromOutput(session, response[1] || "", term);
    return response || [0, ""];
  }

  var status = response[0];
  var output = response[1] || "";

  updateSessionFromOutput(session, output, term);

  while (session.paging) {
    var pageResponse = term.enterCommand(" ");
    updateSessionFromOutput(session, pageResponse[1] || "", term);
    output += pageResponse[1] || "";
  }

  if (session.awaitingConfirm) {
    var confirmResponse = term.enterCommand("\n");
    updateSessionFromOutput(session, confirmResponse[1] || "", term);
    output += confirmResponse[1] || "";
  }

  return [status, output];
}

function ensurePrivileged(term, session) {
  if (isPrivilegedMode(session.mode)) {
    return [true, ""];
  }

  var result = executeIosCommand(term, "enable", session);
  return [result[0] === 0, result[1]];
}

function ensureConfigMode(term, session) {
  if (isConfigMode(session.mode)) {
    return [true, ""];
  }

  if (!isPrivilegedMode(session.mode)) {
    var privResult = ensurePrivileged(term, session);
    if (!privResult[0]) {
      return [false, privResult[1]];
    }
  }

  var result = executeIosCommand(term, "configure terminal", session);
  return [result[0] === 0, result[1]];
}

// ============================================================================
// Command Handlers
// ============================================================================

function handleAddDevice(payload) {
  var lw = getLW();
  var net = getNet();
  var model = resolveModel(payload.model);
  var name = payload.name || model;
  var x = payload.x !== undefined ? payload.x : 100;
  var y = payload.y !== undefined ? payload.y : 100;
  
  var typeList = payload.deviceType !== undefined 
    ? [payload.deviceType] 
    : getDeviceTypeCandidates(model);
  
  var created = createDeviceWithFallback(model, x, y, typeList, lw, net);
  if (!created) {
    return { ok: false, error: "Failed to add device for model: " + model };
  }
  
  var autoName = created.autoName;
  var device = created.device;
  
  device.setName(name);
  if (device.skipBoot) device.skipBoot();
  
  return { ok: true, name: name, autoName: autoName, model: model, deviceType: created.typeId };
}

function handleRemoveDevice(payload) {
  getLW().removeDevice(payload.name);
  return { ok: true, name: payload.name };
}

function handleListDevices() {
  var net = getNet();
  var count = net.getDeviceCount();
  var devices = [];
  
  for (var i = 0; i < count; i++) {
    var device = net.getDeviceAt(i);
    if (device) {
      devices.push({
        name: device.getName(),
        model: device.getModel(),
        type: device.getType(),
        power: device.getPower()
      });
    }
  }
  
  return { ok: true, devices: devices, count: count };
}

function handleRenameDevice(payload) {
  var device = getNet().getDevice(payload.oldName);
  if (!device) return { ok: false, error: "Device not found: " + payload.oldName };
  device.setName(payload.newName);
  return { ok: true, oldName: payload.oldName, newName: payload.newName };
}

function handleAddModule(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  if (!device.addModule) return { ok: false, error: "Device does not support modular expansion" };
  
  var wasPowered = device.getPower();
  
  if (wasPowered) device.setPower(false);
  
  var result = device.addModule(payload.slot, payload.module);
  
  if (wasPowered) {
    device.setPower(true);
    if (device.skipBoot) device.skipBoot();
  }
  
  if (!result) return { ok: false, error: "Failed to add module to slot " + payload.slot };
  
  return { ok: true, device: payload.device, slot: payload.slot, module: payload.module };
}

function handleRemoveModule(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  if (!device.removeModule) return { ok: false, error: "Device does not support modular expansion" };
  
  var wasPowered = device.getPower();
  
  if (wasPowered) device.setPower(false);
  
  var result = device.removeModule(payload.slot);
  
  if (wasPowered) {
    device.setPower(true);
    if (device.skipBoot) device.skipBoot();
  }
  
  if (!result) return { ok: false, error: "Failed to remove module from slot " + payload.slot };
  
  return { ok: true, device: payload.device, slot: payload.slot };
}

function handleAddLink(payload) {
  var lw = getLW();
  var cableType = CABLE_TYPES[payload.linkType] || CABLE_TYPES.auto;
  
  var success = lw.createLink(
    payload.device1, payload.port1,
    payload.device2, payload.port2,
    cableType
  );
  
  if (!success) return { ok: false, error: "Failed to create link" };
  
  return {
    ok: true,
    device1: payload.device1,
    port1: payload.port1,
    device2: payload.device2,
    port2: payload.port2,
    linkType: payload.linkType || "auto"
  };
}

function handleRemoveLink(payload) {
  getLW().deleteLink(payload.device, payload.port);
  return { ok: true };
}

function handleConfigHost(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  var port = device.getPortAt(0);
  if (!port) return { ok: false, error: "No ports on device" };
  
  if (payload.dhcp === true) {
    try { port.setDhcpEnabled(true); } catch(e) {}
  } else {
    if (payload.ip && payload.mask) {
      port.setIpSubnetMask(payload.ip, payload.mask);
    }
    if (payload.gateway) {
      port.setDefaultGateway(payload.gateway);
    }
    if (payload.dns) {
      port.setDnsServerIp(payload.dns);
    }
  }
  
  return { ok: true, device: payload.device, ip: payload.ip };
}

function classifyIosOutput(output) {
  var trimmed = (output || "").trim();

  // Error patterns
  if (trimmed.indexOf("% Invalid input") >= 0) {
    return { category: "invalid", ok: false };
  }
  if (trimmed.indexOf("% Incomplete command") >= 0) {
    return { category: "incomplete", ok: false };
  }
  if (trimmed.indexOf("% Ambiguous command") >= 0) {
    return { category: "ambiguous", ok: false };
  }
  if (trimmed.indexOf("% ") >= 0 && trimmed.indexOf("ERROR") >= 0) {
    return { category: "error", ok: false };
  }

  // Success patterns
  if (trimmed.indexOf("--More--") >= 0) {
    return { category: "paging", ok: true };
  }
  if (trimmed.indexOf("[confirm]") >= 0) {
    return { category: "confirm", ok: true };
  }

  // Default
  return { category: "success", ok: true };
}

function handleConfigIos(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };

  if (device.skipBoot) device.skipBoot();

  var term = device.getCommandLine();
  if (!term) return { ok: false, error: "Device does not support CLI" };

  var session = getOrCreateSession(payload.device, term);

  var configResult = ensureConfigMode(term, session);
  if (!configResult[0]) {
    dprint("[handleConfigIos] Failed to enter config mode: " + configResult[1]);
    return { ok: false, error: "Failed to enter config mode: " + configResult[1], phase: "pre-exec" };
  }

  var results = [];
  var failedCount = 0;
  var stopOnError = payload.stopOnError !== false; // Default: fail-fast

  for (var i = 0; i < payload.commands.length; i++) {
    var cmd = payload.commands[i];
    var cmdResult = executeIosCommand(term, cmd, session);
    var status = cmdResult[0];
    var output = cmdResult[1];

    var classification = classifyIosOutput(output);
    var cmdOk = status === 0 && classification.ok;

    results.push({
      index: i,
      command: cmd,
      ok: cmdOk,
      status: status,
      output: output.slice(0, 500),
      classification: classification.category
    });

    if (!cmdOk) {
      failedCount++;
      if (stopOnError) {
        return {
          ok: false,
          error: "Command failed (abort on error): " + cmd,
          failedAt: i,
          totalCommands: payload.commands.length,
          executedCount: i + 1,
          failedCount: failedCount,
          results: results,
          session: { mode: session.mode }
        };
      }
    }
  }

  if (payload.save !== false) {
    executeIosCommand(term, "write memory", session);
  }

  return {
    ok: failedCount === 0,
    device: payload.device,
    totalCommands: payload.commands.length,
    executedCount: results.length,
    failedCount: failedCount,
    results: results,
    session: { mode: session.mode }
  };
}

function handleExecIos(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };

  var cmd = (payload.command || "").toLowerCase().trim();

  if (cmd === "show running-config" || cmd === "show startup-config") {
    return handleShowConfig(device, payload);
  }

  if (cmd === "show version") {
    return handleShowVersion(device, payload);
  }

  if (cmd.startsWith("show ip ")) {
    return handleShowIpCommand(device, payload);
  }

  var term = device.getCommandLine();
  if (!term) {
    return { ok: false, error: "Device does not support CLI" };
  }

  var session = getOrCreateSession(payload.device, term);

  try {
    var cmdResult = executeIosCommand(term, payload.command, session);
    var status = cmdResult[0];
    var output = cmdResult[1];

    dprint("[execIos] session.execute: status=" + status + ", output length=" + output.length + ", mode=" + session.mode);

    var classification = classifyIosOutput(output);

    var result = {
      ok: status === 0 && classification.ok,
      raw: output,
      status: status,
      classification: classification.category,
      session: { mode: session.mode, paging: session.paging, awaitingConfirm: session.awaitingConfirm }
    };

    if (!result.ok && classification.category !== "success") {
      result.error = {
        code: classification.category.toUpperCase(),
        message: "IOS returned error: " + classification.category,
        raw: output.slice(0, 200)
      };
    }

    if (payload.parse !== false) {
      var parser = getParser(payload.command);
      if (parser) {
        try {
          result.parsed = parser(output);
        } catch (e) {
          result.parseError = String(e);
        }
      }
    }

    return result;
  } catch (e) {
    dprint("[execIos] executeIosCommand error: " + String(e));
    return { ok: false, error: "Failed to execute command: " + String(e), raw: "" };
  }
}

function generateSimulatedConfig(device) {
  var name = device.getName();
  var model = device.getModel();
  var power = device.getPower();
  var type = device.getType();
  var portCount = device.getPortCount();
  var ports = [];

  for (var i = 0; i < portCount; i++) {
    try {
      var port = device.getPortAt(i);
      if (port) {
        var portName = port.getName();
        var ip = port.getIpAddress();
        var mask = port.getSubnetMask();
        if (ip && ip !== "0.0.0.0") {
          ports.push("interface " + portName + "\n ip address " + ip + " " + mask);
        }
      }
    } catch(e) {}
  }

  var config = "!\n! WARNING: Simulated config (PT CLI unavailable)\n!\nversion 15.2\nhostname " + name + "\n!\n";
  if (ports.length > 0) {
    config += ports.join("\n!\n") + "\n";
  }
  if (!power) {
    config += "!\n% Device is powered off\n";
  }

  return {
    ok: true,
    raw: config,
    status: 0,
    simulated: true,
    parsed: {
      raw: config,
      hostname: name,
      version: "15.2",
      sections: [],
      interfaces: {}
    }
  };
}

function handleShowConfig(device, payload) {
  var term = device.getCommandLine();
  if (!term) {
    dprint("[handleShowConfig] No CLI terminal, using simulated config");
    return generateSimulatedConfig(device);
  }

  var session = getOrCreateSession(device.getName(), term);

  try {
    // Execute real command
    var cmdResult = executeIosCommand(term, "show running-config", session);
    var status = cmdResult[0];
    var output = cmdResult[1];

    if (status !== 0) {
      dprint("[handleShowConfig] Command failed (status=" + status + "), using simulated");
      return generateSimulatedConfig(device);
    }

    var result = {
      ok: true,
      raw: output,
      status: status,
      simulated: false,
      session: { mode: session.mode }
    };

    // Parse if requested
    if (payload.parse !== false) {
      var parser = getParser("show running-config");
      if (parser) {
        try {
          result.parsed = parser(output);
        } catch (e) {
          result.parseError = String(e);
        }
      }
    }

    dprint("[handleShowConfig] Real config returned: " + output.length + " chars");
    return result;

  } catch (e) {
    dprint("[handleShowConfig] Error executing command: " + e + ", using simulated");
    return generateSimulatedConfig(device);
  }
}

function generateSimulatedVersion(device) {
  var name = device.getName();
  var model = device.getModel();
  var power = device.getPower();
  var type = device.getType();

  var typeMap = {
    0: "ISR Router",
    1: "Switch",
    16: "Multilayer Switch"
  };
  var typeStr = typeMap[type] || "Unknown";

  var versionOutput = "! WARNING: Simulated output (PT CLI unavailable)\n" +
    "Cisco IOS Software, " + model + " Software (" + model + "-LANBASE-M), Version 15.2(4)E, RELEASE SOFTWARE (fc1)\n" +
    "Technical Support: http://www.cisco.com/techsupport\n" +
    "Copyright (c) 1986-2016 by Cisco Systems, Inc.\n" +
    "Compiled Mon 03-Oct-16 14:49 by prod_rel_team\n\n" +
    "ROM: Bootstrap program is OK\n" +
    name + " uptime is unknown\n" +
    "Uptime for this control processor is unknown\n" +
    "System returned to ROM by power-on\n" +
    "System image file is \"flash:" + model + "-LANBASE-M\"\n\n" +
    typeStr + " " + model + " (PPC processor) with 190464K/18432K bytes of memory.\n" +
    "Processor board ID SIMULATED\n" +
    "1 Gigabit Ethernet interface\n" +
    "4 Fast Ethernet interfaces\n" +
    "64K bytes of flash-simulated non-volatile configuration memory.\n" +
    "Configuration register is 0x2102\n\n" +
    (power ? "Device is operational" : "Device is powered off");

  return {
    ok: true,
    raw: versionOutput,
    status: 0,
    simulated: true,
    parsed: {
      raw: versionOutput,
      hostname: name,
      version: "15.2(4)E",
      uptime: "unknown",
      image: model + "-LANBASE-M",
      processor: typeStr
    }
  };
}

function handleShowVersion(device, payload) {
  var term = device.getCommandLine();
  if (!term) {
    dprint("[handleShowVersion] No CLI terminal, using simulated version");
    return generateSimulatedVersion(device);
  }

  var session = getOrCreateSession(device.getName(), term);

  try {
    // Execute real command
    var cmdResult = executeIosCommand(term, "show version", session);
    var status = cmdResult[0];
    var output = cmdResult[1];

    if (status !== 0) {
      dprint("[handleShowVersion] Command failed (status=" + status + "), using simulated");
      return generateSimulatedVersion(device);
    }

    var result = {
      ok: true,
      raw: output,
      status: status,
      simulated: false,
      session: { mode: session.mode }
    };

    // Parse if requested
    if (payload.parse !== false) {
      var parser = getParser("show version");
      if (parser) {
        try {
          result.parsed = parser(output);
        } catch (e) {
          result.parseError = String(e);
        }
      }
    }

    dprint("[handleShowVersion] Real version returned: " + output.length + " chars");
    return result;

  } catch (e) {
    dprint("[handleShowVersion] Error executing command: " + e + ", using simulated");
    return generateSimulatedVersion(device);
  }
}

function handleShowIpCommand(device, payload) {
  var cmd = (payload.command || "").toLowerCase();

  if (cmd === "show ip interface brief" || cmd === "show ip int brief") {
    var portCount = 0;
    try { portCount = device.getPortCount(); } catch(e) {}
    var interfaces = [];

    interfaces.push({interface: "Vlan1", ipAddress: "unassigned", ok: "NVRAM", method: "manual", status: "down", protocol: "down"});

    for (var i = 0; i < portCount; i++) {
      try {
        var port = device.getPortAt(i);
        if (port) {
          var portName = "";
          var ip = "unassigned";
          try { portName = port.getName(); } catch(e1) {}
          try { ip = port.getIpAddress(); } catch(e1) {}
          var status = (ip && ip !== "0.0.0.0" && ip !== "unassigned") ? "up" : "down";
          interfaces.push({
            interface: portName,
            ipAddress: ip === "0.0.0.0" ? "unassigned" : ip,
            ok: "NVRAM",
            method: "manual",
            status: status,
            protocol: status === "up" ? "up" : "down"
          });
        }
      } catch(e) {}
    }

    var header = "Interface              IP-Address      OK? Method Status                Protocol";
    var lines = [];
    for (var j = 0; j < interfaces.length; j++) {
      var iface = interfaces[j];
      var line = iface.interface.padEnd(20) + iface.ipAddress.padEnd(16) + "YES   " + iface.method.padEnd(8) + iface.status.padEnd(20) + iface.protocol;
      lines.push(line);
    }
    var output = [header].concat(lines).join("\n");

    dprint("[execIos] Generated IP interface brief: " + output.length + " chars");

    var parsedIfaces = [];
    for (var k = 0; k < interfaces.length; k++) {
      var iface2 = interfaces[k];
      parsedIfaces.push({
        interface: iface2.interface,
        ipAddress: iface2.ipAddress === "unassigned" ? "" : iface2.ipAddress,
        ok: iface2.ok,
        method: iface2.method,
        status: iface2.status,
        protocol: iface2.protocol
      });
    }

    return {
      ok: true,
      raw: output,
      status: 0,
      parsed: {
        raw: output,
        interfaces: parsedIfaces
      }
    };
  }

  if (cmd === "show ip route") {
    var output = "Codes: L - local, C - connected, S - static, R - RIP, M - mobile, B - BGP\n" +
      "     D - EIGRP, EX - EIGRP external, O - OSPF, IA - OSPF inter area\n" +
      "     N1 - OSPF NSSA external type 1, N2 - OSPF NSSA external type 2\n" +
      "     E1 - OSPF external type 1, E2 - OSPF external type 2, E - EGP\n" +
      "     i - IS-IS, L1 - IS-IS level-1, L2 - IS-IS level-2, ia - IS-IS inter area\n" +
      "     * - candidate default, U - per-user static route, o - ODR\n" +
      "     P - periodic downloaded static route\n\n" +
      "Gateway of last resort is not set";

    return {
      ok: true,
      raw: output,
      status: 0,
      parsed: {
        raw: output,
        routes: [],
        gatewayOfLastResort: "not set"
      }
    };
  }

  return { ok: false, error: "Unsupported show ip command: " + payload.command, raw: "" };
}

function handleSnapshot() {
  var net = getNet();
  var count = net.getDeviceCount();
  var devices = {};
  var linksMap = {}; // Use link UUID for O(1) deduplication

  for (var i = 0; i < count; i++) {
    var device = net.getDeviceAt(i);
    if (!device) continue;

    var name = device.getName();
    var portCount = device.getPortCount();
    var ports = [];

    for (var p = 0; p < portCount; p++) {
      try {
        var port = device.getPortAt(p);
        if (!port) continue;

        var portInfo = { name: port.getName(), type: "unknown" };

        try { portInfo.ipAddress = port.getIpAddress(); } catch(e) {}
        try { portInfo.subnetMask = port.getSubnetMask(); } catch(e) {}
        try { portInfo.macAddress = port.getMacAddress(); } catch(e) {}

        ports.push(portInfo);

        // O(n) link processing using UUID instead of O(n²) nested loops
        var link = port.getLink();
        if (link) {
          var linkId = link.getObjectUUID();

          // Only process if not already seen (O(1) lookup)
          if (!linksMap[linkId]) {
            var srcPort = link.getSourcePort();
            var dstPort = link.getDestPort();
            var srcDevice = srcPort.getDevice();
            var dstDevice = dstPort.getDevice();

            var dev1, pt1, dev2, pt2;
            if (srcDevice.getName() < dstDevice.getName()) {
              dev1 = srcDevice.getName(); pt1 = srcPort.getName();
              dev2 = dstDevice.getName(); pt2 = dstPort.getName();
            } else {
              dev1 = dstDevice.getName(); pt1 = dstPort.getName();
              dev2 = srcDevice.getName(); pt2 = srcPort.getName();
            }

            linksMap[linkId] = {
              id: linkId,
              device1: dev1,
              port1: pt1,
              device2: dev2,
              port2: pt2,
              type: CABLE_TYPE_NAMES[link.getLinkType()] || "auto",
              status: link.getStatus()
            };
          }
        }
      } catch(e) {
        ports.push({ name: "port" + p });
      }
    }

    devices[name] = {
      name: name,
      model: device.getModel(),
      type: device.getType(),
      power: device.getPower(),
      ports: ports
    };
  }

  // Convert linksMap to array
  var links = [];
  for (var linkId in linksMap) {
    links.push(linksMap[linkId]);
  }

  return {
    ok: true,
    version: "1.0",
    timestamp: Date.now(),
    devices: devices,
    links: links,
    metadata: { deviceCount: count, linkCount: Object.keys(links).length }
  };
}

function handleInspect(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  var portCount = device.getPortCount();
  var ports = [];
  
  for (var i = 0; i < portCount; i++) {
    try {
      var port = device.getPortAt(i);
      if (!port) continue;
      
      var portInfo = { name: port.getName() };
      try { portInfo.ipAddress = port.getIpAddress(); } catch(e) {}
      try { portInfo.subnetMask = port.getSubnetMask(); } catch(e) {}
      try { portInfo.macAddress = port.getMacAddress(); } catch(e) {}
      try { portInfo.defaultGateway = port.getDefaultGateway(); } catch(e) {}
      
      ports.push(portInfo);
    } catch(e) {}
  }
  
  var result = {
    ok: true,
    name: device.getName(),
    model: device.getModel(),
    type: device.getType(),
    power: device.getPower(),
    ports: ports
  };
  
  if (payload.includeXml && device.serializeToXml) {
    try { result.xml = device.serializeToXml(); } catch(e) {}
  }
  
  return result;
}

function handleHardwareInfo() {
  var factory = ipc.hardwareFactory();
  var keys = [];
  for (var key in factory) keys.push(key);
  return { ok: true, keys: keys };
}

function handleHardwareCatalog(payload) {
  var factory = ipc.hardwareFactory();
  var list = factory.devices || [];
  var limit = payload.limit || 50;
  var results = [];
  
  for (var i = 0; i < list.length && results.length < limit; i++) {
    var item = list[i];
    var entry = {};
    try { entry.name = item.name; } catch(e) {}
    try { entry.model = item.model; } catch(e) {}
    try { entry.displayName = item.displayName; } catch(e) {}
    try { entry.deviceType = item.deviceType; } catch(e) {}
    results.push(entry);
  }
  
  return { ok: true, items: results, total: list.length || 0 };
}

function handleCommandLog(payload) {
  var cl = ipc.commandLog();
  cl.setEnabled(true);
  
  var count = cl.getEntryCount();
  var limit = payload.limit || 100;
  var start = Math.max(0, count - limit);
  var entries = [];
  
  for (var i = start; i < count; i++) {
    var entry = cl.getEntryAt(i);
    entries.push({
      index: i,
      time: entry.getTimeToString ? entry.getTimeToString() : "",
      device: entry.getDeviceName ? entry.getDeviceName() : "",
      prompt: entry.getPrompt ? entry.getPrompt() : "",
      command: entry.getCommand ? entry.getCommand() : ""
    });
  }
  
  return { ok: true, entries: entries, count: count };
}

// ============================================================================
// Canvas/Rect Handlers
// ============================================================================

function handleListCanvasRects(payload) {
  var lw = getLW();
  var rectIds = [];

  try {
    if (lw.getCanvasRectIds) {
      rectIds = lw.getCanvasRectIds() || [];
    }
  } catch (e) {
    return { ok: false, error: "Failed to get canvas rect IDs: " + String(e) };
  }

  return { ok: true, rects: rectIds, count: rectIds.length };
}

function handleGetRect(payload) {
  var lw = getLW();
  var rectData = null;

  try {
    if (lw.getRectItemData) {
      rectData = lw.getRectItemData(payload.rectId) || null;
    } else if (lw.getRectData) {
      rectData = lw.getRectData(payload.rectId) || null;
    }
  } catch (e) {
    return { ok: false, error: "Failed to get rect data: " + String(e) };
  }

  if (!rectData) {
    return { ok: false, error: "Rect not found: " + payload.rectId };
  }

  return { ok: true, rectId: payload.rectId, data: rectData };
}

function handleDevicesInRect(payload) {
  var lw = getLW();
  var net = getNet();
  var devices = [];
  var clusters = [];

  try {
    if (lw.devicesAt) {
      var rectData = payload.rectId && lw.getRectItemData ? lw.getRectItemData(payload.rectId) : null;

      var x = 0, y = 0, width = 0, height = 0;

      if (rectData && typeof rectData === "object") {
        x = rectData.x || 0;
        y = rectData.y || 0;
        width = rectData.width || 0;
        height = rectData.height || 0;
      }

      if (width > 0 && height > 0) {
        var foundDevices = lw.devicesAt(x, y, width, height, payload.includeClusters || false);
        if (Array.isArray(foundDevices)) {
          for (var i = 0; i < foundDevices.length; i++) {
            if (typeof foundDevices[i] === "string") {
              devices.push(foundDevices[i]);
            }
          }
        }
      }
    }

    if (devices.length === 0 && payload.rectId) {
      var rectData = lw.getRectItemData ? lw.getRectItemData(payload.rectId) : null;

      if (rectData && typeof rectData === "object") {
        var rx = rectData.x || 0;
        var ry = rectData.y || 0;
        var rw = rectData.width || 0;
        var rh = rectData.height || 0;

        var deviceCount = net.getDeviceCount();
        for (var i = 0; i < deviceCount; i++) {
          var device = net.getDeviceAt(i);
          if (!device) continue;

          var deviceX = device.getX ? device.getX() : 0;
          var deviceY = device.getY ? device.getY() : 0;

          if (deviceX >= rx && deviceX <= rx + rw && deviceY >= ry && deviceY <= ry + rh) {
            devices.push(device.getName());
          }
        }
      }
    }
  } catch (e) {
    return { ok: false, error: "Failed to get devices in rect: " + String(e) };
  }

  return { ok: true, rectId: payload.rectId, devices: devices, clusters: clusters, count: devices.length };
}

// ============================================================================
// Command Dispatcher
// ============================================================================

return (function(payload, ipc, dprint) {
  try {
    dprint("[Runtime] Processing: " + payload.type);
    
    switch (payload.type) {
      case "addDevice": return handleAddDevice(payload);
      case "removeDevice": return handleRemoveDevice(payload);
      case "listDevices": return handleListDevices(payload);
      case "renameDevice": return handleRenameDevice(payload);
      case "addModule": return handleAddModule(payload);
      case "removeModule": return handleRemoveModule(payload);
      case "addLink": return handleAddLink(payload);
      case "removeLink": return handleRemoveLink(payload);
      case "configHost": return handleConfigHost(payload);
      case "configIos": return handleConfigIos(payload);
      case "execIos": return handleExecIos(payload);
      case "snapshot": return handleSnapshot();
      case "inspect": return handleInspect(payload);
      case "hardwareInfo": return handleHardwareInfo();
      case "hardwareCatalog": return handleHardwareCatalog(payload);
      case "commandLog": return handleCommandLog(payload);
      case "listCanvasRects": return handleListCanvasRects(payload);
      case "getRect": return handleGetRect(payload);
      case "devicesInRect": return handleDevicesInRect(payload);
      default: return { ok: false, error: "Unknown command: " + payload.type };
    }
  } catch (e) {
    dprint("[Runtime] Error: " + String(e));
    return { ok: false, error: String(e), stack: String(e.stack || "") };
  }
})(payload, ipc, dprint);
`;

  // Validate before returning - fail fast if generation produced bad code
  validateRuntimeCode(code);

  return code;
}

// ============================================================================
// Exports
// ============================================================================

export const HANDLERS: HandlerMap = {
  addDevice: (p, d) => handleAddDevice(p as unknown as Parameters<typeof handleAddDevice>[0], d),
  removeDevice: (p, d) => handleRemoveDevice(p as unknown as Parameters<typeof handleRemoveDevice>[0], d),
  listDevices: (p, d) => handleListDevices(p as unknown as Parameters<typeof handleListDevices>[0], d),
  renameDevice: (p, d) => handleRenameDevice(p as unknown as Parameters<typeof handleRenameDevice>[0], d),
  addLink: (p, d) => handleAddLink(p as unknown as Parameters<typeof handleAddLink>[0], d),
  removeLink: (p, d) => handleRemoveLink(p as unknown as Parameters<typeof handleRemoveLink>[0], d),
  configHost: (p, d) => handleConfigHost(p as unknown as Parameters<typeof handleConfigHost>[0], d),
  configIos: (p, d) => handleConfigIos(p as unknown as Parameters<typeof handleConfigIos>[0], d),
  execIos: (p, d) => handleExecIos(p as unknown as Parameters<typeof handleExecIos>[0], d),
  snapshot: (p, d) => handleSnapshot(p as unknown as Parameters<typeof handleSnapshot>[0], d),
  inspect: (p, d) => handleInspect(p as unknown as Parameters<typeof handleInspect>[0], d),
  addModule: (p, d) => handleAddModule(p as unknown as Parameters<typeof handleAddModule>[0], d),
  removeModule: (p, d) => handleRemoveModule(p as unknown as Parameters<typeof handleRemoveModule>[0], d),
  listCanvasRects: (p, d) => handleListCanvasRects(p as unknown as Parameters<typeof handleListCanvasRects>[0], d),
  getRect: (p, d) => handleGetRect(p as unknown as Parameters<typeof handleGetRect>[0], d),
  devicesInRect: (p, d) => handleDevicesInRect(p as unknown as Parameters<typeof handleDevicesInRect>[0], d),
};
