/**
 * Runtime Generator - Orchestrates code generation for runtime.js
 * Assembles multiple template modules into a complete runtime
 *
 * PT Control Runtime
 *
 * This runtime is evaluated by main.js.
 * It is intentionally stateless with respect to:
 * - durable queue ownership
 * - recovery
 * - PT module lifecycle
 *
 * All durable / lifecycle concerns belong to main.js or the file bridge.
 */

import { generateConstantsTemplate } from "./templates/constants-template";
import { generateHelpersTemplate } from "./templates/helpers-template";
import { generateSessionTemplate } from "./templates/session-template";
import { generateDeviceHandlersTemplate } from "./templates/device-handlers-template";
import { generateIosConfigHandlersTemplate } from "./templates/ios-config-handlers-template";
import { generateIosExecHandlersTemplate } from "./templates/ios-exec-handlers-template";
import { generateInspectHandlersTemplate } from "./templates/inspect-handlers-template";
import { generateCanvasHandlersTemplate } from "./templates/canvas-handlers-template";
import { generateDispatcherTemplate } from "./templates/dispatcher-template";

/**
 * Generate the complete runtime.js code
 * This function assembles all template modules into a self-contained JavaScript string
 */
export function generateRuntimeCode(): string {
  const code = String.raw`/**
 * PT Control V2 - Runtime
 *
 * Auto-generated by compose.ts - DO NOT EDIT MANUALLY
 * This code runs inside Packet Tracer Script Engine with full IPC access.
 */

${generateConstantsTemplate()}
${generateHelpersTemplate()}
${generateSessionTemplate()}
${generateDeviceHandlersTemplate()}
${generateIosConfigHandlersTemplate()}
${generateIosExecHandlersTemplate()}
${generateInspectHandlersTemplate()}
${generateCanvasHandlersTemplate()}
${generateDispatcherTemplate()}
`;

  return code;
}
