#!/usr/bin/env bun
/**
 * Comando template - Gestión de plantillas de laboratorios CCNA
 * 
 * Implementación local sin dependencias de @cisco-auto/core.
 */

import { Command } from 'commander';
import { writeFileSync } from 'fs';
import { CCNATemplates, getTemplateById, getTemplatesByCategory, getTemplatesByDifficulty } from '../data/templates';
import type { LabTemplate } from '../data/templates';
import type { LabSpec } from '../contracts/lab-spec';

export function createTemplateCommand(): Command {
  const cmd = new Command('template')
    .description('Manage lab templates');

  cmd.command('list')
    .description('List available templates')
    .option('-c, --category <category>', 'Filter by category')
    .option('-d, --difficulty <level>', 'Filter by difficulty (beginner|intermediate|advanced)')
    .action((options) => {
      let templates = CCNATemplates;

      if (options.category) {
        templates = getTemplatesByCategory(options.category);
      }
      if (options.difficulty) {
        templates = getTemplatesByDifficulty(options.difficulty);
      }

      console.log('\n📚 Available Templates:\n');
      console.log('─'.repeat(70));

      for (const t of templates) {
        const difficulty = t.difficulty === 'beginner' ? '🟢' :
                          t.difficulty === 'intermediate' ? '🟡' : '🔴';
        console.log(`${difficulty} ${t.id.padEnd(25)} ${t.name}`);
        console.log(`   ${t.description}`);
        console.log(`   Category: ${t.category} | Time: ${t.estimatedTime}min`);
        console.log('');
      }

      console.log('─'.repeat(70));
      console.log(`Total: ${templates.length} templates`);
    });

  cmd.command('show <id>')
    .description('Show template details')
    .action((id) => {
      const template = getTemplateById(id);

      if (!template) {
        console.error(`❌ Template not found: ${id}`);
        process.exit(1);
      }

      console.log('\n' + '═'.repeat(60));
      console.log(`  ${template.name}`);
      console.log('═'.repeat(60));
      console.log(`\n📝 Description: ${template.description}`);
      console.log(`📊 Difficulty: ${template.difficulty}`);
      console.log(`📁 Category: ${template.category}`);
      console.log(`⏱️  Estimated Time: ${template.estimatedTime} minutes`);

      console.log('\n🎯 Objectives:');
      for (const obj of template.objectives) {
        console.log(`   • ${obj}`);
      }

      const lab = template.create();
      console.log('\n📋 Lab Preview:');
      console.log(`   Devices: ${lab.devices.length}`);
      console.log(`   Connections: ${lab.connections.length}`);

      console.log('\n   Devices:');
      for (const device of lab.devices) {
        console.log(`     • ${device.name} (${device.type})`);
      }

      console.log('\n' + '═'.repeat(60));
    });

  cmd.command('generate <id>')
    .description('Generate a lab file from template')
    .option('-o, --output <file>', 'Output file path', 'lab.yaml')
    .action((id, options) => {
      const template = getTemplateById(id);

      if (!template) {
        console.error(`❌ Template not found: ${id}`);
        process.exit(1);
      }

      const lab = template.create();
      const yaml = generateYAML(lab);

      try {
        writeFileSync(options.output, yaml);
        console.log(`✅ Lab generated: ${options.output}`);
        console.log(`   Template: ${template.name}`);
        console.log(`   Devices: ${lab.devices.length}`);
      } catch (error) {
        console.error(`❌ Failed to write file: ${error}`);
        process.exit(1);
      }
    });

  return cmd;
}

/**
 * Genera YAML desde LabSpec
 */
function generateYAML(lab: LabSpec): string {
  const lines: string[] = [];

  lines.push('# Generated by cisco-auto template');
  lines.push('');
  lines.push('lab:');
  lines.push('  metadata:');
  lines.push(`    name: "${lab.metadata.name}"`);
  lines.push(`    version: "${lab.metadata.version}"`);
  lines.push(`    author: "${lab.metadata.author}"`);
  lines.push('');
  lines.push('  topology:');
  lines.push('    devices:');

  for (const device of lab.devices) {
    lines.push(`      - name: ${device.name}`);
    lines.push(`        type: ${device.type}`);
    if (device.hostname) {
      lines.push(`        hostname: ${device.hostname}`);
    }
    if (device.interfaces && device.interfaces.length > 0) {
      lines.push('        interfaces:');
      for (const iface of device.interfaces) {
        lines.push(`          - name: ${iface.name}`);
        if (iface.ip) {
          lines.push(`            ip: ${iface.ip}`);
        }
        if (iface.description) {
          lines.push(`            description: "${iface.description}"`);
        }
      }
    }
  }

  lines.push('');
  lines.push('    connections:');
  for (const conn of lab.connections) {
    lines.push(`      - from:`);
    lines.push(`          device: ${conn.from.deviceName}`);
    lines.push(`          port: ${conn.from.port}`);
    lines.push(`        to:`);
    lines.push(`          device: ${conn.to.deviceName}`);
    lines.push(`          port: ${conn.to.port}`);
  }

  return lines.join('\n');
}
