import { Command } from 'commander';

/**
 * Tipos de shell soportados
 */
type ShellType = 'bash' | 'zsh' | 'fish' | 'powershell';

/**
 * Genera script de completion para Bash
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generateBashCompletion(programName: string, commands: string[]): string {
  const cmdList = commands.map(c => `'${c}'`).join(' ');
  
  return `#!/bin/bash

# Bash completion for ${programName}
# Generated by ${programName}

_${programName}_completion() {
  local cur prev cmds
  
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD - 1]}"
  
  cmds="${cmdList}"
  
  # Completar comandos
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
    return 0
  fi
  
  # Completar opciones según el comando
  case "\${COMP_WORDS[1]}" in
    parse)
      COMPREPLY=( $(compgen -W "-f --format -t --topology -m --mermaid -s --stats --help" -- "$cur") )
      ;;
    config)
      COMPREPLY=( $(compgen -W "--dry-run --save --host --user --verbose --help" -- "$cur") )
      ;;
    validate)
      COMPREPLY=( $(compgen -W "--json --strict --verbose --help" -- "$cur") )
      ;;
    devices)
      COMPREPLY=( $(compgen -W "--json --filter --verbose --help" -- "$cur") )
      ;;
    deploy)
      COMPREPLY=( $(compgen -W "--save-config --timeout --verbose --help" -- "$cur") )
      ;;
    init)
      COMPREPLY=( $(compgen -W "--template --force --verbose --help" -- "$cur") )
      ;;
    parse-pka)
      COMPREPLY=( $(compgen -W "--yaml --json --output --help" -- "$cur") )
      ;;
    mod-test)
      COMPREPLY=( $(compgen -W "--pc --ip --output --verbose --help" -- "$cur") )
      ;;
    template)
      COMPREPLY=( $(compgen -W "list create apply --help" -- "$cur") )
      ;;
    serve)
      COMPREPLY=( $(compgen -W "--port --host --verbose --help" -- "$cur") )
      ;;
    completion)
      COMPREPLY=( $(compgen -W "bash zsh fish powershell --help" -- "$cur") )
      ;;
  esac
  
  return 0
}

complete -F _${programName}_completion ${programName}
`;
}

/**
 * Genera script de completion para Zsh
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generateZshCompletion(programName: string, commands: string[]): string {
  const cmdList = commands.join(' ');
  
  return `#compdef ${programName}

# Zsh completion for ${programName}
# Generated by ${programName}

local -a cmds
cmds=(
  ${cmdList}
)

_${programName}_command() {
  local -a opts
  
  opts=(
    'parse:Parsear archivo YAML de laboratorio'
    'config:Generar configuraciones IOS'
    'validate:Validar archivo de laboratorio'
    'devices:Listar dispositivos del lab'
    'deploy:Desplegar configuracion a dispositivos'
    'init:Inicializar nuevo laboratorio'
    'parse-pka:Parsear archivo PKA de Packet Tracer'
    'mod-test:Modificar archivo PKA'
    'template:Listar/crear templates'
    'serve:Iniciar servidor API'
    'completion:Generar scripts de completion'
  )
  
  _describe 'command' opts
  _describe 'subcommand' cmds
}

_${programName}_completion() {
  local -a commands options
  
  commands=(
    ${cmdList}
  )
  
  options=(
    '-h[Mostrar ayuda]'
    '--help[Mostrar ayuda]'
    '-v[Modo verbose]'
    '--verbose[Modo verbose]'
    '--json[Salida en formato JSON]'
  )
  
  _arguments -C \\
    '1: :->command' \\
    '*:: :->option-or-arg' \\
    && return 0
    
  case $state in
    command)
      _describe 'command' commands
      ;;
    option-or-arg)
      case $words[1] in
        parse)
          _arguments '*:file:_files'
          ;;
        config)
          _arguments '*:file:_files' '--dry-run[Modo simulacion]' '--save[Guardar configs]'
          ;;
        validate)
          _arguments '*:file:_files'
          ;;
        devices)
          _arguments '*:file:_files'
          ;;
        deploy)
          _arguments '*:file:_files'
          ;;
        *)
          _files
          ;;
      esac
      ;;
  esac
}

_${programName}_completion "$@"
`;
}

/**
 * Genera script de completion para Fish
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generateFishCompletion(programName: string, commands: string[]): string {
  return `# Fish completion for ${programName}
# Generated by ${programName}

complete -c ${programName} -f

# Comandos principales
complete -c ${programName} -n '__fish_use_subcommand' -a 'parse' -d 'Parsear archivo YAML de laboratorio'
complete -c ${programName} -n '__fish_use_subcommand' -a 'config' -d 'Generar configuraciones IOS'
complete -c ${programName} -n '__fish_use_subcommand' -a 'validate' -d 'Validar archivo de laboratorio'
complete -c ${programName} -n '__fish_use_subcommand' -a 'devices' -d 'Listar dispositivos del lab'
complete -c ${programName} -n '__fish_use_subcommand' -a 'deploy' -d 'Desplegar configuracion a dispositivos'
complete -c ${programName} -n '__fish_use_subcommand' -a 'init' -d 'Inicializar nuevo laboratorio'
complete -c ${programName} -n '__fish_use_subcommand' -a 'parse-pka' -d 'Parsear archivo PKA de Packet Tracer'
complete -c ${programName} -n '__fish_use_subcommand' -a 'mod-test' -d 'Modificar archivo PKA'
complete -c ${programName} -n '__fish_use_subcommand' -a 'template' -d 'Listar/crear templates'
complete -c ${programName} -n '__fish_use_subcommand' -a 'serve' -d 'Iniciar servidor API'
complete -c ${programName} -n '__fish_use_subcommand' -a 'completion' -d 'Generar scripts de completion'

# Opciones globales
complete -c ${programName} -n '__fish_use_subcommand' -l help -d 'Mostrar ayuda'
complete -c ${programName} -n '__fish_use_subcommand' -l version -d 'Mostrar version'
complete -c ${programName} -n '__fish_use_subcommand' -l verbose -d 'Modo verbose'
complete -c ${programName} -n '__fish_use_subcommand' -l json -d 'Salida en formato JSON'

# Opciones de parse
complete -c ${programName} -n '__fish_seen_command parse' -l format -d 'Formato de salida (json|summary)'
complete -c ${programName} -n '__fish_seen_command parse' -s f -l format -d 'Formato de salida'
complete -c ${programName} -n '__fish_seen_command parse' -l topology -d 'Mostrar visualizacion de topologia'
complete -c ${programName} -n '__fish_seen_command parse' -s t -l topology -d 'Mostrar topologia'
complete -c ${programName} -n '__fish_seen_command parse' -l mermaid -d 'Generar diagrama Mermaid'
complete -c ${programName} -n '__fish_seen_command parse' -s m -l mermaid -d 'Generar Mermaid'
complete -c ${programName} -n '__fish_seen_command parse' -l stats -d 'Mostrar estadisticas'
complete -c ${programName} -n '__fish_seen_command parse' -s s -l stats -d 'Mostrar stats'

# Opciones de config
complete -c ${programName} -n '__fish_seen_command config' -l dry-run -d 'Modo simulacion sin aplicar'
complete -c ${programName} -n '__fish_seen_command config' -l save -d 'Guardar configs en archivo'
complete -c ${programName} -n '__fish_seen_command config' -l host -d 'Host destino'
complete -c ${programName} -n '__fish_seen_command config' -l user -d 'Usuario SSH'

# Opciones de validate
complete -c ${programName} -n '__fish_seen_command validate' -l json -d 'Salida JSON'
complete -c ${programName} -n '__fish_seen_command validate' -l strict -d 'Modo estricto'
complete -c ${programName} -n '__fish_seen_command validate' -l verbose -d 'Modo detallado'

# Opciones de completion
complete -c ${programName} -n '__fish_seen_command completion' -a 'bash' -d 'Bash completion'
complete -c ${programName} -n '__fish_seen_command completion' -a 'zsh' -d 'Zsh completion'
complete -c ${programName} -n '__fish_seen_command completion' -a 'fish' -d 'Fish completion'
complete -c ${programName} -n '__fish_seen_command completion' -a 'powershell' -d 'PowerShell completion'

# Completar archivos
complete -c ${programName} -n '__fish_seen_command parse config validate devices deploy' -f -a '(
  __fish_complete_suffix .yaml
  __fish_complete_suffix .yml
  __fish_complete_suffix .json
)'
`;
}

/**
 * Genera script de completion para PowerShell
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generatePowerShellCompletion(programName: string, commands: string[]): string {
  return `# PowerShell completion for ${programName}
# Generated by ${programName}

${programName}-Completion {

  param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [System.Management.Automation.CommandTypes]$CommandType,
    
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$WordToComplete,
    
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [System.Management.Automation.CommandCompletion]$CommandAst
  )

  $commands = @(
    @{ Name = 'parse'; Description = 'Parsear archivo YAML de laboratorio' }
    @{ Name = 'config'; Description = 'Generar configuraciones IOS' }
    @{ Name = 'validate'; Description = 'Validar archivo de laboratorio' }
    @{ Name = 'devices'; Description = 'Listar dispositivos del lab' }
    @{ Name = 'deploy'; Description = 'Desplegar configuracion a dispositivos' }
    @{ Name = 'init'; Description = 'Inicializar nuevo laboratorio' }
    @{ Name = 'parse-pka'; Description = 'Parsear archivo PKA de Packet Tracer' }
    @{ Name = 'mod-test'; Description = 'Modificar archivo PKA' }
    @{ Name = 'template'; Description = 'Listar/crear templates' }
    @{ Name = 'serve'; Description = 'Iniciar servidor API' }
    @{ Name = 'completion'; Description = 'Generar scripts de completion' }
  )
  
  $options = @(
    @{ Name = '--help'; Description = 'Mostrar ayuda' }
    @{ Name = '--version'; Description = 'Mostrar version' }
    @{ Name = '--verbose'; Description = 'Modo verbose' }
    @{ Name = '--json'; Description = 'Salida en formato JSON' }
    @{ Name = '-h'; Description = 'Mostrar ayuda (corto)' }
    @{ Name = '-v'; Description = 'Modo verbose (corto)' }
  )
  
  $parseOptions = @(
    @{ Name = '-f, --format'; Description = 'Formato de salida (json|summary)' }
    @{ Name = '-t, --topology'; Description = 'Mostrar visualizacion de topologia' }
    @{ Name = '-m, --mermaid'; Description = 'Generar diagrama Mermaid' }
    @{ Name = '-s, --stats'; Description = 'Mostrar estadisticas' }
  )
  
  $configOptions = @(
    @{ Name = '--dry-run'; Description = 'Modo simulacion sin aplicar' }
    @{ Name = '--save'; Description = 'Guardar configs en archivo' }
    @{ Name = '--host'; Description = 'Host destino' }
    @{ Name = '--user'; Description = 'Usuario SSH' }
  )
  
  $validateOptions = @(
    @{ Name = '--json'; Description = 'Salida JSON' }
    @{ Name = '--strict'; Description = 'Modo estricto' }
    @{ Name = '--verbose'; Description = 'Modo detallado' }
  )
  
  $shellCompletion = @(
    @{ Name = 'bash'; Description = 'Bash completion script' }
    @{ Name = 'zsh'; Description = 'Zsh completion script' }
    @{ Name = 'fish'; Description = 'Fish completion script' }
    @{ Name = 'powershell'; Description = 'PowerShell completion script' }
  )

  # Si es el primer comando, completar nombres de comando
  if ($CommandAst.CommandElements.Count -eq 1) {
    $results = $commands | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
      [System.Management.Automation.CompletionResult]::new(
        $_.Name,
        $_.Name,
        'ParameterValue',
        $_.Description
      )
    }
    return $results
  }
  
  # Completar opciones según el comando
  $currentCmd = $CommandAst.CommandElements[1].ToString()
  
  switch ($currentCmd) {
    'parse' {
      return $parseOptions | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(
          $_.Name,
          $_.Name,
          'ParameterValue',
          $_.Description
        )
      }
    }
    'config' {
      return $configOptions | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(
          $_.Name,
          $_.Name,
          'ParameterValue',
          $_.Description
        )
      }
    }
    'validate' {
      return $validateOptions | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(
          $_.Name,
          $_.Name,
          'ParameterValue',
          $_.Description
        )
      }
    }
    'completion' {
      return $shellCompletion | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(
          $_.Name,
          $_.Name,
          'ParameterValue',
          $_.Description
        )
      }
    }
    default {
      return $options | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
        [System.Management.Automation.CompletionResult]::new(
          $_.Name,
          $_.Name,
          'ParameterValue',
          $_.Description
        )
      }
    }
  }
}

Register-ArgumentCompleter -CommandName ${programName} -ScriptBlock ${programName}-Completion
`;
}

/**
 * Mensaje de instalación para Bash
 */
const BASH_INSTALL = `
# Instalación (agregar a ~/.bashrc o ~/.bash_profile):
# source <(cisco-auto completion bash)

# Para instalación permanente:
# cisco-auto completion bash >> ~/.bashrc

# O usar completado dinámico (requiere Bash 4+):
# curl -o ~/.cisco-auto-complete https://raw.githubusercontent.com/AndresGaibor/cisco-auto/main/completions/cisco-auto.bash
`;

/**
 * Mensaje de instalación para Zsh
 */
const ZSH_INSTALL = `
# Instalación (agregar a ~/.zshrc):
# source <(cisco-auto completion zsh)

# Para instalación permanente:
# cisco-auto completion zsh >> ~/.zshrc
`;

/**
 * Mensaje de instalación para Fish
 */
const FISH_INSTALL = `
# Instalación:
# mkdir -p ~/.config/fish/completions
# cisco-auto completion fish > ~/.config/fish/completions/cisco-auto.fish
`;

/**
 * Mensaje de instalación para PowerShell
 */
const POWERSHELL_INSTALL = `
# Instalación (agregar a $PROFILE):
# cisco-auto completion powershell >> $PROFILE

# O usar import-module:
# cisco-auto completion powershell | Invoke-Expression
`;

/**
 * Lista de comandos disponibles en la CLI
 */
const AVAILABLE_COMMANDS = [
  'parse',
  'config',
  'validate',
  'devices',
  'deploy',
  'init',
  'parse-pka',
  'mod-test',
  'template',
  'serve',
  'completion'
];

/**
 * Crea el comando de completion
 */
export function createCompletionCommand(): Command {
  return new Command('completion')
    .description('Generar scripts de completion para shell')
    .argument('<shell>', 'Shell objetivo: bash, zsh, fish, powershell')
    .action(async (shell: string) => {
      const shellType = shell.toLowerCase() as ShellType;
      
      // Validar shell
      const validShells: ShellType[] = ['bash', 'zsh', 'fish', 'powershell'];
      if (!validShells.includes(shellType)) {
        console.error(`❌ Shell no soportado: ${shell}`);
        console.log('Shells disponibles: bash, zsh, fish, powershell');
        process.exit(1);
      }
      
      const programName = 'cisco-auto';
      let script = '';
      let installMsg = '';
      
      switch (shellType) {
        case 'bash':
          script = generateBashCompletion(programName, AVAILABLE_COMMANDS);
          installMsg = BASH_INSTALL;
          break;
        case 'zsh':
          script = generateZshCompletion(programName, AVAILABLE_COMMANDS);
          installMsg = ZSH_INSTALL;
          break;
        case 'fish':
          script = generateFishCompletion(programName, AVAILABLE_COMMANDS);
          installMsg = FISH_INSTALL;
          break;
        case 'powershell':
          script = generatePowerShellCompletion(programName, AVAILABLE_COMMANDS);
          installMsg = POWERSHELL_INSTALL;
          break;
      }
      
      console.log(script);
      
      // Mostrar instrucciones de instalación
      console.log('\n' + '='.repeat(60));
      console.log('📝 INSTRUCCIONES DE INSTALACIÓN');
      console.log('='.repeat(60));
      console.log(installMsg);
    });
}