import { Command } from 'commander';
import { writeFileSync } from 'fs';
import { CCNATemplates, getTemplateById, getTemplatesByCategory, getTemplatesByDifficulty } from '../../../../src/templates/index.ts';

export function createTemplateCommand(): Command {
  const cmd = new Command('template')
    .description('Manage lab templates');

  // List templates
  cmd.command('list')
    .description('List available templates')
    .option('-c, --category <category>', 'Filter by category')
    .option('-d, --difficulty <level>', 'Filter by difficulty (beginner|intermediate|advanced)')
    .action((options) => {
      let templates = CCNATemplates;
      
      if (options.category) {
        templates = getTemplatesByCategory(options.category);
      }
      if (options.difficulty) {
        templates = getTemplatesByDifficulty(options.difficulty);
      }

      console.log('\n📚 Available Templates:\n');
      console.log('─'.repeat(70));
      
      for (const t of templates) {
        const difficulty = t.difficulty === 'beginner' ? '🟢' : 
                          t.difficulty === 'intermediate' ? '🟡' : '🔴';
        console.log(`${difficulty} ${t.id.padEnd(25)} ${t.name}`);
        console.log(`   ${t.description}`);
        console.log(`   Category: ${t.category} | Time: ${t.estimatedTime}min`);
        console.log('');
      }
      
      console.log('─'.repeat(70));
      console.log(`Total: ${templates.length} templates`);
    });

  // Show template details
  cmd.command('show <id>')
    .description('Show template details')
    .action((id) => {
      const template = getTemplateById(id);
      
      if (!template) {
        console.error(`❌ Template not found: ${id}`);
        process.exit(1);
      }

      console.log('\n' + '═'.repeat(60));
      console.log(`  ${template.name}`);
      console.log('═'.repeat(60));
      console.log(`\n📝 Description: ${template.description}`);
      console.log(`📊 Difficulty: ${template.difficulty}`);
      console.log(`📁 Category: ${template.category}`);
      console.log(`⏱️  Estimated Time: ${template.estimatedTime} minutes`);
      
      console.log('\n🎯 Objectives:');
      for (const obj of template.objectives) {
        console.log(`   • ${obj}`);
      }

      // Show generated lab preview
      const lab = template.create();
      console.log('\n📋 Lab Preview:');
      console.log(`   Devices: ${lab.devices.length}`);
      console.log(`   Connections: ${lab.connections.length}`);
      
      console.log('\n   Devices:');
      for (const device of lab.devices) {
        console.log(`     • ${device.name} (${device.type})`);
      }
      
      console.log('\n' + '═'.repeat(60));
    });

  // Generate lab from template
  cmd.command('generate <id>')
    .description('Generate a lab file from template')
    .option('-o, --output <file>', 'Output file path', 'lab.yaml')
    .action((id, options) => {
      const template = getTemplateById(id);
      
      if (!template) {
        console.error(`❌ Template not found: ${id}`);
        process.exit(1);
      }

      const lab = template.create();
      
      // Convert to YAML format
      const yaml = generateYAML(lab);
      
      try {
        writeFileSync(options.output, yaml);
        console.log(`✅ Lab generated: ${options.output}`);
        console.log(`   Template: ${template.name}`);
        console.log(`   Devices: ${lab.devices.length}`);
      } catch (error) {
        console.error(`❌ Failed to write file: ${error}`);
        process.exit(1);
      }
    });

  return cmd;
}

/**
 * Genera YAML desde LabSpec
 */
function generateYAML(lab: any): string {
  const lines: string[] = [];
  
  lines.push('# Generated by cisco-auto template');
  lines.push('');
  lines.push('lab:');
  lines.push(`  name: "${lab.metadata.name}"`);
  lines.push('  metadata:');
  lines.push(`    version: "${lab.metadata.version}"`);
  lines.push(`    author: "${lab.metadata.author}"`);
  lines.push('');
  lines.push('  topology:');
  lines.push('    devices:');
  
  for (const device of lab.devices) {
    lines.push(`      - name: ${device.name}`);
    lines.push(`        type: ${device.type}`);
    if (device.hostname) {
      lines.push(`        hostname: ${device.hostname}`);
    }
    if (device.interfaces && device.interfaces.length > 0) {
      lines.push('        interfaces:');
      for (const iface of device.interfaces) {
        lines.push(`          - name: ${iface.name}`);
        if (iface.ipAddress) {
          lines.push(`            ip: ${iface.ipAddress}`);
        }
        if (iface.description) {
          lines.push(`            description: "${iface.description}"`);
        }
      }
    }
    if (device.routing) {
      lines.push('        routing:');
      if (device.routing.static) {
        lines.push('          static:');
        for (const route of device.routing.static) {
          lines.push(`            - network: ${route.network}`);
          lines.push(`              nextHop: ${route.nextHop}`);
        }
      }
      if (device.routing.ospf) {
        lines.push('          ospf:');
        lines.push(`            processId: ${device.routing.ospf.processId}`);
        lines.push(`            routerId: ${device.routing.ospf.routerId}`);
        lines.push('            networks:');
        for (const net of device.routing.ospf.networks) {
          lines.push(`              - network: ${net.network}`);
          lines.push(`                wildcard: ${net.wildcard}`);
          lines.push(`                area: ${net.area}`);
        }
      }
    }
    if (device.services?.dhcp) {
      lines.push('        services:');
      lines.push('          dhcp:');
      for (const pool of device.services.dhcp) {
        lines.push(`            - poolName: ${pool.poolName}`);
        lines.push(`              network: ${pool.network}`);
        lines.push(`              subnetMask: ${pool.subnetMask}`);
        if (pool.defaultRouter) {
          lines.push(`              defaultRouter: ${pool.defaultRouter}`);
        }
      }
    }
  }
  
  lines.push('');
  lines.push('    connections:');
  for (const conn of lab.connections) {
    lines.push(`      - from:`);
    lines.push(`          device: ${conn.from.deviceName}`);
    lines.push(`          port: ${conn.from.portName}`);
    lines.push(`        to:`);
    lines.push(`          device: ${conn.to.deviceName}`);
    lines.push(`          port: ${conn.to.portName}`);
    lines.push(`        cable: ${conn.cableType}`);
  }
  
  return lines.join('\n');
}
