// Catálogo de comandos de configuración IOS
// Configuración de interfaces, VLANs, routing, ACLs y más

import type { CommandCatalogEntry } from '../command-catalog-types.js';

export const CONFIG_IOS_COMMANDS: Record<string, CommandCatalogEntry> = {

  'config-host': {
    id: 'config-host',
    summary: 'Configura la dirección IP de un dispositivo',
    longDescription: 'Configura la dirección IP, máscara de subred y gateway en la interfaz primaria de un dispositivo.',
    examples: ['pt config-host R1 --ip 192.168.1.1 --mask 255.255.255.0'],
    related: ['config-ios', 'show'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  vlan: {
    id: 'vlan',
    summary: 'Gestión de VLANs en switches',
    longDescription: 'Crea, elimina y configura VLANs en switches Cisco.',
    examples: ['pt vlan apply Switch1 10 20 30', 'pt vlan create 10 ADMIN'],
    related: ['show vlan', 'config-ios'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  etherchannel: {
    id: 'etherchannel',
    summary: 'Configuración de EtherChannel',
    longDescription: 'Agrupa múltiples interfaces físicas en canales lógicos.',
    examples: ['pt etherchannel create Switch1 1 Gi0/1 Gi0/2', 'pt etherchannel list'],
    related: ['stp', 'vlan'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  'config-ios': {
    id: 'config-ios',
    summary: 'Ejecuta comandos de configuración IOS',
    longDescription: 'Envía comandos de configuración IOS a un dispositivo. Soporta configuración de interfaces, VLANs, routing, ACLs, etc.',
    examples: ['pt config-ios R1 interface GigabitEthernet0/0 ip address 192.168.1.1 255.255.255.0'],
    related: ['config-host', 'show'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
    notes: ['No confiar ciegamente en "ok" sin verificación adicional'],
  },

  routing: {
    id: 'routing',
    summary: 'Configuración de protocolos de routing',
    longDescription: 'Configura protocolos de routing como OSPF, EIGRP, static.',
    examples: ['pt routing ospf enable R1', 'pt routing static add 0.0.0.0 0.0.0.0 192.168.1.1'],
    related: ['show ip-route', 'config-ios'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  acl: {
    id: 'acl',
    summary: 'Configuración de Access Control Lists',
    longDescription: 'Crea y aplica ACLs para filtrar tráfico.',
    examples: ['pt acl create 100 permit tcp any any eq 80', 'pt acl apply ACL-100 R1'],
    related: ['config-ios', 'show'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  stp: {
    id: 'stp',
    summary: 'Configuración de Spanning Tree Protocol',
    longDescription: 'Configura STP en switches para evitar bucles de capa 2.',
    examples: ['pt stp set Switch1 mode rapid-pvst', 'pt stp set Switch1 priority 4096'],
    related: ['vlan', 'etherchannel'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  services: {
    id: 'services',
    summary: 'Servicios de red en Packet Tracer',
    longDescription: 'Configura servicios como DHCP, DNS, HTTP, etc.',
    examples: ['pt services dhcp Switch1', 'pt services dns add 8.8.8.8'],
    related: ['config-ios', 'device'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    requiresPostValidation: true,
  },

  'config-ospf': {
    id: 'config-ospf',
    summary: 'Configurar enrutamiento OSPF',
    longDescription: 'Configura OSPF con process-id, networks y passive-interfaces desde CLI o archivo YAML.',
    examples: ['pt config ospf --device R1 --process-id 1 --network "192.168.1.0,0.0.0.255,0" --dry-run'],
    related: ['config eigrp', 'config bgp', 'show ip route'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

  'config-eigrp': {
    id: 'config-eigrp',
    summary: 'Configurar enrutamiento EIGRP',
    longDescription: 'Configura EIGRP con autonomous system, networks y passive-interfaces.',
    examples: ['pt config eigrp --device R1 --as 100 --network "192.168.1.0,0.0.0.255" --dry-run'],
    related: ['config ospf', 'config bgp', 'show ip route'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

  'config-bgp': {
    id: 'config-bgp',
    summary: 'Configurar enrutamiento BGP',
    longDescription: 'Configura BGP con autonomous system, neighbors y networks.',
    examples: ['pt config bgp --device R1 --as 65000 --neighbor "10.0.0.2,65001" --dry-run'],
    related: ['config ospf', 'config eigrp', 'show ip bgp'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

  'config-acl': {
    id: 'config-acl',
    summary: 'Configurar Access Control Lists',
    longDescription: 'Configura ACLs standard o extended con reglas permit/deny.',
    examples: ['pt config acl --device R1 --name FILTER --type extended --rule "permit,ip,any,any" --dry-run'],
    related: ['config interface', 'show access-lists'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

  'config-vlan': {
    id: 'config-vlan',
    summary: 'Configurar VLANs',
    longDescription: 'Crea y configura VLANs con id, nombre y estado.',
    examples: ['pt config vlan --device S1 --vlan "10,ADMIN" --vlan "20,USERS" --dry-run'],
    related: ['show vlan', 'config interface'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

  'config-interface': {
    id: 'config-interface',
    summary: 'Configurar interfaces',
    longDescription: 'Configura interfaces con IP, mascara, descripcion y estado.',
    examples: ['pt config interface --device R1 --name Gig0/0 --ip 192.168.1.1 --mask 255.255.255.0 --dry-run'],
    related: ['show ip interface brief', 'config ospf'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

  'config-apply': {
    id: 'config-apply',
    summary: 'Aplicar configuración desde archivo YAML/JSON',
    longDescription: 'Lee un archivo de configuración, detecta el tipo y aplica los comandos IOS.',
    examples: ['pt config apply configs/ospf.yaml --dry-run'],
    related: ['config ospf', 'config eigrp', 'config bgp'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
    supportsJson: true,
    supportsPlan: true,
    supportsExplain: true,
    supportsVerify: true,
  },

};