// Catálogo de comandos meta
// Status, lab, deploy, init, parse, template, validate, canvas, omniscience, simulation, lint, dhcp-server, host, show-mac

import type { CommandCatalogEntry } from '../command-catalog-types.js';

export const META_COMMANDS: Record<string, CommandCatalogEntry> = {

  status: {
    id: 'status',
    summary: 'Muestra el estado actual del contexto y Packet Tracer',
    longDescription: 'Muestra un resumen del contexto actual, dispositivos, enlaces y estado de Packet Tracer.',
    examples: ['pt status', 'pt status --verbose'],
    related: ['doctor', 'topology'],
    status: 'stable',
    supportsAutonomousUse: true,
    requiresPT: true,
    requiresContext: true,
  },

  lab: {
    id: 'lab',
    summary: 'Gestión de laboratorios Cisco',
    longDescription: 'Comandos para crear, validar, parsear y levantar laboratorios Cisco en Packet Tracer.',
    examples: ['pt lab list', 'pt lab create', 'pt lab validate', 'pt lab lift'],
    related: ['device', 'topology', 'lab lift'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    notes: [
      'lab create/list/parse/validate/interactive/pipeline son partial',
      'lab lift es experimental - requiere validación adicional',
    ],
  },

  deploy: {
    id: 'deploy',
    summary: 'Desplegar configuraciones Cisco usando kernel plugins',
    longDescription: 'Compila y aplica configuraciones IOS a dispositivos basados en una definición YAML.',
    examples: ['pt deploy lab.yaml', 'pt deploy lab.yaml --device R1 --dry-run'],
    related: ['config-apply', 'config-ios'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesIOS: true,
  },

  init: {
    id: 'init',
    summary: 'Crear un archivo de lab de ejemplo',
    longDescription: 'Genera un archivo YAML base para comenzar a definir un nuevo laboratorio.',
    examples: ['pt init mi-lab'],
    related: ['lab create'],
    status: 'stable',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
  },

  parse: {
    id: 'parse',
    summary: 'Analizar archivo de definición de lab (YAML)',
    longDescription: 'Lee un archivo YAML, extrae estadísticas, valida estructura y opcionalmente genera diagramas.',
    examples: ['pt parse lab.yaml', 'pt parse lab.yaml --mermaid'],
    related: ['validate', 'topology'],
    status: 'stable',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
    supportsJson: true,
  },

  template: {
    id: 'template',
    summary: 'Gestión de plantillas de laboratorios CCNA',
    longDescription: 'Lista, muestra y genera laboratorios a partir de plantillas predefinidas de CCNA.',
    examples: ['pt template list', 'pt template generate basic-lan'],
    related: ['lab', 'init'],
    status: 'partial',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
  },

  validate: {
    id: 'validate',
    summary: 'Validar archivo YAML de laboratorio con chequeos exhaustivos',
    longDescription: 'Realiza validaciones estructurales, físicas y lógicas sobre una definición de laboratorio.',
    examples: ['pt validate lab.yaml', 'pt validate lab.yaml --strict'],
    related: ['parse', 'lab validate'],
    status: 'partial',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
    supportsJson: true,
  },

  canvas: {
    id: 'canvas',
    summary: 'Operaciones sobre el canvas de Packet Tracer',
    longDescription: 'Gestiona elementos visuales del canvas como rectángulos, notas y fondos.',
    examples: ['pt canvas list-rects', 'pt canvas add-note "Red de Ventas" 200 200'],
    related: ['layout', 'device'],
    status: 'experimental',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
  },

  omniscience: {
    id: 'omniscience',
    summary: 'Acceso total al motor C++ de Packet Tracer',
    longDescription: 'Permite evaluar scripts arbitrarios y acceder a datos de bajo nivel inaccesibles vía API oficial.',
    examples: ['pt omniscience eval "ipc.network().getDeviceCount()"'],
    related: ['inspect', 'diagnose'],
    status: 'stable',
    supportsAutonomousUse: true,
    requiresPT: true,
    requiresContext: true,
  },

  simulation: {
    id: 'simulation',
    summary: 'Control del modo simulación',
    longDescription: 'Gestiona el estado de la simulación, filtros de eventos y reproducción de paquetes.',
    examples: ['pt simulation play', 'pt simulation reset'],
    related: ['status'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: false,
  },

  lint: {
    id: 'lint',
    summary: 'Análisis estático de mejores prácticas',
    longDescription: 'Verifica la topología contra un conjunto de reglas de diseño y seguridad.',
    examples: ['pt lint'],
    related: ['validate'],
    status: 'experimental',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: true,
  },

  'dhcp-server': {
    id: 'dhcp-server',
    summary: 'Inspeccionar servidores DHCP',
    longDescription: 'Muestra las concesiones (leases) y estado de pools DHCP en routers o servidores.',
    examples: ['pt dhcp-server leases R1'],
    related: ['services'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
  },

  host: {
    id: 'host',
    summary: 'Configuración de End Devices (PCs, Servers)',
    longDescription: 'Gestiona IPs, gateways y servicios en dispositivos finales.',
    examples: ['pt host config PC1 --ip 192.168.1.10/24'],
    related: ['device'],
    status: 'stable',
    supportsAutonomousUse: true,
    requiresPT: true,
    requiresContext: true,
  },

  'show-mac': {
    id: 'show-mac',
    summary: 'Ver tabla de direcciones MAC',
    longDescription: 'Muestra la CAM table de los switches con filtrado por VLAN o puerto.',
    examples: ['pt show-mac Switch1'],
    related: ['show-vlan'],
    status: 'stable',
    supportsAutonomousUse: true,
    requiresPT: true,
    requiresContext: true,
  },

  show: {
    id: 'show',
    summary: 'Ejecuta comandos show en dispositivos',
    longDescription: 'Ejecuta comandos show en dispositivos para obtener información sobre la configuración y estado.',
    examples: ['pt show ip-int-brief R1', 'pt show vlan Switch1', 'pt show ip-route R1'],
    related: ['config-ios', 'device get'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
  },

  layout: {
    id: 'layout',
    summary: 'Disposición espacial del laboratorio',
    longDescription: 'Orienta el canvas del laboratorio con comandos de alto nivel para acomodar dispositivos y zonas.',
    examples: ['pt layout place R1 right-of S1 --gap 160', 'pt layout grid access-switches --columns 3'],
    related: ['inspect', 'device', 'link'],
    status: 'partial',
    supportsAutonomousUse: false,
    requiresPT: true,
    requiresContext: true,
    writesTopology: true,
    supportsPlan: true,
    supportsExplain: true,
    notes: ['Apunta a layout semántico en vez de coordenadas crudas'],
  },

  'devices-list': {
    id: 'devices-list',
    summary: 'Listar dispositivos guardados en memoria',
    longDescription: 'Muestra dispositivos registrados en la base de datos SQLite.',
    examples: ['pt devices list'],
    related: ['devices add', 'topology show'],
    status: 'partial',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
  },

  'devices-add': {
    id: 'devices-add',
    summary: 'Agregar dispositivo a la memoria',
    longDescription: 'Registra un dispositivo en la base de datos SQLite.',
    examples: ['pt devices add R1 --ip 10.0.0.1'],
    related: ['devices list', 'device add'],
    status: 'partial',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
  },

  'config-prefs': {
    id: 'config-prefs',
    summary: 'Gestionar preferencias',
    longDescription: 'Guarda y recupera preferencias del usuario.',
    examples: ['pt config prefs set default_router 2911', 'pt config prefs get default_router'],
    related: ['config list', 'config set'],
    status: 'partial',
    supportsAutonomousUse: true,
    requiresPT: false,
    requiresContext: false,
  },

};