/**
 * DEVICE SPEC VALIDATOR - TYPES AND CONSTANTS
 * 
 * Tipos de validación y códigos de error
 */

export interface ValidationResult {
  valid: boolean;
  errors: ValidationError[];
  warnings: ValidationWarning[];
  info: ValidationInfo[];
}

export interface ValidationError {
  code: string;
  message: string;
  field: string;
  severity: 'error';
}

export interface ValidationWarning {
  code: string;
  message: string;
  field: string;
  severity: 'warning';
}

export interface ValidationInfo {
  code: string;
  message: string;
  field: string;
  severity: 'info';
}

export const ValidationCodes = {
  INVALID_INTERFACE_NAME: 'IFACE_INVALID_NAME',
  INTERFACE_NOT_ON_DEVICE: 'IFACE_NOT_ON_DEVICE',
  DUPLICATE_INTERFACE: 'IFACE_DUPLICATE',
  INVALID_IP_FORMAT: 'IFACE_INVALID_IP',
  INVALID_SUBNET_MASK: 'IFACE_INVALID_MASK',
  INVALID_VLAN_RANGE: 'IFACE_INVALID_VLAN',
  NATIVE_VLAN_MISMATCH: 'IFACE_NATIVE_VLAN_MISMATCH',
  
  VLAN_INVALID_ID: 'VLAN_INVALID_ID',
  VLAN_DUPLICATE: 'VLAN_DUPLICATE',
  VLAN_INVALID_NAME: 'VLAN_INVALID_NAME',
  VLAN_RANGE_EXCEEDED: 'VLAN_RANGE_EXCEEDED',
  
  ROUTER_ID_INVALID: 'ROUTING_ROUTER_ID_INVALID',
  ROUTER_ID_DUPLICATE: 'ROUTING_ROUTER_ID_DUPLICATE',
  OSPF_AREA_INVALID: 'ROUTING_OSPF_AREA_INVALID',
  OSPF_NETWORK_INVALID: 'ROUTING_OSPF_NETWORK_INVALID',
  EIGRP_ASN_INVALID: 'ROUTING_EIGRP_ASN_INVALID',
  BGP_ASN_INVALID: 'ROUTING_BGP_ASN_INVALID',
  
  ACL_INVALID_NAME: 'SECURITY_ACL_INVALID_NAME',
  ACL_INVALID_RULE: 'SECURITY_ACL_INVALID_RULE',
  
  DEVICE_EXCEEDS_VLAN_LIMIT: 'DEVICE_VLAN_LIMIT',
  DEVICE_EXCEEDS_ACL_LIMIT: 'DEVICE_ACL_LIMIT',
  DEVICE_UNSUPPORTED_FEATURE: 'DEVICE_UNSUPPORTED_FEATURE',
  
  TOPOLOGY_DUPLICATE_IP: 'TOPO_DUPLICATE_IP',
  TOPOLOGY_DUPLICATE_ROUTER_ID: 'TOPO_DUPLICATE_ROUTER_ID',
} as const;
