// ============================================================================
// Module Type Constants (from PT API)
// ============================================================================

export const MODULE_TYPE = {
  eLineCard: 0,
  eNetworkModule: 1,
  eInterfaceCard: 2,
  ePtRouterModule: 3,
  ePtSwitchModule: 4,
  ePtCloudModule: 5,
  ePtRepeaterModule: 6,
  ePtHostModule: 7,
  ePtModemModule: 8,
  ePtLaptopModule: 9,
  ePtTVModule: 10,
  eIpPhonePowerAdapter: 11,
  ePtTabletPCModule: 12,
  ePtPdaModule: 13,
  ePtWirelessEndDeviceModule: 14,
  ePtWiredEndDeviceModule: 15,
  eTrs35: 16,
  eUsb: 17,
  eNonRemovableModule: 18,
  eASAModule: 19,
  eASAPowerAdapter: 20,
  ePtCellTowerModule: 21,
  ePtIoeModule: 22,
  ePtIoeNetworkModule: 23,
  ePtIoeAnalogModule: 24,
  ePtIoeDigitalModule: 25,
  ePtIoeCustomIOModule: 26,
  ePtIoePowerAdapter: 27,
  ePtIoeMcuComponentPowerAdapter: 28,
  ePtRouterPowerAdapter: 29,
  eSfpModule: 30,
  eAccessPointPowerAdaptor: 31,
  eNonRemovableInterfaceCard: 32,
  eCustomModuleType: 2000,
};
