// ============================================================================
// Main.js Template - PT Script Module with Event Listeners
// ============================================================================
// Bridge V2 Layout: Uses commands/, in-flight/, results/, logs/
// ============================================================================

export const MAIN_JS_TEMPLATE = `
/**
 * PT Control V2 - Main Script Module (Bridge V2)
 * 
 * Auto-generated by pt-control-v2 runtime generator.
 * This module runs INSIDE Packet Tracer and provides:
 * - FileWatcher for commands directory
 * - PT Event listeners for real-time updates
 * - Auto-snapshot for state synchronization
 * 
 * Bridge V2 Layout:
 * - commands/: Queue of pending commands
 * - in-flight/: Commands currently being processed
 * - results/<id>.json: Authoritative result for each command
 * - logs/events.current.ndjson: Append-only event journal
 */

// Configuration
var DEV_DIR = {{DEV_DIR_LITERAL}};
var RUNTIME_FILE = DEV_DIR + "/runtime.js";

// V2 Directory layout
var COMMANDS_DIR = DEV_DIR + "/commands";
var IN_FLIGHT_DIR = DEV_DIR + "/in-flight";
var RESULTS_DIR = DEV_DIR + "/results";
var LOGS_DIR = DEV_DIR + "/logs";
var EVENTS_FILE = LOGS_DIR + "/events.current.ndjson";
var STATE_FILE = DEV_DIR + "/state.json";

// State
var fm = null;
var fw = null;
var runtimeFn = null;
var reloadTimer = null;
var commandTimer = null;
var snapshotInterval = null;

// ============================================================================
// Event Helpers
// ============================================================================

function appendEvent(evt) {
  try {
    var line = JSON.stringify(evt) + "\\n";
    fm.appendToFile(EVENTS_FILE, line);
  } catch (e) {
    dprint("[ERROR] Failed to append event: " + String(e));
  }
}

function writeState(state) {
  try {
    fm.writePlainTextToFile(STATE_FILE, JSON.stringify(state));
  } catch (e) {
    dprint("[ERROR] Failed to write state: " + String(e));
  }
}

function safeValue(getter, fallback) {
  try {
    return getter();
  } catch (e) {
    return fallback;
  }
}

function readDeviceState(device) {
  try {
    var name = safeValue(function() { return device.getName(); }, "");
    if (!name) return null;

    var portCount = safeValue(function() { return device.getPortCount(); }, 0);
    var ports = [];

    for (var p = 0; p < portCount; p++) {
      try {
        var port = device.getPortAt(p);
        var portInfo = { name: port.getName() };
        try { portInfo.ipAddress = port.getIpAddress(); } catch(e1) {}
        try { portInfo.subnetMask = port.getSubnetMask(); } catch(e2) {}
        try { portInfo.macAddress = port.getMacAddress(); } catch(e3) {}
        ports.push(portInfo);
      } catch (e) {}
    }

    return {
      name: name,
      model: safeValue(function() { return device.getModel(); }, ""),
      type: safeValue(function() { return device.getType(); }, 0),
      power: safeValue(function() { return device.getPower(); }, false),
      ports: ports
    };
  } catch (e) {
    return null;
  }
}

function collectDevices() {
  var net = ipc.network();
  var count = net.getDeviceCount();
  var devices = {};
  var deviceList = [];

  for (var i = 0; i < count; i++) {
    try {
      var snapshot = readDeviceState(net.getDeviceAt(i));
      if (!snapshot) continue;
      devices[snapshot.name] = snapshot;
      deviceList.push(snapshot);
    } catch (e) {}
  }

  return {
    count: deviceList.length,
    devices: devices,
    list: deviceList
  };
}

// ============================================================================
// Runtime Management
// ============================================================================

function loadRuntime() {
  try {
    if (!fm.fileExists(RUNTIME_FILE)) {
      appendEvent({ type: "error", ts: Date.now(), message: "Runtime file not found" });
      return;
    }

    var code = fm.getFileContents(RUNTIME_FILE);
    if (!code || code.length < 100) {
      appendEvent({ type: "error", ts: Date.now(), message: "Runtime file is suspiciously small or empty" });
      dprint("[ERROR] Runtime file is suspiciously small or empty");
      return;
    }

    // Parse to validate syntax
    var candidate;
    try {
      candidate = new Function("payload", "ipc", "dprint", code);
    } catch (syntaxErr) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        message: "Runtime syntax error: " + String(syntaxErr),
        stack: String(syntaxErr.stack || "")
      });
      dprint("[ERROR] Runtime syntax error: " + String(syntaxErr));
      return;
    }

    // Smoke test: execute with a healthcheck payload
    var smokeTestPassed = false;
    var smokeTestError = null;
    try {
      var smokeResult = candidate(
        { type: "__healthcheck__" },
        ipc,
        function() {} // dprint stub
      );

      // Smoke test passes if it returns an "unknown command" error (not a crash)
      if (smokeResult && smokeResult.error && smokeResult.error.indexOf("Unknown command") !== -1) {
        smokeTestPassed = true;
      } else if (smokeResult && smokeResult.ok === false && smokeResult.error) {
        // Runtime executed but returned our healthcheck as unknown - that's fine
        smokeTestPassed = true;
      } else if (!smokeResult) {
        // Null/undefined result might be OK if runtime is still initializing
        smokeTestPassed = true;
      }
    } catch (execErr) {
      smokeTestError = execErr;
      smokeTestPassed = false;
    }

    if (!smokeTestPassed) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        message: "Runtime smoke test failed" + (smokeTestError ? ": " + String(smokeTestError) : ""),
        stack: smokeTestError ? String(smokeTestError.stack || "") : ""
      });
      dprint("[ERROR] Runtime smoke test failed: " + (smokeTestError ? String(smokeTestError) : "unknown error"));
      return;
    }

    // All checks passed - replace the runtime function
    runtimeFn = candidate;

    appendEvent({ type: "runtime-loaded", ts: Date.now(), version: "2.1", smokeTest: true });
    dprint("[OK] Runtime loaded and smoke-tested successfully");
  } catch (e) {
    appendEvent({
      type: "error",
      ts: Date.now(),
      message: "Failed to load runtime: " + String(e),
      stack: String(e.stack || "")
    });
    dprint("[ERROR] Failed to load runtime: " + String(e));
  }
}

// ============================================================================
// Command Execution (V2 - uses commands/ directory)
// ============================================================================

function pickNextCommand() {
  try {
    if (!fm.directoryExists(COMMANDS_DIR)) {
      return null;
    }
    
    var files = fm.listDirectory(COMMANDS_DIR);
    if (!files || files.length === 0) {
      return null;
    }
    
    // Sort files to get deterministic order
    var jsonFiles = [];
    for (var i = 0; i < files.length; i++) {
      if (files[i].endsWith(".json")) {
        jsonFiles.push(files[i]);
      }
    }
    
    if (jsonFiles.length === 0) {
      return null;
    }
    
    // Sort to ensure deterministic ordering
    jsonFiles.sort();
    
    var cmdFile = jsonFiles[0];
    var cmdPath = COMMANDS_DIR + "/" + cmdFile;
    var inFlightPath = IN_FLIGHT_DIR + "/" + cmdFile;
    
    // Move to in-flight
    var cmdContent = fm.getFileContents(cmdPath);
    fm.deleteFile(cmdPath);
    
    // Ensure in-flight dir exists
    if (!fm.directoryExists(IN_FLIGHT_DIR)) {
      fm.makeDirectory(IN_FLIGHT_DIR);
    }
    
    // Write to in-flight
    fm.writePlainTextToFile(inFlightPath, cmdContent);
    
    return JSON.parse(cmdContent);
  } catch (e) {
    dprint("[ERROR] Failed to pick command: " + String(e));
    return null;
  }
}

function runCommand() {
  try {
    // V2: Pick command from commands/ directory
    var cmd = pickNextCommand();
    
    if (!cmd) {
      return;
    }
    
    if (!cmd || !cmd.payload) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        id: cmd && cmd.id ? cmd.id : "unknown",
        message: "Invalid command format"
      });
      return;
    }

    dprint("[INFO] Executing command: " + cmd.payload.type);

    if (!runtimeFn) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        id: cmd.id,
        message: "Runtime not loaded"
      });
      return;
    }

    var startedAt = Date.now();
    
    // Execute runtime with payload
    var result = runtimeFn(cmd.payload, ipc, dprint);

    // V2: Write result to results/<id>.json
    if (cmd.id) {
      try {
        if (!fm.directoryExists(RESULTS_DIR)) {
          fm.makeDirectory(RESULTS_DIR);
        }
        var resultEnvelope = {
          protocolVersion: 2,
          id: cmd.id,
          seq: cmd.seq || 0,
          startedAt: startedAt,
          completedAt: Date.now(),
          status: result && result.ok !== false ? "completed" : "failed",
          ok: result && result.ok !== false,
          value: result
        };
        fm.writePlainTextToFile(RESULTS_DIR + "/" + cmd.id + ".json", JSON.stringify(resultEnvelope));
      } catch (e) {
        dprint("[WARN] Failed to write result file: " + String(e));
      }
    }

    appendEvent({
      type: "result",
      ts: Date.now(),
      id: cmd.id,
      ok: result && result.ok !== false,
      value: result,
      parsed: result && result.parsed ? result.parsed : undefined
    });

    // V2: Clean up in-flight file
    if (cmd.id) {
      try {
        var inFlightFile = IN_FLIGHT_DIR + "/" + String(cmd.seq || "0").padStart(12, "0") + "-" + (cmd.payload.type || "unknown") + ".json";
        if (fm.fileExists(inFlightFile)) {
          fm.deleteFile(inFlightFile);
        }
      } catch (e) {
        dprint("[WARN] Failed to clean up in-flight: " + String(e));
      }
    }

    dprint("[OK] Command executed successfully");

  } catch (e) {
    appendEvent({
      type: "error",
      ts: Date.now(),
      id: typeof cmd !== "undefined" && cmd && cmd.id ? cmd.id : "unknown",
      message: String(e),
      stack: String(e.stack || "")
    });
    dprint("[ERROR] Failed to execute command: " + String(e));
  }
}

// ============================================================================
// PT Event Listeners
// ============================================================================

function setupEventListeners() {
  try {
    var lw = ipc.appWindow().getActiveWorkspace().getLogicalWorkspace();
    var cl = ipc.commandLog();
    
    // Topology events
    lw.registerEvent("deviceAdded", null, function(src, args) {
      appendEvent({
        type: "device-added",
        ts: Date.now(),
        name: args.name,
        model: args.model,
        uuid: args.uuid
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("deviceRemoved", null, function(src, args) {
      appendEvent({
        type: "device-removed",
        ts: Date.now(),
        name: args.name,
        uuid: args.uuid
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("linkCreated", null, function(src, args) {
      appendEvent({
        type: "link-created",
        ts: Date.now(),
        device1: args.device1 || args.device1Name,
        port1: args.port1 || args.port1Name,
        device2: args.device2 || args.device2Name,
        port2: args.port2 || args.port2Name,
        connType: args.connType
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("linkDeleted", null, function(src, args) {
      appendEvent({
        type: "link-deleted",
        ts: Date.now(),
        device1: args.device1 || args.device1Name,
        port1: args.port1 || args.port1Name,
        device2: args.device2 || args.device2Name,
        port2: args.port2 || args.port2Name
      });
      triggerSnapshot();
    });
    
    // Command log events
    cl.setEnabled(true);
    cl.registerEvent("entryAdded", null, function(src, args) {
      try {
        var entry = cl.getEntryAt(args.index);
        appendEvent({
          type: "cli-command",
          ts: Date.now(),
          index: args.index,
          device: entry.getDeviceName ? entry.getDeviceName() : "",
          prompt: entry.getPrompt ? entry.getPrompt() : "",
          command: entry.getCommand ? entry.getCommand() : "",
          resolvedCommand: entry.getResolvedCommand ? entry.getResolvedCommand() : ""
        });
      } catch (e) {
        // Skip invalid entries
      }
    });
    
    dprint("[OK] Event listeners registered");
    
  } catch (e) {
    dprint("[WARN] Failed to setup event listeners: " + String(e));
  }
}

// ============================================================================
// Snapshot
// ============================================================================

function generateSnapshot() {
  try {
    var collected = collectDevices();
    var links = {};
    
    return {
      version: "1.0",
      timestamp: Date.now(),
      devices: collected.devices,
      links: links,
      metadata: {
        deviceCount: collected.count,
        linkCount: Object.keys(links).length
      }
    };
    
  } catch (e) {
    dprint("[ERROR] Failed to generate snapshot: " + String(e));
    return null;
  }
}

function triggerSnapshot() {
  var snapshot = generateSnapshot();
  if (snapshot) {
    writeState(snapshot);
    appendEvent({
      type: "snapshot",
      ts: Date.now(),
      devices: snapshot.metadata.deviceCount,
      links: snapshot.metadata.linkCount
    });
  }
}

// ============================================================================
// File Watcher (V2 - watches commands/ directory)
// ============================================================================

function ensureDirectory(path) {
  try {
    if (!fm.directoryExists(path)) {
      fm.makeDirectory(path);
    }
  } catch (e) {
    dprint("[WARN] Failed to create directory " + path + ": " + String(e));
  }
}

function onFileChanged(src, args) {
  var path = args.path;
  
  if (path === RUNTIME_FILE) {
    if (reloadTimer) clearTimeout(reloadTimer);
    reloadTimer = setTimeout(function() {
      loadRuntime();
    }, 80);
  }
  
  // V2: Watch for new command files in commands/
  if (path.indexOf(COMMANDS_DIR) === 0 && path.endsWith(".json")) {
    if (commandTimer) clearTimeout(commandTimer);
    commandTimer = setTimeout(function() {
      runCommand();
    }, 50);
  }
}

// ============================================================================
// Main
// ============================================================================

function main() {
  dprint("=== PT Control V2 Starting (Bridge V2) ===");
  
  try {
    fm = ipc.systemFileManager();
    fw = fm.getFileWatcher();

    // Ensure V2 directories exist
    if (!fm.directoryExists(DEV_DIR)) {
      fm.makeDirectory(DEV_DIR);
      dprint("[INFO] Created dev directory: " + DEV_DIR);
    }
    
    ensureDirectory(COMMANDS_DIR);
    ensureDirectory(IN_FLIGHT_DIR);
    ensureDirectory(RESULTS_DIR);
    ensureDirectory(LOGS_DIR);

    // Setup file watcher
    fw.addPath(RUNTIME_FILE);
    fw.addPath(COMMANDS_DIR);  // V2: Watch the commands directory
    fw.registerEvent("fileChanged", null, onFileChanged);

    // Init event
    appendEvent({ type: "init", ts: Date.now(), version: "2.1" });
    
    // Setup PT event listeners
    setupEventListeners();
    
    // Load runtime if exists
    if (fm.fileExists(RUNTIME_FILE)) {
      loadRuntime();
    }

    // Initial snapshot
    triggerSnapshot();
    
    // Auto-snapshot every 5 seconds
    snapshotInterval = setInterval(function() {
      triggerSnapshot();
    }, 5000);
    
    dprint("[OK] PT Control V2 initialized (Bridge V2)");
    dprint("[INFO] Watching: " + DEV_DIR);
    dprint("[INFO] Commands dir: " + COMMANDS_DIR);

  } catch (e) {
    dprint("[FATAL] Failed to initialize: " + String(e));
    appendEvent({
      type: "error",
      ts: Date.now(),
      message: "Failed to initialize module: " + String(e),
      stack: String(e.stack || "")
    });
  }
}

function cleanUp() {
  dprint("=== PT Control V2 Stopping ===");
  
  if (reloadTimer) clearTimeout(reloadTimer);
  if (commandTimer) clearTimeout(commandTimer);
  if (snapshotInterval) clearInterval(snapshotInterval);
  
  appendEvent({ type: "log", ts: Date.now(), level: "info", message: "Module stopped" });
}
`;
