// ============================================================================
// Main.js Template - PT Script Module with Event Listeners
// ============================================================================

export const MAIN_JS_TEMPLATE = `/**
 * PT Control V2 - Main Script Module
 * 
 * Auto-generated by pt-control-v2 runtime generator.
 * This module runs INSIDE Packet Tracer and provides:
 * - FileWatcher for commands
 * - PT Event listeners for real-time updates
 * - Auto-snapshot for state synchronization
 */

// Configuration
var DEV_DIR = {{DEV_DIR_LITERAL}};
var RUNTIME_FILE = DEV_DIR + "/runtime.js";
var COMMAND_FILE = DEV_DIR + "/command.json";
var EVENTS_FILE = DEV_DIR + "/events.ndjson";
var STATE_FILE = DEV_DIR + "/state.json";

// State
var fm = null;
var fw = null;
var runtimeFn = null;
var reloadTimer = null;
var commandTimer = null;
var snapshotInterval = null;

// ============================================================================
// Event Helpers
// ============================================================================

function appendEvent(evt) {
  try {
    var prev = fm.fileExists(EVENTS_FILE) ? fm.getFileContents(EVENTS_FILE) : "";
    var line = JSON.stringify(evt) + "\\n";
    fm.writePlainTextToFile(EVENTS_FILE, prev + line);
  } catch (e) {
    dprint("[ERROR] Failed to append event: " + String(e));
  }
}

function writeState(state) {
  try {
    fm.writePlainTextToFile(STATE_FILE, JSON.stringify(state));
  } catch (e) {
    dprint("[ERROR] Failed to write state: " + String(e));
  }
}

function safeValue(getter, fallback) {
  try {
    return getter();
  } catch (e) {
    return fallback;
  }
}

function readDeviceState(device) {
  try {
    var name = safeValue(function() { return device.getName(); }, "");
    if (!name) return null;

    var portCount = safeValue(function() { return device.getPortCount(); }, 0);
    var ports = [];

    for (var p = 0; p < portCount; p++) {
      try {
        var port = device.getPortAt(p);
        var portInfo = { name: port.getName() };
        try { portInfo.ipAddress = port.getIpAddress(); } catch(e1) {}
        try { portInfo.subnetMask = port.getSubnetMask(); } catch(e2) {}
        try { portInfo.macAddress = port.getMacAddress(); } catch(e3) {}
        ports.push(portInfo);
      } catch (e) {}
    }

    return {
      name: name,
      model: safeValue(function() { return device.getModel(); }, ""),
      type: safeValue(function() { return device.getType(); }, 0),
      power: safeValue(function() { return device.getPower(); }, false),
      ports: ports
    };
  } catch (e) {
    return null;
  }
}

function collectDevices() {
  var net = ipc.network();
  var count = net.getDeviceCount();
  var devices = {};
  var deviceList = [];

  for (var i = 0; i < count; i++) {
    try {
      var snapshot = readDeviceState(net.getDeviceAt(i));
      if (!snapshot) continue;
      devices[snapshot.name] = snapshot;
      deviceList.push(snapshot);
    } catch (e) {}
  }

  return {
    count: deviceList.length,
    devices: devices,
    list: deviceList
  };
}

// ============================================================================
// Runtime Management
// ============================================================================

function loadRuntime() {
  try {
    if (!fm.fileExists(RUNTIME_FILE)) {
      appendEvent({ type: "error", ts: Date.now(), message: "Runtime file not found" });
      return;
    }

    var code = fm.getFileContents(RUNTIME_FILE);
    runtimeFn = new Function("payload", "ipc", "dprint", code);
    
    appendEvent({ type: "runtime-loaded", ts: Date.now(), version: "2.0" });
    dprint("[OK] Runtime loaded successfully");
  } catch (e) {
    appendEvent({ 
      type: "error", 
      ts: Date.now(), 
      message: "Failed to load runtime: " + String(e),
      stack: String(e.stack || "")
    });
    dprint("[ERROR] Failed to load runtime: " + String(e));
  }
}

// ============================================================================
// Command Execution
// ============================================================================

function runCommand() {
  try {
    if (!fm.fileExists(COMMAND_FILE)) {
      return;
    }

    var cmdContent = fm.getFileContents(COMMAND_FILE);
    var cmd = JSON.parse(cmdContent);
    
    if (!cmd || !cmd.payload) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        id: cmd && cmd.id ? cmd.id : "unknown",
        message: "Invalid command format"
      });
      return;
    }

    dprint("[INFO] Executing command: " + cmd.payload.type);

    if (!runtimeFn) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        id: cmd.id,
        message: "Runtime not loaded"
      });
      return;
    }

    // Execute runtime with payload
    var result = runtimeFn(cmd.payload, ipc, dprint);

    appendEvent({
      type: "result",
      ts: Date.now(),
      id: cmd.id,
      ok: result && result.ok !== false,
      value: result,
      parsed: result && result.parsed ? result.parsed : undefined
    });

    dprint("[OK] Command executed successfully");

  } catch (e) {
    appendEvent({
      type: "error",
      ts: Date.now(),
      id: typeof cmd !== "undefined" && cmd && cmd.id ? cmd.id : "unknown",
      message: String(e),
      stack: String(e.stack || "")
    });
    dprint("[ERROR] Failed to execute command: " + String(e));
  }
}

// ============================================================================
// PT Event Listeners
// ============================================================================

function setupEventListeners() {
  try {
    var lw = ipc.appWindow().getActiveWorkspace().getLogicalWorkspace();
    var cl = ipc.commandLog();
    
    // Topology events
    lw.registerEvent("deviceAdded", null, function(src, args) {
      appendEvent({
        type: "device-added",
        ts: Date.now(),
        name: args.name,
        model: args.model,
        uuid: args.uuid
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("deviceRemoved", null, function(src, args) {
      appendEvent({
        type: "device-removed",
        ts: Date.now(),
        name: args.name,
        uuid: args.uuid
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("linkCreated", null, function(src, args) {
      appendEvent({
        type: "link-created",
        ts: Date.now(),
        device1: args.device1 || args.device1Name,
        port1: args.port1 || args.port1Name,
        device2: args.device2 || args.device2Name,
        port2: args.port2 || args.port2Name,
        connType: args.connType
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("linkDeleted", null, function(src, args) {
      appendEvent({
        type: "link-deleted",
        ts: Date.now(),
        device1: args.device1 || args.device1Name,
        port1: args.port1 || args.port1Name,
        device2: args.device2 || args.device2Name,
        port2: args.port2 || args.port2Name
      });
      triggerSnapshot();
    });
    
    // Command log events
    cl.setEnabled(true);
    cl.registerEvent("entryAdded", null, function(src, args) {
      try {
        var entry = cl.getEntryAt(args.index);
        appendEvent({
          type: "cli-command",
          ts: Date.now(),
          index: args.index,
          device: entry.getDeviceName ? entry.getDeviceName() : "",
          prompt: entry.getPrompt ? entry.getPrompt() : "",
          command: entry.getCommand ? entry.getCommand() : "",
          resolvedCommand: entry.getResolvedCommand ? entry.getResolvedCommand() : ""
        });
      } catch (e) {
        // Skip invalid entries
      }
    });
    
    dprint("[OK] Event listeners registered");
    
  } catch (e) {
    dprint("[WARN] Failed to setup event listeners: " + String(e));
  }
}

// ============================================================================
// Snapshot
// ============================================================================

function generateSnapshot() {
  try {
    var collected = collectDevices();
    var links = {};
    
    return {
      version: "1.0",
      timestamp: Date.now(),
      devices: collected.devices,
      links: links,
      metadata: {
        deviceCount: collected.count,
        linkCount: Object.keys(links).length
      }
    };
    
  } catch (e) {
    dprint("[ERROR] Failed to generate snapshot: " + String(e));
    return null;
  }
}

function triggerSnapshot() {
  var snapshot = generateSnapshot();
  if (snapshot) {
    writeState(snapshot);
    appendEvent({
      type: "snapshot",
      ts: Date.now(),
      devices: snapshot.metadata.deviceCount,
      links: snapshot.metadata.linkCount
    });
  }
}

// ============================================================================
// File Watcher
// ============================================================================

function onFileChanged(src, args) {
  var path = args.path;
  
  if (path === RUNTIME_FILE) {
    if (reloadTimer) clearTimeout(reloadTimer);
    reloadTimer = setTimeout(function() {
      loadRuntime();
    }, 80);
  }
  
  if (path === COMMAND_FILE) {
    if (commandTimer) clearTimeout(commandTimer);
    commandTimer = setTimeout(function() {
      runCommand();
    }, 50);
  }
}

// ============================================================================
// Main
// ============================================================================

function main() {
  dprint("=== PT Control V2 Starting ===");
  
  try {
    fm = ipc.systemFileManager();
    fw = fm.getFileWatcher();

    // Ensure dev directory exists
    if (!fm.directoryExists(DEV_DIR)) {
      fm.makeDirectory(DEV_DIR);
      dprint("[INFO] Created dev directory: " + DEV_DIR);
    }

    // Clear events file on startup
    if (fm.fileExists(EVENTS_FILE)) {
      fm.writePlainTextToFile(EVENTS_FILE, "");
    }

    // Setup file watcher
    fw.addPath(RUNTIME_FILE);
    fw.addPath(COMMAND_FILE);
    fw.registerEvent("fileChanged", null, onFileChanged);

    // Init event
    appendEvent({ type: "init", ts: Date.now(), version: "2.0" });
    
    // Setup PT event listeners
    setupEventListeners();
    
    // Load runtime if exists
    if (fm.fileExists(RUNTIME_FILE)) {
      loadRuntime();
    }

    // Initial snapshot
    triggerSnapshot();
    
    // Auto-snapshot every 5 seconds
    snapshotInterval = setInterval(function() {
      triggerSnapshot();
    }, 5000);
    
    dprint("[OK] PT Control V2 initialized");
    dprint("[INFO] Watching: " + DEV_DIR);

  } catch (e) {
    dprint("[FATAL] Failed to initialize: " + String(e));
    appendEvent({
      type: "error",
      ts: Date.now(),
      message: "Failed to initialize module: " + String(e),
      stack: String(e.stack || "")
    });
  }
}

function cleanUp() {
  dprint("=== PT Control V2 Stopping ===");
  
  if (reloadTimer) clearTimeout(reloadTimer);
  if (commandTimer) clearTimeout(commandTimer);
  if (snapshotInterval) clearInterval(snapshotInterval);
  
  appendEvent({ type: "log", ts: Date.now(), level: "info", message: "Module stopped" });
}
`;
