import type { PtHelperMaps } from "./pt-helpers";

export const PT_HELPER_MAPS: PtHelperMaps = {
  PT_MODEL_MAP: {},
  PT_DEVICE_TYPE_MAP: {},
  PT_PORT_MAP: {},
  PT_MODULE_CATALOG: {},
  PT_DEVICE_MODULE_SLOTS: {},
  CABLE_CONNECTOR_COMPATIBILITY: {
    'straight': ['rj45'],
    'cross': ['rj45'],
    'ethernet-straight': ['rj45'],
    'ethernet-cross': ['rj45'],
    'fiber': ['sfp', 'sfp+'],
    'serial': ['serial'],
    'console': ['console'],
    'phone': ['rj45'],
    'cable': ['rj45'],
    'roll': ['rj45'],
    'auto': ['rj45', 'sfp', 'sfp+', 'serial', 'console'],
    'wireless': ['rj45'],
    'coaxial': ['rj45'],
    'octal': ['rj45'],
    'cellular': ['rj45'],
    'usb': ['usb'],
  },
  CABLE_TYPES: {
    'auto': -1,
    'straight': 0,
    'cross': 1,
    'ethernet-straight': 8100,
    'ethernet-cross': 8101,
    'fiber': 2,
    'serial': 3,
    'console': 4,
    'phone': 5,
    'cable': 6,
    'roll': 7,
    'wireless': 8,
    'coaxial': 9,
    'custom': 10,
    'octal': 11,
    'cellular': 12,
    'usb': 13,
  },
  DEVICE_TYPES: {
    router: 0,
    switch: 1,
    hub: 2,
    bridge: 3,
    repeater: 4,
    coaxialSplitter: 5,
    wireless: 7,
    pc: 8,
    server: 9,
    printer: 10,
    wirelessRouter: 11,
    ipPhone: 12,
    dslModem: 13,
    cableModem: 14,
    multilayerSwitch: 16,
    laptop: 18,
    tablet: 19,
    smartphone: 20,
    wirelessEndDevice: 21,
    wiredEndDevice: 22,
    tv: 23,
    homeVoip: 24,
    analogPhone: 25,
    firewall: 27,
    dlc: 29,
    homeRouter: 30,
    cellTower: 31,
    centralOfficeServer: 32,
    iot: 34,
    sniffer: 35,
    mcu: 36,
    sbc: 37,
  },
};
