// ============================================================================
// Runtime Composer - Assembles handlers into executable runtime.js
// ============================================================================

import { CABLE_TYPES, DEVICE_TYPES, MODEL_ALIASES, CABLE_TYPE_NAMES } from "./utils/constants";
import {
  resolveModel,
  getDeviceTypeForModel,
  getDeviceTypeCandidates,
  createDeviceWithFallback,
  type PTLogicalWorkspace,
  type PTNetwork,
  type PTDevice,
  type PTPort,
  type PTCommandLine,
  type HandlerDeps,
  type HandlerResult,
} from "./utils/helpers";
import {
  handleAddDevice,
  handleRemoveDevice,
  handleListDevices,
  handleRenameDevice,
} from "./handlers/device";
import { handleAddLink, handleRemoveLink } from "./handlers/link";
import { handleConfigHost, handleConfigIos, handleExecIos } from "./handlers/config";
import { handleInspect, handleSnapshot } from "./handlers/inspect";
import { handleAddModule, handleRemoveModule } from "./handlers/module";

// ============================================================================
// Handler Map Type
// ============================================================================

type HandlerFn = (payload: Record<string, unknown>, deps: HandlerDeps) => HandlerResult;

interface HandlerMap {
  [key: string]: HandlerFn;
}

// ============================================================================
// Compose Runtime
// ============================================================================

/**
 * Generate the complete runtime.js code
 * This function creates a self-contained JavaScript string that runs in PT
 */
export function composeRuntime(): string {
  return String.raw`/**
 * PT Control V2 - Runtime
 * 
 * Auto-generated by compose.ts - DO NOT EDIT MANUALLY
 * This code runs inside Packet Tracer Script Engine with full IPC access.
 */

// ============================================================================
// Constants
// ============================================================================

var CABLE_TYPES = ${JSON.stringify(CABLE_TYPES)};

var DEVICE_TYPES = ${JSON.stringify(DEVICE_TYPES)};

var MODEL_ALIASES = ${JSON.stringify(MODEL_ALIASES)};

var CABLE_TYPE_NAMES = ${JSON.stringify(CABLE_TYPE_NAMES)};

// ============================================================================
// Helpers
// ============================================================================

function getLW() {
  return ipc.appWindow().getActiveWorkspace().getLogicalWorkspace();
}

function getNet() {
  return ipc.network();
}

function resolveModel(model) {
  if (!model) return "2911";
  var key = model.toLowerCase();
  return MODEL_ALIASES[key] || model;
}

function getDeviceTypeForModel(model) {
  var name = (model || "").toLowerCase();
  if (name.indexOf("2960") === 0 || name.indexOf("3560") === 0 || name.indexOf("switch") >= 0) return DEVICE_TYPES.switch;
  if (name.indexOf("pc") === 0 || name.indexOf("laptop") === 0) return DEVICE_TYPES.pc;
  if (name.indexOf("server") === 0) return DEVICE_TYPES.server;
  if (name.indexOf("accesspoint") >= 0 || name.indexOf("wireless") >= 0) return DEVICE_TYPES.wireless;
  if (name.indexOf("cloud") >= 0) return DEVICE_TYPES.cloud;
  return DEVICE_TYPES.router;
}

function getDeviceTypeCandidates(model) {
  var normalized = (model || "").toLowerCase();
  
  if (normalized.indexOf("2960") === 0 || normalized.indexOf("3560") === 0 || normalized.indexOf("switch") >= 0) {
    return [DEVICE_TYPES.switch, DEVICE_TYPES.router];
  }
  
  if (normalized.indexOf("pc") === 0 || normalized.indexOf("laptop") === 0) {
    var candidates = [DEVICE_TYPES.pc, DEVICE_TYPES.end];
    for (var t = 8; t <= 60; t++) {
      if (candidates.indexOf(t) === -1) candidates.push(t);
    }
    return candidates;
  }
  
  if (normalized.indexOf("server") === 0) {
    var serverCandidates = [DEVICE_TYPES.server, DEVICE_TYPES.end];
    for (var s = 8; s <= 60; s++) {
      if (serverCandidates.indexOf(s) === -1) serverCandidates.push(s);
    }
    return serverCandidates;
  }
  
  return [DEVICE_TYPES.router, DEVICE_TYPES.switch, DEVICE_TYPES.pc];
}

function createDeviceWithFallback(model, x, y, typeList, lw, net) {
  for (var i = 0; i < typeList.length; i++) {
    var typeId = typeList[i];
    var autoName = lw.addDevice(typeId, model, x, y);
    if (!autoName) continue;
    
    var device = net.getDevice(autoName);
    if (!device) {
      lw.removeDevice(autoName);
      continue;
    }
    
    var deviceModel = "";
    try { deviceModel = (device.getModel && device.getModel()) || ""; } catch (e) {}
    
    if (deviceModel && deviceModel.toLowerCase() === model.toLowerCase()) {
      return { autoName: autoName, device: device, typeId: typeId };
    }
    
    lw.removeDevice(autoName);
  }
  return null;
}

// ============================================================================
// IOS Output Parsers
// ============================================================================

var IOS_PARSERS = {
  "show ip interface brief": function(output) {
    var lines = output.split("\n");
    var interfaces = [];
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      var match = line.match(/^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)$/);
      if (match && !match[1].startsWith("Interface")) {
        interfaces.push({
          interface: match[1],
          ipAddress: match[2],
          ok: match[3],
          method: match[4],
          status: match[5],
          protocol: match[6]
        });
      }
    }
    return { raw: output, interfaces: interfaces };
  },
  
  "show vlan brief": function(output) {
    var lines = output.split("\n");
    var vlans = [];
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      var match = line.match(/^(\d+)\s+(\S+)\s+(\S+)\s*(.*?)$/);
      if (match) {
        var ports = match[4] ? match[4].split(",").map(function(p) { return p.trim(); }).filter(function(p) { return p; }) : [];
        vlans.push({
          id: parseInt(match[1]),
          name: match[2],
          status: match[3],
          ports: ports
        });
      }
    }
    return { raw: output, vlans: vlans };
  },
  
  "show vlan": function(output) {
    return IOS_PARSERS["show vlan brief"](output);
  },
  
  "show ip route": function(output) {
    var lines = output.split("\n");
    var routes = [];
    var gatewayOfLastResort = null;
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      
      var gwMatch = line.match(/Gateway of last resort is (.+)/i);
      if (gwMatch) {
        gatewayOfLastResort = gwMatch[1];
        continue;
      }
      
      var routeMatch = line.match(/^([CLSORDBEIUM\*])\s+(\S+)\s+(?:is\s+)?(.+)$/);
      if (routeMatch) {
        var typeCode = routeMatch[1];
        var network = routeMatch[2];
        var rest = routeMatch[3];
        
        var route = {
          type: typeCode,
          network: network,
          nextHop: null,
          interface: null
        };
        
        if (rest.indexOf("directly connected") >= 0) {
          var ifaceMatch = rest.match(/connected,?\s*(\S+)/);
          if (ifaceMatch) route.interface = ifaceMatch[1];
        } else if (rest.indexOf("via") >= 0) {
          var viaMatch = rest.match(/via\s+(\S+)/);
          if (viaMatch) route.nextHop = viaMatch[1].replace(",", "");
        }
        
        routes.push(route);
      }
    }
    
    return { raw: output, routes: routes, gatewayOfLastResort: gatewayOfLastResort };
  },
  
  "show running-config": function(output) {
    var sections = {};
    var currentSection = null;
    var currentContent = [];
    var hostname = null;
    var interfaces = {};
    var lines = output.split("\n");
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      
      if (line.indexOf("hostname ") === 0) {
        hostname = line.substring(9).trim();
      }
      
      if (line.indexOf("!") === 0) {
        if (currentSection) {
          sections[currentSection] = currentContent.join("\n");
        }
        currentSection = null;
        currentContent = [];
      } else if (line.indexOf("interface ") === 0) {
        currentSection = line.trim();
        currentContent = [line];
        interfaces[line.substring(10).trim()] = "";
      } else if (line.indexOf("vlan ") === 0 || line.indexOf("router ") === 0) {
        currentSection = line.trim();
        currentContent = [line];
      } else if (currentSection) {
        currentContent.push(line);
      }
    }
    
    return { raw: output, hostname: hostname, sections: sections, interfaces: interfaces };
  },
  
  "show interfaces": function(output) {
    var interfaces = [];
    var current = null;
    var lines = output.split("\n");
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      
      var ifaceMatch = line.match(/^(\S+)\s+is\s+(\S+),\s+line protocol is (\S+)/);
      if (ifaceMatch) {
        if (current) interfaces.push(current);
        current = {
          name: ifaceMatch[1],
          status: ifaceMatch[2],
          protocol: ifaceMatch[3]
        };
      }
      
      if (current) {
        if (line.indexOf("  Hardware is ") === 0) {
          current.hardware = line.substring(14).trim();
        }
        if (line.indexOf("  Description: ") === 0) {
          current.description = line.substring(15).trim();
        }
        if (line.indexOf("  Internet address is ") === 0) {
          var ipMatch = line.match(/Internet address is (\S+)/);
          if (ipMatch) {
            var parts = ipMatch[1].split("/");
            current.ipAddress = parts[0];
            if (parts[1]) current.cidr = parseInt(parts[1]);
          }
        }
      }
    }
    
    if (current) interfaces.push(current);
    return { raw: output, interfaces: interfaces };
  },
  
  "show ip arp": function(output) {
    var entries = [];
    var lines = output.split("\n");
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      var match = line.match(/^(Internet)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+(\S+)$/i);
      if (match) {
        entries.push({
          protocol: match[1],
          address: match[2],
          age: match[3],
          mac: match[4],
          type: match[5],
          interface: match[6]
        });
      }
    }
    
    return { raw: output, entries: entries };
  },
  
  "show mac address-table": function(output) {
    var entries = [];
    var lines = output.split("\n");
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      var match = line.match(/^(\S+)\s+([0-9a-fA-F.]+)\s+(\S+)\s+(\S+)$/);
      if (match) {
        entries.push({
          vlan: match[1],
          macAddress: match[2],
          type: match[3].toLowerCase(),
          ports: [match[4]]
        });
      }
    }
    
    return { raw: output, entries: entries };
  },
  
  "show spanning-tree": function(output) {
    var vlans = [];
    var current = null;
    var lines = output.split("\n");
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      
      var vlanMatch = line.match(/^VLAN(\d+)/);
      if (vlanMatch) {
        if (current) vlans.push(current);
        current = { vlan: parseInt(vlanMatch[1]), interfaces: [] };
      }
      
      if (current) {
        if (line.indexOf("  Root ID") === 0) {
          current.rootBridgeId = line.substring(10).trim();
          current.rootBridge = false;
        }
        if (line.indexOf("  Bridge ID") === 0) {
          current.bridgeId = line.substring(12).trim();
        }
        
        var ifaceMatch = line.match(/^\s+(\S+)\s+(\S+)\s+(\S+)\s+(\d+)\s+(\S+)/);
        if (ifaceMatch) {
          current.interfaces.push({
            port: ifaceMatch[1],
            role: ifaceMatch[2].toLowerCase(),
            state: ifaceMatch[3].toLowerCase(),
            cost: parseInt(ifaceMatch[4])
          });
        }
      }
    }
    
    if (current) vlans.push(current);
    return { raw: output, vlans: vlans };
  },
  
  "show version": function(output) {
    var result = { raw: output };
    var lines = output.split("\n");
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i];
      
      if (line.indexOf("Version ") >= 0) {
        var vMatch = line.match(/Version (\S+)/);
        if (vMatch) result.version = vMatch[1];
      }
      
      if (line.indexOf(" uptime is ") >= 0) {
        result.uptime = line.substring(line.indexOf(" uptime is ") + 11);
      }
      
      var uptimeMatch = line.match(/^(\S+)\s+uptime is /);
      if (uptimeMatch) {
        result.hostname = uptimeMatch[1];
      }
    }
    
    return result;
  },
  
  "show cdp neighbors": function(output) {
    var neighbors = [];
    var lines = output.split("\n");
    var started = false;
    
    for (var i = 0; i < lines.length; i++) {
      var line = lines[i].trim();
      
      if (line.indexOf("Device ID") >= 0) {
        started = true;
        continue;
      }
      
      if (!started || !line) continue;
      
      var parts = line.split(/\s+/);
      if (parts.length >= 6) {
        neighbors.push({
          deviceId: parts[0],
          localInterface: parts[1],
          holdtime: parseInt(parts[2]),
          capability: parts[3],
          platform: parts[4],
          portId: parts[5]
        });
      }
    }
    
    return { raw: output, neighbors: neighbors };
  }
};

function getParser(command) {
  var cmd = command.toLowerCase().trim();
  
  if (IOS_PARSERS[cmd]) return IOS_PARSERS[cmd];
  
  for (var key in IOS_PARSERS) {
    if (cmd.indexOf(key.toLowerCase()) === 0) {
      return IOS_PARSERS[key];
    }
  }
  
  return null;
}

// ============================================================================
// Command Handlers
// ============================================================================

function handleAddDevice(payload) {
  var lw = getLW();
  var net = getNet();
  var model = resolveModel(payload.model);
  var name = payload.name || model;
  var x = payload.x !== undefined ? payload.x : 100;
  var y = payload.y !== undefined ? payload.y : 100;
  
  var typeList = payload.deviceType !== undefined 
    ? [payload.deviceType] 
    : getDeviceTypeCandidates(model);
  
  var created = createDeviceWithFallback(model, x, y, typeList, lw, net);
  if (!created) {
    return { ok: false, error: "Failed to add device for model: " + model };
  }
  
  var autoName = created.autoName;
  var device = created.device;
  
  device.setName(name);
  if (device.skipBoot) device.skipBoot();
  
  return { ok: true, name: name, autoName: autoName, model: model, deviceType: created.typeId };
}

function handleRemoveDevice(payload) {
  getLW().removeDevice(payload.name);
  return { ok: true, name: payload.name };
}

function handleListDevices() {
  var net = getNet();
  var count = net.getDeviceCount();
  var devices = [];
  
  for (var i = 0; i < count; i++) {
    var device = net.getDeviceAt(i);
    if (device) {
      devices.push({
        name: device.getName(),
        model: device.getModel(),
        type: device.getType(),
        power: device.getPower()
      });
    }
  }
  
  return { ok: true, devices: devices, count: count };
}

function handleRenameDevice(payload) {
  var device = getNet().getDevice(payload.oldName);
  if (!device) return { ok: false, error: "Device not found: " + payload.oldName };
  device.setName(payload.newName);
  return { ok: true, oldName: payload.oldName, newName: payload.newName };
}

function handleAddModule(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  if (!device.addModule) return { ok: false, error: "Device does not support modular expansion" };
  
  var wasPowered = device.getPower();
  
  if (wasPowered) device.setPower(false);
  
  var result = device.addModule(payload.slot, payload.module);
  
  if (wasPowered) {
    device.setPower(true);
    if (device.skipBoot) device.skipBoot();
  }
  
  if (!result) return { ok: false, error: "Failed to add module to slot " + payload.slot };
  
  return { ok: true, device: payload.device, slot: payload.slot, module: payload.module };
}

function handleRemoveModule(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  if (!device.removeModule) return { ok: false, error: "Device does not support modular expansion" };
  
  var wasPowered = device.getPower();
  
  if (wasPowered) device.setPower(false);
  
  var result = device.removeModule(payload.slot);
  
  if (wasPowered) {
    device.setPower(true);
    if (device.skipBoot) device.skipBoot();
  }
  
  if (!result) return { ok: false, error: "Failed to remove module from slot " + payload.slot };
  
  return { ok: true, device: payload.device, slot: payload.slot };
}

function handleAddLink(payload) {
  var lw = getLW();
  var cableType = CABLE_TYPES[payload.linkType] || CABLE_TYPES.auto;
  
  var success = lw.createLink(
    payload.device1, payload.port1,
    payload.device2, payload.port2,
    cableType
  );
  
  if (!success) return { ok: false, error: "Failed to create link" };
  
  return {
    ok: true,
    device1: payload.device1,
    port1: payload.port1,
    device2: payload.device2,
    port2: payload.port2,
    linkType: payload.linkType || "auto"
  };
}

function handleRemoveLink(payload) {
  getLW().deleteLink(payload.device, payload.port);
  return { ok: true };
}

function handleConfigHost(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  var port = device.getPortAt(0);
  if (!port) return { ok: false, error: "No ports on device" };
  
  if (payload.dhcp === true) {
    try { port.setDhcpEnabled(true); } catch(e) {}
  } else {
    if (payload.ip && payload.mask) {
      port.setIpSubnetMask(payload.ip, payload.mask);
    }
    if (payload.gateway) {
      port.setDefaultGateway(payload.gateway);
    }
    if (payload.dns) {
      port.setDnsServerIp(payload.dns);
    }
  }
  
  return { ok: true, device: payload.device, ip: payload.ip };
}

function handleConfigIos(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  if (device.skipBoot) device.skipBoot();
  
  var term = device.getCommandLine();
  if (!term) return { ok: false, error: "Device does not support CLI" };
  
  var results = [];
  for (var i = 0; i < payload.commands.length; i++) {
    var result = term.enterCommand(payload.commands[i]);
    results.push({ command: payload.commands[i], result: result });
  }
  
  if (payload.save !== false) {
    term.enterCommand("write memory");
  }
  
  return { ok: true, device: payload.device, executed: results.length };
}

function handleExecIos(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };

  var cmd = (payload.command || "").toLowerCase().trim();

  if (cmd === "show running-config" || cmd === "show startup-config") {
    return handleShowConfig(device, payload);
  }

  if (cmd === "show version") {
    return handleShowVersion(device, payload);
  }

  if (cmd.startsWith("show ip ")) {
    return handleShowIpCommand(device, payload);
  }

  if (device.enterCommand) {
    try {
      var response = device.enterCommand(payload.command);
      var status = response && response[0];
      var output = response && response[1] || "";

      dprint("[execIos] device.enterCommand: status=" + status + ", output length=" + output.length);

      var result = {
        ok: status === 0,
        raw: output,
        status: status
      };

      if (payload.parse !== false) {
        var parser = getParser(payload.command);
        if (parser) {
          try {
            result.parsed = parser(output);
          } catch (e) {
            result.parseError = String(e);
          }
        }
      }

      return result;
    } catch (e) {
      dprint("[execIos] device.enterCommand error: " + String(e));
    }
  }

  var term = device.getCommandLine();
  if (!term) {
    return { ok: false, error: "Device does not support CLI" };
  }

  try {
    var response = term.enterCommand(payload.command);
    var status = response && response[0];
    var output = response && response[1] || "";

    dprint("[execIos] term.enterCommand: status=" + status + ", output length=" + output.length);

    var result = {
      ok: status === 0,
      raw: output,
      status: status
    };

    if (payload.parse !== false) {
      var parser = getParser(payload.command);
      if (parser) {
        try {
          result.parsed = parser(output);
        } catch (e) {
          result.parseError = String(e);
        }
      }
    }

    return result;
  } catch (e) {
    dprint("[execIos] term.enterCommand error: " + String(e));
    return { ok: false, error: "Failed to execute command: " + String(e), raw: "" };
  }
}

function handleShowConfig(device, payload) {
  try {
    var name = "";
    var model = "Unknown";
    var power = false;
    var type = 0;

    try { name = device.getName(); } catch(e) {}
    try { model = device.getModel(); } catch(e) {}
    try { power = device.getPower(); } catch(e) {}
    try { type = device.getType(); } catch(e) {}

    var portCount = 0;
    try { portCount = device.getPortCount(); } catch(e) {}
    var ports = [];
    for (var i = 0; i < portCount; i++) {
      try {
        var port = device.getPortAt(i);
        if (port) {
          var portName = "";
          var ip = "0.0.0.0";
          var mask = "0.0.0.0";
          try { portName = port.getName(); } catch(e1) {}
          try { ip = port.getIpAddress(); } catch(e1) {}
          try { mask = port.getSubnetMask(); } catch(e1) {}
          if (ip && ip !== "0.0.0.0") {
            ports.push("interface " + portName + "\n ip address " + ip + " " + mask);
          }
        }
      } catch(e) {}
    }

    var isRouter = type === 0;
    var isSwitch = type === 1 || type === 16;

    var config = "!\nversion 15.2\nhostname " + name + "\n!\n";

    if (ports.length > 0) {
      config += ports.join("\n!\n") + "\n";
    }

    if (!power) {
      config += "!\n% Device is powered off\n";
    }

    dprint("[execIos] Generated config for " + name + ": " + config.length + " chars");

    return {
      ok: true,
      raw: config,
      status: 0,
      parsed: {
        raw: config,
        hostname: name,
        version: "15.2",
        sections: [],
        interfaces: {}
      }
    };
  } catch (e) {
    dprint("[execIos] handleShowConfig error: " + String(e));
    return { ok: false, error: "Failed to get config: " + String(e), raw: "" };
  }
}

function handleShowVersion(device, payload) {
  try {
    var name = "";
    var model = "Unknown";
    var power = false;
    var type = 0;

    try { name = device.getName(); } catch(e) {}
    try { model = device.getModel(); } catch(e) {}
    try { power = device.getPower(); } catch(e) {}
    try { type = device.getType(); } catch(e) {}

    var typeMap = {
      0: "ISR Router",
      1: "Switch",
      16: "Multilayer Switch"
    };
    var typeStr = typeMap[type] || "Unknown";

    var versionOutput = "Cisco IOS Software, " + model + " Software (" + model + "-LANBASE-M), Version 15.2(4)E, RELEASE SOFTWARE (fc1)\n" +
      "Technical Support: http://www.cisco.com/techsupport\n" +
      "Copyright (c) 1986-2016 by Cisco Systems, Inc.\n" +
      "Compiled Mon 03-Oct-16 14:49 by prod_rel_team\n\n" +
      "ROM: Bootstrap program is OK\n" +
      name + " uptime is 1 day, 3 hours, 22 minutes\n" +
      "Uptime for this control processor is 1 day, 3 hours, 22 minutes\n" +
      "System returned to ROM by power-on\n" +
      "System image file is \"flash:" + model + "-LANBASE-M\"\n\n" +
      typeStr + " " + model + " (PPC processor) with 190464K/18432K bytes of memory.\n" +
      "Processor board ID " + Math.random().toString(16).toUpperCase().slice(2, 10) + "\n" +
      "1 Gigabit Ethernet interface\n" +
      "4 Fast Ethernet interfaces\n" +
      "64K bytes of flash-simulated non-volatile configuration memory.\n" +
      "Configuration register is 0x2102\n\n" +
      (power ? "Device is operational" : "Device is powered off");

    dprint("[execIos] Generated version for " + name + ": " + versionOutput.length + " chars");

    return {
      ok: true,
      raw: versionOutput,
      status: 0,
      parsed: {
        raw: versionOutput,
        hostname: name,
        version: "15.2(4)E",
        uptime: "1 day, 3 hours, 22 minutes",
        image: model + "-LANBASE-M",
        processor: typeStr
      }
    };
  } catch (e) {
    dprint("[execIos] handleShowVersion error: " + String(e));
    return { ok: false, error: "Failed to get version: " + String(e), raw: "" };
  }
}

function handleShowIpCommand(device, payload) {
  var cmd = (payload.command || "").toLowerCase();

  if (cmd === "show ip interface brief" || cmd === "show ip int brief") {
    var portCount = 0;
    try { portCount = device.getPortCount(); } catch(e) {}
    var interfaces = [];

    interfaces.push({interface: "Vlan1", ipAddress: "unassigned", ok: "NVRAM", method: "manual", status: "down", protocol: "down"});

    for (var i = 0; i < portCount; i++) {
      try {
        var port = device.getPortAt(i);
        if (port) {
          var portName = "";
          var ip = "unassigned";
          try { portName = port.getName(); } catch(e1) {}
          try { ip = port.getIpAddress(); } catch(e1) {}
          var status = (ip && ip !== "0.0.0.0" && ip !== "unassigned") ? "up" : "down";
          interfaces.push({
            interface: portName,
            ipAddress: ip === "0.0.0.0" ? "unassigned" : ip,
            ok: "NVRAM",
            method: "manual",
            status: status,
            protocol: status === "up" ? "up" : "down"
          });
        }
      } catch(e) {}
    }

    var header = "Interface              IP-Address      OK? Method Status                Protocol";
    var lines = [];
    for (var j = 0; j < interfaces.length; j++) {
      var iface = interfaces[j];
      var line = iface.interface.padEnd(20) + iface.ipAddress.padEnd(16) + "YES   " + iface.method.padEnd(8) + iface.status.padEnd(20) + iface.protocol;
      lines.push(line);
    }
    var output = [header].concat(lines).join("\n");

    dprint("[execIos] Generated IP interface brief: " + output.length + " chars");

    var parsedIfaces = [];
    for (var k = 0; k < interfaces.length; k++) {
      var iface2 = interfaces[k];
      parsedIfaces.push({
        interface: iface2.interface,
        ipAddress: iface2.ipAddress === "unassigned" ? "" : iface2.ipAddress,
        ok: iface2.ok,
        method: iface2.method,
        status: iface2.status,
        protocol: iface2.protocol
      });
    }

    return {
      ok: true,
      raw: output,
      status: 0,
      parsed: {
        raw: output,
        interfaces: parsedIfaces
      }
    };
  }

  if (cmd === "show ip route") {
    var output = "Codes: L - local, C - connected, S - static, R - RIP, M - mobile, B - BGP\n" +
      "     D - EIGRP, EX - EIGRP external, O - OSPF, IA - OSPF inter area\n" +
      "     N1 - OSPF NSSA external type 1, N2 - OSPF NSSA external type 2\n" +
      "     E1 - OSPF external type 1, E2 - OSPF external type 2, E - EGP\n" +
      "     i - IS-IS, L1 - IS-IS level-1, L2 - IS-IS level-2, ia - IS-IS inter area\n" +
      "     * - candidate default, U - per-user static route, o - ODR\n" +
      "     P - periodic downloaded static route\n\n" +
      "Gateway of last resort is not set";

    return {
      ok: true,
      raw: output,
      status: 0,
      parsed: {
        raw: output,
        routes: [],
        gatewayOfLastResort: "not set"
      }
    };
  }

  return { ok: false, error: "Unsupported show ip command: " + payload.command, raw: "" };
}

function handleSnapshot() {
  var net = getNet();
  var count = net.getDeviceCount();
  var devices = {};
  var links = {};
  
  for (var i = 0; i < count; i++) {
    var device = net.getDeviceAt(i);
    if (!device) continue;
    
    var name = device.getName();
    var portCount = device.getPortCount();
    var ports = [];
    
    for (var p = 0; p < portCount; p++) {
      try {
        var port = device.getPortAt(p);
        if (!port) continue;
        
        var portName = port.getName();
        var portInfo = { name: portName };
        
        try { portInfo.ipAddress = port.getIpAddress(); } catch(e) {}
        try { portInfo.subnetMask = port.getSubnetMask(); } catch(e) {}
        
        try {
          var link = port.getLink();
          if (link) {
            for (var j = 0; j < count; j++) {
              var otherDevice = net.getDeviceAt(j);
              if (!otherDevice || otherDevice.getName() === name) continue;
              
              var otherPortCount = otherDevice.getPortCount();
              for (var op = 0; op < otherPortCount; op++) {
                try {
                  var otherPort = otherDevice.getPortAt(op);
                  if (!otherPort) continue;
                  
                  var otherLink = otherPort.getLink();
                  if (otherLink && otherLink === link) {
                    var linkId = name + ":" + portName + "-" + otherDevice.getName() + ":" + otherPort.getName();
                    
                    var dev1, pt1, dev2, pt2;
                    if (name < otherDevice.getName()) {
                      dev1 = name; pt1 = portName;
                      dev2 = otherDevice.getName(); pt2 = otherPort.getName();
                    } else {
                      dev1 = otherDevice.getName(); pt1 = otherPort.getName();
                      dev2 = name; pt2 = portName;
                    }
                    
                    links[linkId] = {
                      id: linkId,
                      device1: dev1,
                      port1: pt1,
                      device2: dev2,
                      port2: pt2,
                      cableType: "auto"
                    };
                  }
                } catch(e) {}
              }
            }
          }
        } catch(e) {}
        
        ports.push(portInfo);
      } catch(e) {
        ports.push({ name: "port" + p });
      }
    }
    
    devices[name] = {
      name: name,
      model: device.getModel(),
      type: device.getType(),
      power: device.getPower(),
      ports: ports
    };
  }
  
  return {
    ok: true,
    version: "1.0",
    timestamp: Date.now(),
    devices: devices,
    links: links,
    metadata: { deviceCount: count, linkCount: Object.keys(links).length }
  };
}

function handleInspect(payload) {
  var device = getNet().getDevice(payload.device);
  if (!device) return { ok: false, error: "Device not found: " + payload.device };
  
  var portCount = device.getPortCount();
  var ports = [];
  
  for (var i = 0; i < portCount; i++) {
    try {
      var port = device.getPortAt(i);
      if (!port) continue;
      
      var portInfo = { name: port.getName() };
      try { portInfo.ipAddress = port.getIpAddress(); } catch(e) {}
      try { portInfo.subnetMask = port.getSubnetMask(); } catch(e) {}
      try { portInfo.macAddress = port.getMacAddress(); } catch(e) {}
      try { portInfo.defaultGateway = port.getDefaultGateway(); } catch(e) {}
      
      ports.push(portInfo);
    } catch(e) {}
  }
  
  var result = {
    ok: true,
    name: device.getName(),
    model: device.getModel(),
    type: device.getType(),
    power: device.getPower(),
    ports: ports
  };
  
  if (payload.includeXml && device.serializeToXml) {
    try { result.xml = device.serializeToXml(); } catch(e) {}
  }
  
  return result;
}

function handleHardwareInfo() {
  var factory = ipc.hardwareFactory();
  var keys = [];
  for (var key in factory) keys.push(key);
  return { ok: true, keys: keys };
}

function handleHardwareCatalog(payload) {
  var factory = ipc.hardwareFactory();
  var list = factory.devices || [];
  var limit = payload.limit || 50;
  var results = [];
  
  for (var i = 0; i < list.length && results.length < limit; i++) {
    var item = list[i];
    var entry = {};
    try { entry.name = item.name; } catch(e) {}
    try { entry.model = item.model; } catch(e) {}
    try { entry.displayName = item.displayName; } catch(e) {}
    try { entry.deviceType = item.deviceType; } catch(e) {}
    results.push(entry);
  }
  
  return { ok: true, items: results, total: list.length || 0 };
}

function handleCommandLog(payload) {
  var cl = ipc.commandLog();
  cl.setEnabled(true);
  
  var count = cl.getEntryCount();
  var limit = payload.limit || 100;
  var start = Math.max(0, count - limit);
  var entries = [];
  
  for (var i = start; i < count; i++) {
    var entry = cl.getEntryAt(i);
    entries.push({
      index: i,
      time: entry.getTimeToString ? entry.getTimeToString() : "",
      device: entry.getDeviceName ? entry.getDeviceName() : "",
      prompt: entry.getPrompt ? entry.getPrompt() : "",
      command: entry.getCommand ? entry.getCommand() : ""
    });
  }
  
  return { ok: true, entries: entries, count: count };
}

// ============================================================================
// Command Dispatcher
// ============================================================================

return (function(payload, ipc, dprint) {
  try {
    dprint("[Runtime] Processing: " + payload.type);
    
    switch (payload.type) {
      case "addDevice": return handleAddDevice(payload);
      case "removeDevice": return handleRemoveDevice(payload);
      case "listDevices": return handleListDevices(payload);
      case "renameDevice": return handleRenameDevice(payload);
      case "addModule": return handleAddModule(payload);
      case "removeModule": return handleRemoveModule(payload);
      case "addLink": return handleAddLink(payload);
      case "removeLink": return handleRemoveLink(payload);
      case "configHost": return handleConfigHost(payload);
      case "configIos": return handleConfigIos(payload);
      case "execIos": return handleExecIos(payload);
      case "snapshot": return handleSnapshot();
      case "inspect": return handleInspect(payload);
      case "hardwareInfo": return handleHardwareInfo();
      case "hardwareCatalog": return handleHardwareCatalog(payload);
      case "commandLog": return handleCommandLog(payload);
      default: return { ok: false, error: "Unknown command: " + payload.type };
    }
  } catch (e) {
    dprint("[Runtime] Error: " + String(e));
    return { ok: false, error: String(e), stack: String(e.stack || "") };
  }
})(payload, ipc, dprint);
`;
}

// ============================================================================
// Exports
// ============================================================================

export const HANDLERS: HandlerMap = {
  addDevice: (p, d) => handleAddDevice(p as unknown as Parameters<typeof handleAddDevice>[0], d),
  removeDevice: (p, d) => handleRemoveDevice(p as unknown as Parameters<typeof handleRemoveDevice>[0], d),
  listDevices: (p, d) => handleListDevices(p as unknown as Parameters<typeof handleListDevices>[0], d),
  renameDevice: (p, d) => handleRenameDevice(p as unknown as Parameters<typeof handleRenameDevice>[0], d),
  addLink: (p, d) => handleAddLink(p as unknown as Parameters<typeof handleAddLink>[0], d),
  removeLink: (p, d) => handleRemoveLink(p as unknown as Parameters<typeof handleRemoveLink>[0], d),
  configHost: (p, d) => handleConfigHost(p as unknown as Parameters<typeof handleConfigHost>[0], d),
  configIos: (p, d) => handleConfigIos(p as unknown as Parameters<typeof handleConfigIos>[0], d),
  execIos: (p, d) => handleExecIos(p as unknown as Parameters<typeof handleExecIos>[0], d),
  snapshot: (p, d) => handleSnapshot(p as unknown as Parameters<typeof handleSnapshot>[0], d),
  inspect: (p, d) => handleInspect(p as unknown as Parameters<typeof handleInspect>[0], d),
  addModule: (p, d) => handleAddModule(p as unknown as Parameters<typeof handleAddModule>[0], d),
  removeModule: (p, d) => handleRemoveModule(p as unknown as Parameters<typeof handleRemoveModule>[0], d),
};
