// ============================================================================
// AUTO-GENERATED MODEL MAP - DO NOT EDIT MANUALLY
// Generated by: generate-model-map.ts
// Source: verified-models.ts (ÚNICA fuente de verdad)
// 
// Los modelos se validan en compile-time con TypeScript.
// Si un modelo no está en VERIFIED_MODELS, falla en el compilador.
// ============================================================================

var PT_MODEL_MAP = {
  // Routers
  "1841": "1841",
  "1941": "1941",
  "2811": "2811",
  "2901": "2901",
  "2911": "2911",
  "2620xm": "2620XM",
  "2621xm": "2621XM",
  "819": "819",
  "829": "829",
  "4331": "4331",
  
  // Switches - 2950 series
  "2950": "2950-24",
  "2950-24": "2950-24",
  "2950t": "2950T-24",
  "2950t-24": "2950T-24",
  
  // Switches - 2960 series
  "2960": "2960-24TT",
  "2960-24": "2960-24TT",
  "2960-24tt": "2960-24TT",
  "2960-24tc": "2960-24TT",  // TC no existe, mapear a TT
  
  // Switches - 3560/3650 series (L3)
  "3560": "3560-24PS",
  "3560-24ps": "3560-24PS",
  "3650": "3650-24PS",
  "3650-24ps": "3650-24PS",
  
  // Switches - Industrial
  "ie-2000": "IE-2000",
  "ie-3400": "IE-3400",
  "ie-9320": "IE-9320",
  "ie2000": "IE-2000",
  "ie3400": "IE-3400",
  "ie9320": "IE-9320",
  
  // Other network devices
  "bridge-pt": "Bridge-PT",
  
  // Wireless
  "accesspoint-pt": "AccessPoint-PT",
  "accesspoint-pt-a": "AccessPoint-PT-A",
  "accesspoint-pt-ac": "AccessPoint-PT-AC",
  "accesspoint-pt-n": "AccessPoint-PT-N",
  "linksys-wrt300n": "Linksys-WRT300N",
  "wrt300n": "Linksys-WRT300N",
  "wireless": "AccessPoint-PT",
  "accesspoint": "AccessPoint-PT",
  "ap": "AccessPoint-PT",
  
  // End devices
  "pc-pt": "PC-PT",
  "laptop-pt": "Laptop-PT",
  "server-pt": "Server-PT",
  "printer-pt": "Printer-PT",
  "cloud-pt": "Cloud-PT",
  "pc": "PC-PT",
  "laptop": "Laptop-PT",
  "server": "Server-PT",
  "printer": "Printer-PT",
  "cloud": "Cloud-PT",
  
  // Generic aliases
  "switch": "2960-24TT",
  "router": "2911"
};

var PT_DEVICE_TYPE_MAP = {
  // Routers (type 0)
  "1841": 0,
  "1941": 0,
  "2811": 0,
  "2901": 0,
  "2911": 0,
  "2620xm": 0,
  "2621xm": 0,
  "819": 0,
  "829": 0,
  "4331": 0,
  
  // Switches L2 (type 1)
  "2950": 1,
  "2950-24": 1,
  "2950t": 1,
  "2950t-24": 1,
  "2960": 1,
  "2960-24": 1,
  "2960-24tt": 1,
  "2960-24tc": 1,
  
  // Switches L3 (type 16)
  "3560": 16,
  "3560-24ps": 16,
  "3650": 16,
  "3650-24ps": 16,
  
  // Industrial switches
  "ie-2000": 1,
  "ie-3400": 1,
  "ie-9320": 16,
  "ie2000": 1,
  "ie3400": 1,
  "ie9320": 16,
  "bridge-pt": 1,
  
  // Wireless (type 7)
  "accesspoint-pt": 7,
  "accesspoint-pt-a": 7,
  "accesspoint-pt-ac": 7,
  "accesspoint-pt-n": 7,
  "linksys-wrt300n": 11,
  "wrt300n": 11,
  "wireless": 7,
  "accesspoint": 7,
  "ap": 7,
  
  // End devices
  "pc-pt": 8,
  "laptop-pt": 18,
  "server-pt": 9,
  "printer-pt": 10,
  "cloud-pt": 2,
  "pc": 8,
  "laptop": 18,
  "server": 9,
  "printer": 10,
  "cloud": 2,
  
  // Generic
  "switch": 1,
  "router": 0
};