// ============================================================================
// AUTO-GENERATED MODULE MAP - DO NOT EDIT MANUALLY
// Generated by: generate-module-map.ts
// Source: ptbuilder-spec.ts + pt-runtime module handlers
//
// Módulos HWIC/WIC para routers 2811, 2911, 2620XM
// Slot types: 0=eLineCard, 1=eNetworkModule, 2=eInterfaceCard
// ============================================================================

var PT_MODULE_CATALOG = {
  "NM-2W":    { code: "NM-2W",    slotType: "eNetworkModule",   name: "NM-2W HWIC-2T" },
  "HWIC-2T":  { code: "HWIC-2T",  slotType: "eInterfaceCard",   name: "HWIC-2T" },
  "HWIC-4ESW":{ code: "HWIC-4ESW",slotType: "eInterfaceCard",   name: "HWIC-4ESW" },
  "WIC-2T":   { code: "WIC-2T",   slotType: "eInterfaceCard",   name: "WIC-2T" },
  "WIC-1T":   { code: "WIC-1T",   slotType: "eInterfaceCard",   name: "WIC-1T" },
};

var PT_DEVICE_MODULE_SLOTS = {
  "2811": [
    { type: "eNetworkModule",  count: 2, supportedModules: ["NM-2W","NM-1E","NM-1FE-TX","NM-4A/S"] },
    { type: "eInterfaceCard",   count: 2, supportedModules: ["HWIC-2T","HWIC-4ESW","WIC-2T","WIC-1T","HWIC-1GE-SFP"] },
    { type: "eInterfaceCard",   count: 0, supportedModules: [] },
  ],
  "2911": [
    { type: "eNetworkModule",   count: 2, supportedModules: ["NM-2W","NM-1E","NM-1FE-TX","NM-4A/S"] },
    { type: "eInterfaceCard",   count: 2, supportedModules: ["HWIC-2T","HWIC-4ESW","WIC-2T","WIC-1T","HWIC-1GE-SFP"] },
    { type: "eInterfaceCard",   count: 0, supportedModules: [] },
  ],
  "2620XM": [
    { type: "eNetworkModule",   count: 1, supportedModules: ["NM-2W","NM-1E","NM-1FE-TX"] },
    { type: "eInterfaceCard",   count: 2, supportedModules: ["HWIC-2T","HWIC-4ESW","WIC-2T","WIC-1T"] },
    { type: "eInterfaceCard",   count: 0, supportedModules: [] },
  ],
};
