// ============================================================================
// AUTO-GENERATED PORT MAP - DO NOT EDIT MANUALLY
// Generated by: generate-port-map.ts
// Source: @cisco-ai/catalog (routers.ts, switches.ts)
//
// Mapeo de modelo -> puertos válidos según catálogo oficial
// ============================================================================

var PT_PORT_MAP = {
  "819": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "829": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45"
  },
  "1841": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "1941": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45"
  },
  "2811": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "2901": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45"
  },
  "2911": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45"
  },
  "ISR4321": {
    "gigabitethernet0/0": "sfp",
    "gigabitethernet0/1": "rj45"
  },
  "ISR4331": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45"
  },
  "2620XM": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "2621XM": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "CGR1240": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45"
  },
  "IR-8340": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45"
  },
  "Router-PT": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "C8200": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45"
  },
  "2960-24TT": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp"
  },
  "2960-24TC": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp"
  },
  "2950-24": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45"
  },
  "2950T-24": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45"
  },
  "3560-24PS": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp"
  },
  "3650-24PS": {
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45",
    "gigabitethernet0/4": "rj45",
    "gigabitethernet0/5": "rj45",
    "gigabitethernet0/6": "rj45",
    "gigabitethernet0/7": "rj45",
    "gigabitethernet0/8": "rj45",
    "gigabitethernet0/9": "rj45",
    "gigabitethernet0/10": "rj45",
    "gigabitethernet0/11": "rj45",
    "gigabitethernet0/12": "rj45",
    "gigabitethernet0/13": "rj45",
    "gigabitethernet0/14": "rj45",
    "gigabitethernet0/15": "rj45",
    "gigabitethernet0/16": "rj45",
    "gigabitethernet0/17": "rj45",
    "gigabitethernet0/18": "rj45",
    "gigabitethernet0/19": "rj45",
    "gigabitethernet0/20": "rj45",
    "gigabitethernet0/21": "rj45",
    "gigabitethernet0/22": "rj45",
    "gigabitethernet0/23": "rj45",
    "gigabitethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "gigabitethernet0/27": "sfp",
    "gigabitethernet0/28": "sfp"
  },
  "IE2000": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "gigabitethernet0/9": "sfp",
    "gigabitethernet0/10": "sfp"
  },
  "IE-3400": {
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45",
    "gigabitethernet0/4": "rj45",
    "gigabitethernet0/5": "rj45",
    "gigabitethernet0/6": "rj45",
    "gigabitethernet0/7": "rj45",
    "gigabitethernet0/8": "rj45",
    "gigabitethernet0/9": "rj45",
    "gigabitethernet0/10": "rj45",
    "gigabitethernet0/11": "rj45",
    "gigabitethernet0/12": "rj45",
    "gigabitethernet0/13": "rj45",
    "gigabitethernet0/14": "rj45",
    "gigabitethernet0/15": "rj45",
    "gigabitethernet0/16": "rj45",
    "gigabitethernet0/17": "rj45",
    "gigabitethernet0/18": "rj45",
    "gigabitethernet0/19": "rj45",
    "gigabitethernet0/20": "rj45",
    "gigabitethernet0/21": "rj45",
    "gigabitethernet0/22": "rj45",
    "gigabitethernet0/23": "rj45",
    "gigabitethernet0/24": "rj45"
  },
  "IE-9320": {
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45",
    "gigabitethernet0/4": "rj45",
    "gigabitethernet0/5": "rj45",
    "gigabitethernet0/6": "rj45",
    "gigabitethernet0/7": "rj45",
    "gigabitethernet0/8": "rj45",
    "gigabitethernet0/9": "rj45",
    "gigabitethernet0/10": "rj45",
    "gigabitethernet0/11": "rj45",
    "gigabitethernet0/12": "rj45",
    "gigabitethernet0/13": "rj45",
    "gigabitethernet0/14": "rj45",
    "gigabitethernet0/15": "rj45",
    "gigabitethernet0/16": "rj45",
    "gigabitethernet0/17": "rj45",
    "gigabitethernet0/18": "rj45",
    "gigabitethernet0/19": "rj45",
    "gigabitethernet0/20": "rj45",
    "gigabitethernet0/21": "rj45",
    "gigabitethernet0/22": "rj45",
    "gigabitethernet0/23": "rj45",
    "gigabitethernet0/24": "rj45",
    "gigabitethernet0/25": "rj45",
    "gigabitethernet0/26": "rj45",
    "gigabitethernet0/27": "rj45",
    "gigabitethernet0/28": "rj45",
    "gigabitethernet0/29": "rj45",
    "gigabitethernet0/30": "rj45",
    "gigabitethernet0/31": "rj45",
    "gigabitethernet0/32": "rj45",
    "gigabitethernet0/33": "rj45",
    "gigabitethernet0/34": "rj45",
    "gigabitethernet0/35": "rj45",
    "gigabitethernet0/36": "rj45",
    "gigabitethernet0/37": "rj45",
    "gigabitethernet0/38": "rj45",
    "gigabitethernet0/39": "rj45",
    "gigabitethernet0/40": "rj45",
    "gigabitethernet0/41": "rj45",
    "gigabitethernet0/42": "rj45",
    "gigabitethernet0/43": "rj45",
    "gigabitethernet0/44": "rj45",
    "gigabitethernet0/45": "rj45",
    "gigabitethernet0/46": "rj45",
    "gigabitethernet0/47": "rj45",
    "gigabitethernet0/48": "rj45"
  },
  "Bridge-PT": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45"
  },
  "AccessPoint-PT": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AP-PT-A": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AccessPoint-PT-A": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AP-PT-N": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AccessPoint-PT-N": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AP-PT-AC": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AccessPoint-PT-AC": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "LAP-PT": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "Aironet-3702i": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "WLC-PT": {
    "gigabitethernet0/0": "rj45"
  },
  "WLC-2504": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "WLC-3504": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "WirelessRouter-PT": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "Home-Router": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "WRT300N": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "Linksys-WRT300N": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "Home-Gateway": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "Repeater-PT": {
    "wireless0/0": "rj45"
  }
};
