// ============================================================================
// AUTO-GENERATED MODEL MAP - DO NOT EDIT MANUALLY
// Generated by: generate-model-map.ts
// Source: verified-models.ts (ÚNICA fuente de verdad)
// 
// Los modelos se validan en compile-time con TypeScript.
// Si un modelo no está en VERIFIED_MODELS, falla en el compilador.
// ============================================================================

var PT_MODEL_MAP = {
  "1841": "1841",
  "1941": "1941",
  "2811": "2811",
  "2901": "2901",
  "2911": "2911",
  "2950": "2950-24",
  "2960": "2960-24TT",
  "3560": "3560-24PS",
  "3650": "3650-24PS",
  "4331": "4331",
  "2950-24": "2950-24",
  "2950t-24": "2950T-24",
  "2960-24tt": "2960-24TT",
  "3560-24ps": "3560-24PS",
  "3650-24ps": "3650-24PS",
  "accesspoint-pt": "AccessPoint-PT",
  "accesspoint-pt-a": "AccessPoint-PT-A",
  "accesspoint-pt-ac": "AccessPoint-PT-AC",
  "accesspoint-pt-n": "AccessPoint-PT-N",
  "linksys-wrt300n": "Linksys-WRT300N",
  "pc-pt": "PC-PT",
  "laptop-pt": "Laptop-PT",
  "server-pt": "Server-PT",
  "printer-pt": "Printer-PT",
  "cloud-pt": "Cloud-PT",
  "2960-24": "2960-24TT",
  "wrt300n": "Linksys-WRT300N",
  "wireless": "AccessPoint-PT",
  "accesspoint": "AccessPoint-PT",
  "pc": "PC-PT",
  "laptop": "Laptop-PT",
  "server": "Server-PT",
  "printer": "Printer-PT",
  "cloud": "Cloud-PT"
};

var PT_DEVICE_TYPE_MAP = {
  "1841": 0,
  "1941": 0,
  "2811": 0,
  "2901": 0,
  "2911": 0,
  "2950": 1,
  "2960": 1,
  "3560": 16,
  "3650": 16,
  "4331": 0,
  "2950-24": 1,
  "2950t-24": 1,
  "2960-24tt": 1,
  "3560-24ps": 16,
  "3650-24ps": 16,
  "accesspoint-pt": 7,
  "accesspoint-pt-a": 7,
  "accesspoint-pt-ac": 7,
  "accesspoint-pt-n": 7,
  "linksys-wrt300n": 11,
  "pc-pt": 8,
  "laptop-pt": 18,
  "server-pt": 9,
  "printer-pt": 10,
  "cloud-pt": 2,
  "2960-24": 1,
  "wrt300n": 11,
  "wireless": 7,
  "accesspoint": 7,
  "pc": 8,
  "laptop": 18,
  "server": 9,
  "printer": 10,
  "cloud": 2
};