// ============================================================================
// AUTO-GENERATED PORT MAP - DO NOT EDIT MANUALLY
// Generated by: generate-port-map.ts
// Source: packages/core/src/catalog/
//
// Mapeo de modelo -> puertos válidos según catálogo oficial
// ============================================================================

var PT_PORT_MAP = {
  "819": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "console0/0": "console"
  },
  "829": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "1841": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "console0/0": "console"
  },
  "1941": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "2811": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "console0/0": "console"
  },
  "2901": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "2911": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "console0/0": "console"
  },
  "2960": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "5505": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45"
  },
  "5506": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "7960": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45"
  },
  "ISR4321": {
    "gigabitethernet0/0": "sfp",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "ISR4331": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "console0/0": "console"
  },
  "router": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "2620XM": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "console0/0": "console"
  },
  "2621XM": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "console0/0": "console"
  },
  "CGR1240": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "IR-8340": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "console0/0": "console"
  },
  "Router-PT": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "console0/0": "console"
  },
  "C8200": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "console0/0": "console"
  },
  "2960-24TT": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "switch": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "2960-24tt-l": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "2960-24TC": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "2960-24tc-l": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "2950-24": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "console0/0": "console"
  },
  "2950T-24": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "console0/0": "console"
  },
  "3560-24PS": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "3560-24ps-l": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "console0/0": "console"
  },
  "3650-24PS": {
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45",
    "gigabitethernet0/4": "rj45",
    "gigabitethernet0/5": "rj45",
    "gigabitethernet0/6": "rj45",
    "gigabitethernet0/7": "rj45",
    "gigabitethernet0/8": "rj45",
    "gigabitethernet0/9": "rj45",
    "gigabitethernet0/10": "rj45",
    "gigabitethernet0/11": "rj45",
    "gigabitethernet0/12": "rj45",
    "gigabitethernet0/13": "rj45",
    "gigabitethernet0/14": "rj45",
    "gigabitethernet0/15": "rj45",
    "gigabitethernet0/16": "rj45",
    "gigabitethernet0/17": "rj45",
    "gigabitethernet0/18": "rj45",
    "gigabitethernet0/19": "rj45",
    "gigabitethernet0/20": "rj45",
    "gigabitethernet0/21": "rj45",
    "gigabitethernet0/22": "rj45",
    "gigabitethernet0/23": "rj45",
    "gigabitethernet0/24": "rj45",
    "gigabitethernet0/25": "sfp",
    "gigabitethernet0/26": "sfp",
    "gigabitethernet0/27": "sfp",
    "gigabitethernet0/28": "sfp",
    "console0/0": "console"
  },
  "IE2000": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "gigabitethernet0/9": "sfp",
    "gigabitethernet0/10": "sfp",
    "console0/0": "console"
  },
  "IE-3400": {
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45",
    "gigabitethernet0/4": "rj45",
    "gigabitethernet0/5": "rj45",
    "gigabitethernet0/6": "rj45",
    "gigabitethernet0/7": "rj45",
    "gigabitethernet0/8": "rj45",
    "gigabitethernet0/9": "rj45",
    "gigabitethernet0/10": "rj45",
    "gigabitethernet0/11": "rj45",
    "gigabitethernet0/12": "rj45",
    "gigabitethernet0/13": "rj45",
    "gigabitethernet0/14": "rj45",
    "gigabitethernet0/15": "rj45",
    "gigabitethernet0/16": "rj45",
    "gigabitethernet0/17": "rj45",
    "gigabitethernet0/18": "rj45",
    "gigabitethernet0/19": "rj45",
    "gigabitethernet0/20": "rj45",
    "gigabitethernet0/21": "rj45",
    "gigabitethernet0/22": "rj45",
    "gigabitethernet0/23": "rj45",
    "gigabitethernet0/24": "rj45",
    "console0/0": "console"
  },
  "IE-9320": {
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45",
    "gigabitethernet0/4": "rj45",
    "gigabitethernet0/5": "rj45",
    "gigabitethernet0/6": "rj45",
    "gigabitethernet0/7": "rj45",
    "gigabitethernet0/8": "rj45",
    "gigabitethernet0/9": "rj45",
    "gigabitethernet0/10": "rj45",
    "gigabitethernet0/11": "rj45",
    "gigabitethernet0/12": "rj45",
    "gigabitethernet0/13": "rj45",
    "gigabitethernet0/14": "rj45",
    "gigabitethernet0/15": "rj45",
    "gigabitethernet0/16": "rj45",
    "gigabitethernet0/17": "rj45",
    "gigabitethernet0/18": "rj45",
    "gigabitethernet0/19": "rj45",
    "gigabitethernet0/20": "rj45",
    "gigabitethernet0/21": "rj45",
    "gigabitethernet0/22": "rj45",
    "gigabitethernet0/23": "rj45",
    "gigabitethernet0/24": "rj45",
    "gigabitethernet0/25": "rj45",
    "gigabitethernet0/26": "rj45",
    "gigabitethernet0/27": "rj45",
    "gigabitethernet0/28": "rj45",
    "gigabitethernet0/29": "rj45",
    "gigabitethernet0/30": "rj45",
    "gigabitethernet0/31": "rj45",
    "gigabitethernet0/32": "rj45",
    "gigabitethernet0/33": "rj45",
    "gigabitethernet0/34": "rj45",
    "gigabitethernet0/35": "rj45",
    "gigabitethernet0/36": "rj45",
    "gigabitethernet0/37": "rj45",
    "gigabitethernet0/38": "rj45",
    "gigabitethernet0/39": "rj45",
    "gigabitethernet0/40": "rj45",
    "gigabitethernet0/41": "rj45",
    "gigabitethernet0/42": "rj45",
    "gigabitethernet0/43": "rj45",
    "gigabitethernet0/44": "rj45",
    "gigabitethernet0/45": "rj45",
    "gigabitethernet0/46": "rj45",
    "gigabitethernet0/47": "rj45",
    "gigabitethernet0/48": "rj45",
    "console0/0": "console"
  },
  "Bridge-PT": {
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45",
    "fastethernet0/8": "rj45",
    "fastethernet0/9": "rj45",
    "fastethernet0/10": "rj45",
    "fastethernet0/11": "rj45",
    "fastethernet0/12": "rj45",
    "fastethernet0/13": "rj45",
    "fastethernet0/14": "rj45",
    "fastethernet0/15": "rj45",
    "fastethernet0/16": "rj45",
    "fastethernet0/17": "rj45",
    "fastethernet0/18": "rj45",
    "fastethernet0/19": "rj45",
    "fastethernet0/20": "rj45",
    "fastethernet0/21": "rj45",
    "fastethernet0/22": "rj45",
    "fastethernet0/23": "rj45",
    "fastethernet0/24": "rj45",
    "console0/0": "console"
  },
  "PC-PT": {
    "fastethernet0/0": "rj45"
  },
  "pc": {
    "fastethernet0/0": "rj45"
  },
  "Laptop-PT": {
    "fastethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "laptop": {
    "fastethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "Server-PT": {
    "gigabitethernet0/0": "rj45"
  },
  "server": {
    "gigabitethernet0/0": "rj45"
  },
  "Meraki-Server": {
    "gigabitethernet0/0": "rj45"
  },
  "Printer-PT": {
    "fastethernet0/0": "rj45"
  },
  "printer": {
    "fastethernet0/0": "rj45"
  },
  "Home-VoIP-PT": {
    "fastethernet0/0": "rj45"
  },
  "Analog-Phone-PT": {
    "phone0/0": "rj45"
  },
  "TabletPC-PT": {
    "wireless0/0": "rj45"
  },
  "SMARTPHONE-PT": {
    "wireless0/0": "rj45"
  },
  "TV-PT": {
    "fastethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "WirelessEndDevice-PT": {
    "wireless0/0": "rj45"
  },
  "WiredDevice-PT": {
    "fastethernet0/0": "rj45"
  },
  "Sniffer": {
    "gigabitethernet0/0": "rj45"
  },
  "DataHistorianServer": {
    "gigabitethernet0/0": "rj45"
  },
  "CyberObserver": {
    "gigabitethernet0/0": "rj45"
  },
  "AccessPoint-PT": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "ap": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "accesspoint": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AccessPoint-PT-A": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AccessPoint-PT-N": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "AccessPoint-PT-AC": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "LAP-PT": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "Aironet-3702i": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "WLC-PT": {
    "gigabitethernet0/0": "rj45"
  },
  "WLC-2504": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "WLC-3504": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "WirelessRouter-PT": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "Home-Router": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "WRT300N": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "wrt300n": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "wireless0/0": "rj45"
  },
  "Home-Gateway": {
    "gigabitethernet0/0": "rj45",
    "wireless0/0": "rj45"
  },
  "Repeater-PT": {
    "wireless0/0": "rj45"
  },
  "ASA-5505": {
    "fastethernet0/0": "rj45",
    "fastethernet0/1": "rj45",
    "fastethernet0/2": "rj45",
    "fastethernet0/3": "rj45",
    "fastethernet0/4": "rj45",
    "fastethernet0/5": "rj45",
    "fastethernet0/6": "rj45",
    "fastethernet0/7": "rj45"
  },
  "ASA-5506": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "ISA-3000": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "isa-3000": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "Meraki-MX65W": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "Cloud-PT": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "cloud": {
    "gigabitethernet0/0": "rj45",
    "gigabitethernet0/1": "rj45",
    "gigabitethernet0/2": "rj45",
    "gigabitethernet0/3": "rj45"
  },
  "DSL-Modem-PT": {
    "dsl0/0": "rj45",
    "gigabitethernet0/0": "rj45"
  },
  "Cable-Modem-PT": {
    "cable0/0": "rj45",
    "gigabitethernet0/0": "rj45"
  },
  "Cell-Tower": {
    "gigabitethernet0/0": "rj45"
  },
  "Central-Office-Server": {
    "gigabitethernet0/0": "rj45"
  }
};
