// ============================================================================
// Main.js Template - PT Script Module with Event Listeners
// ============================================================================
// Bridge V2 Layout: Uses commands/, in-flight/, results/, logs/
// ============================================================================

export const MAIN_JS_TEMPLATE = `
/**
 * PT Control V2 - Main Script Module (Bridge V2)
 * 
 * Auto-generated by pt-control runtime generator.
 * This module runs INSIDE Packet Tracer and provides:
 * - FileWatcher for commands directory
 * - PT Event listeners for real-time updates
 * - Auto-snapshot for state synchronization
 * 
 * Bridge V2 Layout:
 * - commands/: Queue of pending commands
 * - in-flight/: Commands currently being processed
 * - results/<id>.json: Authoritative result for each command
 * - logs/events.current.ndjson: Append-only event journal
 */

// Configuration
var DEV_DIR = {{DEV_DIR_LITERAL}};
var RUNTIME_FILE = DEV_DIR + "/runtime.js";
var COMMAND_FILE = DEV_DIR + "/command.json";

// Directory layout
var RESULTS_DIR = DEV_DIR + "/results";
var LOGS_DIR = DEV_DIR + "/logs";
var EVENTS_FILE = LOGS_DIR + "/events.current.ndjson";
var STATE_FILE = DEV_DIR + "/state.json";
var SESSIONS_FILE = DEV_DIR + "/sessions/ios-sessions.json";
var HEARTBEAT_PATH = DEV_DIR + "/sessions/heartbeat.json";

// State
var fm = null;
var fw = null;
var runtimeFn = null;
var reloadTimer = null;
var commandTimer = null;
var snapshotInterval = null;
var heartbeatInterval = null;
var commandPollInterval = null;
var lastCommandContent = "";

// ============================================================================
// Event Helpers
// ============================================================================

function appendEvent(evt) {
  try {
    var line = JSON.stringify(evt) + "\\n";
    var prev = fm.fileExists(EVENTS_FILE) ? fm.getFileContents(EVENTS_FILE) : "";
    fm.writePlainTextToFile(EVENTS_FILE, prev + line);
  } catch (e) {
    dprint("[ERROR] Failed to append event: " + String(e));
  }
}

function writeState(state) {
  try {
    fm.writePlainTextToFile(STATE_FILE, JSON.stringify(state));
  } catch (e) {
    dprint("[ERROR] Failed to write state: " + String(e));
  }
}

function writeHeartbeat() {
  try {
    fm.writePlainTextToFile(HEARTBEAT_PATH, JSON.stringify({ ts: Date.now(), pid: "main" }));
  } catch (e) {
    dprint("[WARN] Failed to write heartbeat: " + String(e));
  }
}

function cleanStaleSessions() {
  try {
    if (!fm.fileExists(SESSIONS_FILE)) {
      return;
    }
    var content = fm.getFileContents(SESSIONS_FILE);
    var sessions = JSON.parse(content);
    var heartbeatContent = null;
    var isStale = true;

    if (fm.fileExists(HEARTBEAT_PATH)) {
      heartbeatContent = fm.getFileContents(HEARTBEAT_PATH);
      var heartbeat = JSON.parse(heartbeatContent);
      var age = Date.now() - heartbeat.ts;
      isStale = age > 15000; // Consider stale if no heartbeat for > 15 seconds
    }

    if (isStale) {
      dprint("[INFO] Stale sessions detected, resetting ios-sessions.json");
      fm.writePlainTextToFile(SESSIONS_FILE, JSON.stringify({}));
      if (heartbeatContent) {
        fm.writePlainTextToFile(HEARTBEAT_PATH, JSON.stringify({ ts: Date.now(), pid: "main" }));
      }
    }
  } catch (e) {
    dprint("[WARN] Failed to clean stale sessions: " + String(e));
  }
}

function safeValue(getter, fallback) {
  try {
    return getter();
  } catch (e) {
    return fallback;
  }
}

function readDeviceState(device) {
  try {
    var name = safeValue(function() { return device.getName(); }, "");
    if (!name) return null;

    var portCount = safeValue(function() { return device.getPortCount(); }, 0);
    var ports = [];

    for (var p = 0; p < portCount; p++) {
      try {
        var port = device.getPortAt(p);
        var portInfo = { name: port.getName() };
        try { portInfo.ipAddress = port.getIpAddress(); } catch(e1) {}
        try { portInfo.subnetMask = port.getSubnetMask(); } catch(e2) {}
        try { portInfo.macAddress = port.getMacAddress(); } catch(e3) {}
        ports.push(portInfo);
      } catch (e) {}
    }

    return {
      name: name,
      model: safeValue(function() { return device.getModel(); }, ""),
      type: safeValue(function() { return device.getType(); }, 0),
      power: safeValue(function() { return device.getPower(); }, false),
      ports: ports
    };
  } catch (e) {
    return null;
  }
}

function collectDevices() {
  var net = ipc.network();
  var count = net.getDeviceCount();
  var devices = {};
  var deviceList = [];

  for (var i = 0; i < count; i++) {
    try {
      var snapshot = readDeviceState(net.getDeviceAt(i));
      if (!snapshot) continue;
      devices[snapshot.name] = snapshot;
      deviceList.push(snapshot);
    } catch (e) {}
  }

  return {
    count: deviceList.length,
    devices: devices,
    list: deviceList
  };
}

// ============================================================================
// Runtime Management
// ============================================================================

function loadRuntime() {
  try {
    if (!fm.fileExists(RUNTIME_FILE)) {
      appendEvent({ type: "error", ts: Date.now(), message: "Runtime file not found" });
      return;
    }

    var code = fm.getFileContents(RUNTIME_FILE);
    if (!code || code.length < 100) {
      appendEvent({ type: "error", ts: Date.now(), message: "Runtime file is suspiciously small or empty" });
      dprint("[ERROR] Runtime file is suspiciously small or empty");
      return;
    }

    // Parse to validate syntax
    var candidate;
    try {
      candidate = new Function("payload", "ipc", "dprint", code);
    } catch (syntaxErr) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        message: "Runtime syntax error: " + String(syntaxErr),
        stack: String(syntaxErr.stack || "")
      });
      dprint("[ERROR] Runtime syntax error: " + String(syntaxErr));
      return;
    }

    // Smoke test: execute with a healthcheck payload
    var smokeTestPassed = false;
    var smokeTestError = null;
    try {
      var smokeResult = candidate(
        { type: "__healthcheck__" },
        ipc,
        function() {} // dprint stub
      );

      // Smoke test passes if it returns an "unknown command" error (not a crash)
      if (smokeResult && smokeResult.error && smokeResult.error.indexOf("Unknown command") !== -1) {
        smokeTestPassed = true;
      } else if (smokeResult && smokeResult.ok === false && smokeResult.error) {
        // Runtime executed but returned our healthcheck as unknown - that's fine
        smokeTestPassed = true;
      } else if (!smokeResult) {
        // Null/undefined result might be OK if runtime is still initializing
        smokeTestPassed = true;
      }
    } catch (execErr) {
      smokeTestError = execErr;
      smokeTestPassed = false;
    }

    if (!smokeTestPassed) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        message: "Runtime smoke test failed" + (smokeTestError ? ": " + String(smokeTestError) : ""),
        stack: smokeTestError ? String(smokeTestError.stack || "") : ""
      });
      dprint("[ERROR] Runtime smoke test failed: " + (smokeTestError ? String(smokeTestError) : "unknown error"));
      return;
    }

    // All checks passed - replace the runtime function
    runtimeFn = candidate;

    appendEvent({ type: "runtime-loaded", ts: Date.now(), version: "2.1", smokeTest: true });
    dprint("[OK] Runtime loaded and smoke-tested successfully");
  } catch (e) {
    appendEvent({
      type: "error",
      ts: Date.now(),
      message: "Failed to load runtime: " + String(e),
      stack: String(e.stack || "")
    });
    dprint("[ERROR] Failed to load runtime: " + String(e));
  }
}

// ============================================================================
// Command Execution (Single command.json file with FileWatcher)
// ============================================================================

function processCommandFile() {
  try {
    if (!fm.fileExists(COMMAND_FILE)) {
      return;
    }
    
    var content = fm.getFileContents(COMMAND_FILE);
    
    // Skip if empty or same as last processed
    if (!content || content.length === 0 || content === lastCommandContent) {
      return;
    }
    
    lastCommandContent = content;
    dprint("[DEBUG] New command detected");
    
    // Clear the file first to avoid re-processing
    fm.writePlainTextToFile(COMMAND_FILE, "");
    
    var cmd = JSON.parse(content);
    
    if (!cmd || !cmd.payload) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        id: cmd && cmd.id ? cmd.id : "unknown",
        message: "Invalid command format"
      });
      return;
    }

    dprint("[INFO] Executing command: " + cmd.payload.type);

    if (!runtimeFn) {
      appendEvent({
        type: "error",
        ts: Date.now(),
        id: cmd.id,
        message: "Runtime not loaded"
      });
      return;
    }

    var startedAt = Date.now();
    
    // Execute runtime with payload
    var result = runtimeFn(cmd.payload, ipc, dprint);

    // Write result to results/<id>.json
    if (cmd.id) {
      try {
        if (!fm.directoryExists(RESULTS_DIR)) {
          fm.makeDirectory(RESULTS_DIR);
        }
        var resultEnvelope = {
          protocolVersion: 2,
          id: cmd.id,
          seq: cmd.seq || 0,
          startedAt: startedAt,
          completedAt: Date.now(),
          status: result && result.ok !== false ? "completed" : "failed",
          ok: result && result.ok !== false,
          value: result
        };
        fm.writePlainTextToFile(RESULTS_DIR + "/" + cmd.id + ".json", JSON.stringify(resultEnvelope));
      } catch (e) {
        dprint("[WARN] Failed to write result file: " + String(e));
      }
    }

    appendEvent({
      type: "result",
      ts: Date.now(),
      id: cmd.id,
      ok: result && result.ok !== false,
      value: result
    });

    dprint("[OK] Command executed successfully");
    
    // Reset lastCommandContent after successful processing
    lastCommandContent = "";

  } catch (e) {
    appendEvent({
      type: "error",
      ts: Date.now(),
      id: typeof cmd !== "undefined" && cmd && cmd.id ? cmd.id : "unknown",
      message: String(e),
      stack: String(e.stack || "")
    });
    dprint("[ERROR] Failed to execute command: " + String(e));
  }
}

// ============================================================================
// PT Event Listeners
// ============================================================================

function setupEventListeners() {
  try {
    var lw = ipc.appWindow().getActiveWorkspace().getLogicalWorkspace();
    var cl = ipc.commandLog();
    
    // Topology events
    lw.registerEvent("deviceAdded", null, function(src, args) {
      appendEvent({
        type: "device-added",
        ts: Date.now(),
        name: args.name,
        model: args.model,
        uuid: args.uuid
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("deviceRemoved", null, function(src, args) {
      appendEvent({
        type: "device-removed",
        ts: Date.now(),
        name: args.name,
        uuid: args.uuid
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("linkCreated", null, function(src, args) {
      appendEvent({
        type: "link-created",
        ts: Date.now(),
        device1: args.device1 || args.device1Name,
        port1: args.port1 || args.port1Name,
        device2: args.device2 || args.device2Name,
        port2: args.port2 || args.port2Name,
        connType: args.connType
      });
      triggerSnapshot();
    });
    
    lw.registerEvent("linkDeleted", null, function(src, args) {
      appendEvent({
        type: "link-deleted",
        ts: Date.now(),
        device1: args.device1 || args.device1Name,
        port1: args.port1 || args.port1Name,
        device2: args.device2 || args.device2Name,
        port2: args.port2 || args.port2Name
      });
      triggerSnapshot();
    });
    
    // Command log events
    cl.setEnabled(true);
    cl.registerEvent("entryAdded", null, function(src, args) {
      try {
        var entry = cl.getEntryAt(args.index);
        appendEvent({
          type: "cli-command",
          ts: Date.now(),
          index: args.index,
          device: entry.getDeviceName ? entry.getDeviceName() : "",
          prompt: entry.getPrompt ? entry.getPrompt() : "",
          command: entry.getCommand ? entry.getCommand() : "",
          resolvedCommand: entry.getResolvedCommand ? entry.getResolvedCommand() : ""
        });
      } catch (e) {
        // Skip invalid entries
      }
    });
    
    dprint("[OK] Event listeners registered");
    
  } catch (e) {
    dprint("[WARN] Failed to setup event listeners: " + String(e));
  }
}

// ============================================================================
// Snapshot
// ============================================================================

function generateSnapshot() {
  try {
    var collected = collectDevices();
    var links = {};
    
    return {
      version: "1.0",
      timestamp: Date.now(),
      devices: collected.devices,
      links: links,
      metadata: {
        deviceCount: collected.count,
        linkCount: Object.keys(links).length
      }
    };
    
  } catch (e) {
    dprint("[ERROR] Failed to generate snapshot: " + String(e));
    return null;
  }
}

function triggerSnapshot() {
  var snapshot = generateSnapshot();
  if (snapshot) {
    writeState(snapshot);
    appendEvent({
      type: "snapshot",
      ts: Date.now(),
      devices: snapshot.metadata.deviceCount,
      links: snapshot.metadata.linkCount
    });
  }
}

// ============================================================================
// File Watcher (V2 - watches commands/ directory)
// ============================================================================

var lastProcessedId = "";

function pollCommandFile() {
  try {
    if (!fm.fileExists(COMMAND_FILE)) {
      lastProcessedId = "";
      return;
    }
    var content = fm.getFileContents(COMMAND_FILE);
    if (!content || content.length === 0) {
      return;
    }
    var cmd;
    try {
      cmd = JSON.parse(content);
    } catch (e) {
      return;
    }
    if (!cmd || !cmd.id || cmd.id === lastProcessedId) {
      return;
    }
    dprint("[DEBUG] Poll detected new command: " + cmd.id);
    processCommandFile();
    lastProcessedId = cmd.id;
  } catch (e) {
    dprint("[WARN] Poll error: " + String(e));
  }
}

function ensureDirectory(path) {
  try {
    if (!fm.directoryExists(path)) {
      fm.makeDirectory(path);
    }
  } catch (e) {
    dprint("[WARN] Failed to create directory " + path + ": " + String(e));
  }
}

function onFileChanged(src, args) {
  var path = args.path;
  
  if (path === RUNTIME_FILE) {
    if (reloadTimer) clearTimeout(reloadTimer);
    reloadTimer = setTimeout(function() {
      loadRuntime();
    }, 80);
  }
  
  // Reload main.js when it changes (hot reload via FileWatcher)
  if (path === DEV_DIR + "/main.js") {
    dprint("[INFO] main.js changed, reloading...");
    appendEvent({ type: "main-reload", ts: Date.now() });
    // PT will reload the script on next evaluation
  }
}

// ============================================================================
// Main
// ============================================================================

function main() {
  dprint("=== PT Control V2 Starting (Bridge V2) ===");
  
  try {
    fm = ipc.systemFileManager();
    fw = fm.getFileWatcher();

    // Ensure V2 directories exist
    if (!fm.directoryExists(DEV_DIR)) {
      fm.makeDirectory(DEV_DIR);
      dprint("[INFO] Created dev directory: " + DEV_DIR);
    }
    
    ensureDirectory(RESULTS_DIR);
    ensureDirectory(LOGS_DIR);

    // Setup file watcher
    fw.addPath(RUNTIME_FILE);
    fw.addPath(COMMAND_FILE);
    fw.registerEvent("fileChanged", null, onFileChanged);

    // Init event
    appendEvent({ type: "init", ts: Date.now(), version: "2.1" });
    
    // Setup PT event listeners
    setupEventListeners();
    
    // Load runtime if exists
    if (fm.fileExists(RUNTIME_FILE)) {
      loadRuntime();
    }

    // Initial snapshot
    triggerSnapshot();
    
    // Auto-snapshot every 5 seconds
    snapshotInterval = setInterval(function() {
      triggerSnapshot();
    }, 5000);

    // Poll command.json every 500ms (FileWatcher doesn't detect external changes)
    commandPollInterval = setInterval(function() {
      pollCommandFile();
    }, 500);

    // Clean stale sessions at startup (PT reopened after crash)
    cleanStaleSessions();

    // Heartbeat every 5 seconds
    heartbeatInterval = setInterval(function() {
      writeHeartbeat();
    }, 5000);
    writeHeartbeat(); // Write immediately

    dprint("[OK] PT Control V2 initialized (Bridge V2)");
    dprint("[INFO] Watching: " + DEV_DIR);
    dprint("[INFO] Command file: " + COMMAND_FILE);

  } catch (e) {
    dprint("[FATAL] Failed to initialize: " + String(e));
    appendEvent({
      type: "error",
      ts: Date.now(),
      message: "Failed to initialize module: " + String(e),
      stack: String(e.stack || "")
    });
  }
}

function cleanUp() {
  dprint("=== PT Control V2 Stopping ===");
  // Solo log - no limpiar timers para evitar crashes en PT
  try {
    appendEvent({ type: "log", ts: Date.now(), level: "info", message: "Module stopped" });
  } catch (e) {}
}
`;
