/**
 * CONFIG DIFFER
 *
 * Compara configuraciones IOS y genera comandos diferenciales para deployment incremental
 */

export interface ConfigDiff {
  /** Líneas agregadas */
  added: string[];
  /** Líneas removidas */
  removed: string[];
  /** Líneas modificadas (solo para referencia) */
  modified: Array<{ old: string; new: string; section: string }>;
  /** Secciones afectadas */
  affectedSections: string[];
}

export interface DiffOptions {
  /** Ignorar comentarios */
  ignoreComments?: boolean;
  /** Ignorar líneas en blanco */
  ignoreBlank?: boolean;
  /** Ignorar case */
  ignoreCase?: boolean;
  /** Secciones a comparar */
  sections?: string[];
}

/**
 * Compara configuraciones IOS y genera diff
 */
export class ConfigDiffer {
  /**
   * Compara dos configuraciones y retorna el diff
   * @param oldConfig - Configuración anterior (running-config)
   * @param newConfig - Configuración nueva (desired-config)
   * @param options - Opciones de comparación
   */
  static diff(
    oldConfig: string | string[],
    newConfig: string | string[],
    options: DiffOptions = {}
  ): ConfigDiff {
    const {
      ignoreComments = true,
      ignoreBlank = true,
      ignoreCase = false,
      sections
    } = options;

    // Parsear configuraciones a líneas
    const oldLines = this.parseConfig(oldConfig, { ignoreComments, ignoreBlank, ignoreCase });
    const newLines = this.parseConfig(newConfig, { ignoreComments, ignoreBlank, ignoreCase });

    // Filtrar por secciones si se especifica
    const filteredOld = sections ? this.filterBySections(oldLines, sections) : oldLines;
    const filteredNew = sections ? this.filterBySections(newLines, sections) : newLines;

    // Calcular diff
    const added = filteredNew.filter(line => !this.lineExistsInConfig(line, filteredOld));
    const removed = filteredOld.filter(line => !this.lineExistsInConfig(line, filteredNew));

    // Detectar modificaciones (líneas similares pero no iguales)
    const modified = this.detectModifications(filteredOld, filteredNew);

    // Determinar secciones afectadas
    const affectedSections = this.determineAffectedSections(added, removed, modified);

    return {
      added,
      removed,
      modified,
      affectedSections
    };
  }

  /**
   * Genera comandos IOS incrementales a partir del diff
   * Para remover configuraciones, prefija con 'no'
   */
  static generateIncrementalCommands(diff: ConfigDiff): string[] {
    const commands: string[] = [];

    // Remover primero (líneas que existían y ya no deben existir)
    for (const line of diff.removed) {
      if (this.isInterfaceLine(line)) {
        // Para interfaces, necesitamos entrar y hacer shutdown
        commands.push(line);
        commands.push(' no shutdown');
        commands.push(' exit');
      } else if (this.isRemovableLine(line)) {
        commands.push(`no ${line}`);
      }
    }

    // Agregar después (líneas nuevas)
    for (const line of diff.added) {
      commands.push(line);
    }

    return commands;
  }

  /**
   * Genera script de rollback (vuelve a la configuración anterior)
   */
  static generateRollbackScript(diff: ConfigDiff): string[] {
    const commands: string[] = [];

    commands.push('! Rollback script');
    commands.push('! Generated by cisco-auto ConfigDiffer');
    commands.push('');

    // Revertir: remover lo agregado y agregar lo removido
    for (const line of diff.added) {
      if (this.isRemovableLine(line)) {
        commands.push(`no ${line}`);
      }
    }

    for (const line of diff.removed) {
      commands.push(line);
    }

    commands.push('');
    commands.push('end');
    commands.push('write memory');

    return commands;
  }

  /**
   * Parsea configuración a array de líneas
   */
  private static parseConfig(
    config: string | string[],
    options: { ignoreComments: boolean; ignoreBlank: boolean; ignoreCase: boolean }
  ): string[] {
    let lines: string[];

    if (typeof config === 'string') {
      lines = config.split('\n');
    } else {
      lines = config;
    }

    return lines.filter(line => {
      const trimmed = line.trim();

      if (options.ignoreBlank && trimmed === '') return false;
      if (options.ignoreComments && this.isComment(trimmed)) return false;

      return options.ignoreCase ? trimmed.toLowerCase() : trimmed;
    }).map(line => options.ignoreCase ? line.toLowerCase() : line);
  }

  /**
   * Filtra líneas por secciones
   */
  private static filterBySections(lines: string[], sections: string[]): string[] {
    // Simple implementation: look for section markers like '! --- BASIC ---'
    const result: string[] = [];
    let inSection = false;
    let currentSection = '';

    for (const line of lines) {
      const sectionMatch = line.match(/! --- (\w+) ---/);
      if (sectionMatch) {
        currentSection = sectionMatch[1]!.toLowerCase();
        inSection = sections.some(s => s.toLowerCase() === currentSection);
        continue;
      }

      if (inSection) {
        result.push(line);
      }
    }

    return result;
  }

  /**
   * Verifica si una línea existe en una configuración
   */
  private static lineExistsInConfig(line: string, config: string[]): boolean {
    const normalizedLine = line.trim();
    return config.some(l => l.trim() === normalizedLine);
  }

  /**
   * Detecta modificaciones entre configuraciones
   */
  private static detectModifications(
    oldLines: string[],
    newLines: string[]
  ): Array<{ old: string; new: string; section: string }> {
    const modified: Array<{ old: string; new: string; section: string }> = [];

    // Simple heuristic: lines that share a common prefix but differ in value
    const oldMap = new Map<string, string>();
    const newMap = new Map<string, string>();

    for (const line of oldLines) {
      const key = this.extractConfigKey(line);
      if (key) oldMap.set(key, line);
    }

    for (const line of newLines) {
      const key = this.extractConfigKey(line);
      if (key) newMap.set(key, line);
    }

    for (const [key, oldLine] of oldMap.entries()) {
      const newLine = newMap.get(key);
      if (newLine && oldLine !== newLine) {
        modified.push({
          old: oldLine,
          new: newLine,
          section: 'unknown'
        });
      }
    }

    return modified;
  }

  /**
   * Extrae la clave de configuración de una línea
   * Ej: 'ip address 192.168.1.1 255.255.255.0' -> 'ip address'
   */
  private static extractConfigKey(line: string): string | null {
    const trimmed = line.trim();

    // Patrones comunes
    const patterns = [
      /^(hostname|ip domain-name|banner motd)/i,
      /^(interface \S+)/i,
      /^(vlan \d+)/i,
      /^(router (ospf|eigrp|bgp|rip) \S+)/i,
      /^(ip route \S+)/i,
      /^(access-list \d+)/i,
      /^(ip access-list \w+ \w+)/i,
      /^(\w+ \w+)/i  // Generic: first two words
    ];

    for (const pattern of patterns) {
      const match = trimmed.match(pattern);
      if (match) {
        return match[1]?.toLowerCase() || null;
      }
    }

    return null;
  }

  /**
   * Determina secciones afectadas por los cambios
   */
  private static determineAffectedSections(
    added: string[],
    removed: string[],
    modified: Array<{ old: string; new: string; section: string }>
  ): string[] {
    const sections = new Set<string>();

    const allChanges = [...added, ...removed, ...modified.map(m => m.new)];

    for (const line of allChanges) {
      if (this.isInterfaceLine(line)) sections.add('interfaces');
      if (this.isVlanLine(line)) sections.add('vlans');
      if (this.isRoutingLine(line)) sections.add('routing');
      if (this.isSecurityLine(line)) sections.add('security');
      if (this.isBasicLine(line)) sections.add('basic');
      if (this.isLineLine(line)) sections.add('lines');
    }

    return Array.from(sections);
  }

  /**
   * Verifica si una línea es un comentario
   */
  private static isComment(line: string): boolean {
    return line.trim().startsWith('!') || line.trim() === '';
  }

  /**
   * Verifica si una línea es de interfaz
   */
  private static isInterfaceLine(line: string): boolean {
    return /^interface\s+/i.test(line.trim());
  }

  /**
   * Verifica si una línea es de VLAN
   */
  private static isVlanLine(line: string): boolean {
    return /^(vlan \d+| switchport | spanning-tree )/i.test(line.trim());
  }

  /**
   * Verifica si una línea es de routing
   */
  private static isRoutingLine(line: string): boolean {
    const trimmed = line.trim();
    return /^(router |router-id |ip route |ip ospf |network |passive-interface | eigrp | bgp | rip )/i.test(trimmed);
  }

  /**
   * Verifica si una línea es de seguridad
   */
  private static isSecurityLine(line: string): boolean {
    return /^(access-list |ip access-list |ip nat |crypto )/i.test(line.trim());
  }

  /**
   * Verifica si una línea es de configuración básica
   */
  private static isBasicLine(line: string): boolean {
    return /^(hostname |ip domain-name |banner |service |no ip domain-lookup)/i.test(line.trim());
  }

  /**
   * Verifica si una línea es de líneas (console/vty)
   */
  private static isLineLine(line: string): boolean {
    return /^line (console|vty|aux)/i.test(line.trim());
  }

  /**
   * Verifica si una línea puede ser removida con 'no'
   */
  private static isRemovableLine(line: string): boolean {
    const trimmed = line.trim();
    // No remover comandos que ya tienen 'no' o son estructurales
    if (trimmed.startsWith('no ')) return false;
    if (/^(interface |router |line |vlan )/i.test(trimmed)) return false;
    if (/^(exit|end|write|copy)/i.test(trimmed)) return false;

    return true;
  }

  /**
   * Formatea diff para visualización
   */
  static formatDiff(diff: ConfigDiff): string {
    const lines: string[] = [];

    lines.push('=== Configuration Diff ===');
    lines.push('');

    if (diff.added.length > 0) {
      lines.push('+ ADDED:');
      for (const line of diff.added) {
        lines.push(`  + ${line}`);
      }
      lines.push('');
    }

    if (diff.removed.length > 0) {
      lines.push('- REMOVED:');
      for (const line of diff.removed) {
        lines.push(`  - ${line}`);
      }
      lines.push('');
    }

    if (diff.modified.length > 0) {
      lines.push('~ MODIFIED:');
      for (const mod of diff.modified) {
        lines.push(`  ~ ${mod.section}:`);
        lines.push(`    - ${mod.old}`);
        lines.push(`    + ${mod.new}`);
      }
      lines.push('');
    }

    if (diff.affectedSections.length > 0) {
      lines.push(`Affected sections: ${diff.affectedSections.join(', ')}`);
    }

    return lines.join('\n');
  }
}

export default ConfigDiffer;
