/**
 * PT Control - Parsed IOS Output Types
 * 
 * @deprecated Import directly from @cisco-auto/types instead
 * This file is kept for backwards compatibility during migration
 */

// Re-export from @cisco-auto/types for backwards compatibility
export {
  InterfaceBriefSchema,
  ShowIpInterfaceBriefSchema,
  InterfaceDetailSchema,
  ShowInterfacesSchema,
  VlanEntrySchema,
  ShowVlanSchema,
  TrunkPortSchema,
  ShowInterfacesTrunkSchema,
  SwitchportInfoSchema,
  ShowInterfacesSwitchportSchema,
  RouteEntrySchema,
  ShowIpRouteSchema,
  RoutingProtocolSchema,
  ShowIpProtocolsSchema,
  RunningConfigSectionSchema,
  ShowRunningConfigSchema,
  ArpEntrySchema,
  ShowIpArpSchema,
  MacEntrySchema,
  ShowMacAddressTableSchema,
  StpPortSchema,
  StpVlanSchema,
  ShowSpanningTreeSchema,
  ShowVersionSchema,
  CdpNeighborSchema,
  ShowCdpNeighborsSchema,
  ParsedOutputSchema,
  type InterfaceBrief,
  type ShowIpInterfaceBrief,
  type InterfaceDetail,
  type ShowInterfaces,
  type VlanEntry,
  type ShowVlan,
  type TrunkPort,
  type ShowInterfacesTrunk,
  type SwitchportInfo,
  type ShowInterfacesSwitchport,
  type RouteEntry,
  type ShowIpRoute,
  type RoutingProtocol,
  type ShowIpProtocols,
  type RunningConfigSection,
  type ShowRunningConfig,
  type ArpEntry,
  type ShowIpArp,
  type MacEntry,
  type ShowMacAddressTable,
  type StpPort,
  type StpVlan,
  type ShowSpanningTree,
  type ShowVersion,
  type CdpNeighbor,
  type ShowCdpNeighbors,
  type ParsedOutput,
  type ParserFunction,
  type ParserRegistry,
} from '@cisco-auto/types';
