import { Command } from 'commander';


/**
 * Genera script de completion para Bash
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generateBashCompletion(programName: string, commands: string[]): string {
  const cmdList = commands.map(c => `'${c}'`).join(' ');
  
  return `#!/bin/bash

# Bash completion for ${programName}
# Generated by ${programName} from command-registry.js

_${programName}_completion() {
  local cur prev cmds
  
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD - 1]}"
  
  cmds="${cmdList}"
  
  # Completar comandos
  if [[ $COMP_CWORD -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
    return 0
  fi
  
  # Completar opciones globales
  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "--help --version --verbose --json --no-pt --yes" -- "$cur") )
    return 0
  fi

  return 0
}

complete -F _${programName}_completion ${programName}
`;
}
  

/**
 * Genera script de completion para Zsh
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generateZshCompletion(programName: string, commands: string[]): string {
  const cmdList = commands.join(' ');
  
  return `#compdef ${programName}

# Zsh completion for ${programName}
# Generated by ${programName} from command-registry.js

_${programName}_completion() {
  local -a commands options
  
  commands=(
    ${cmdList}
  )
  
  options=(
    '-h[Mostrar ayuda]'
    '--help[Mostrar ayuda]'
    '-v[Modo verbose]'
    '--verbose[Modo verbose]'
    '--json[Salida en formato JSON]'
    '--no-pt[No requiere Packet Tracer]'
    '--yes[Auto-confirmar]'
  )
  
  _arguments -C \\
    '1: :->command' \\
    '*:: :->option-or-arg' \\
    && return 0
    
  case $state in
    command)
      _describe 'command' commands
      ;;
  esac
}

_${programName}_completion "$@"
`;
}


/**
 * Genera script de completion para Fish
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generateFishCompletion(programName: string, commands: string[], summaries: Record<string, string>): string {
  let script = `# Fish completion for ${programName}
# Generated by ${programName} from command-registry.js

complete -c ${programName} -f

# Opciones globales
complete -c ${programName} -n '__fish_use_subcommand' -l help -d 'Mostrar ayuda'
complete -c ${programName} -n '__fish_use_subcommand' -l version -d 'Mostrar version'
complete -c ${programName} -n '__fish_use_subcommand' -l verbose -d 'Modo verbose'
complete -c ${programName} -n '__fish_use_subcommand' -l json -d 'Salida en formato JSON'

# Comandos principales
`;

  for (const cmdId of commands) {
    const summary = summaries[cmdId] || '';
    script += `complete -c ${programName} -n '__fish_use_subcommand' -a '${cmdId}' -d '${summary.replace(/'/g, "\\'")}'\n`;
  }

  return script;
}

/**
 * Genera script de completion para PowerShell
 * @param programName Nombre del programa
 * @param commands Lista de comandos disponibles
 */
function generatePowerShellCompletion(programName: string, commands: string[], summaries: Record<string, string>): string {
  let commandsList = commands.map(cmdId => {
    const summary = summaries[cmdId] || '';
    return `    @{ Name = '${cmdId}'; Description = '${summary.replace(/'/g, "''")}' }`;
  }).join('\n');

  return `# PowerShell completion for ${programName}
# Generated by ${programName} from command-registry.js

${programName}-Completion {

  param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [System.Management.Automation.CommandTypes]$CommandType,
    
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$WordToComplete,
    
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [System.Management.Automation.CommandCompletion]$CommandAst
  )

  $commands = @(
${commandsList}
  )
  
  $options = @(
    @{ Name = '--help'; Description = 'Mostrar ayuda' }
    @{ Name = '--version'; Description = 'Mostrar version' }
    @{ Name = '--verbose'; Description = 'Modo verbose' }
    @{ Name = '--json'; Description = 'Salida en formato JSON' }
    @{ Name = '-h'; Description = 'Mostrar ayuda (corto)' }
    @{ Name = '-v'; Description = 'Modo verbose (corto)' }
  )
  
  # Si es el primer comando, completar nombres de comando
  if ($CommandAst.CommandElements.Count -eq 1) {
    $results = $commands | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
      [System.Management.Automation.Automation.CompletionResult]::new(
        $_.Name,
        $_.Name,
        'ParameterValue',
        $_.Description
      )
    }
    return $results
  }
  
  return $options | Where-Object { $_.Name -like "$WordToComplete*" } | ForEach-Object {
    [System.Management.Automation.Automation.CompletionResult]::new(
      $_.Name,
      $_.Name,
      'ParameterValue',
      $_.Description
    )
  }
}

Register-ArgumentCompleter -CommandName ${programName} -ScriptBlock ${programName}-Completion
`;
}

/**
 * Mensaje de instalación para Bash
 */
const BASH_INSTALL = `
# Instalación (agregar a ~/.bashrc o ~/.bash_profile):
# source <(pt completion bash)

# Para instalación permanente:
# pt completion bash >> ~/.bashrc
`;

const ZSH_INSTALL = `
# Instalación (agregar a ~/.zshrc):
# source <(pt completion zsh)

# Para instalación permanente:
# pt completion zsh >> ~/.zshrc
`;

const FISH_INSTALL = `
# Instalación:
# mkdir -p ~/.config/fish/completions
# pt completion fish > ~/.config/fish/completions/pt.fish
`;

const POWERSHELL_INSTALL = `
# Instalación (agregar a $PROFILE):
# pt completion powershell >> $PROFILE
`;

type ShellType = 'bash' | 'zsh' | 'fish' | 'powershell';

/**
 * Crea el comando de completion
 */
export function createCompletionCommand(): Command {
  return new Command("completion")
    .description("Generar scripts de completion para shell")
    .argument("<shell>", "Shell objetivo: bash, zsh, fish, powershell")
    .option("--install-help", "Imprimir instrucciones de instalación en stderr", false)
    .action(async (shell: string, options: { installHelp?: boolean }) => {
      const { PUBLIC_COMMAND_DEFINITIONS } = await import("./command-registry.js");

      const visibleDefinitions = PUBLIC_COMMAND_DEFINITIONS.filter(
        (cmd) => !cmd.hidden && !cmd.legacy,
      );

      const AVAILABLE_COMMANDS = visibleDefinitions.flatMap((cmd) => [
        cmd.name,
        ...(cmd.aliases ?? []),
      ]);

      const COMMAND_SUMMARIES = Object.fromEntries(
        visibleDefinitions.map((cmd) => [cmd.name, cmd.summary ?? ""]),
      );

      const shellType = shell.toLowerCase() as ShellType;

      const validShells: ShellType[] = ["bash", "zsh", "fish", "powershell"];
      if (!validShells.includes(shellType)) {
        process.stderr.write(`❌ Shell no soportado: ${shell}\n`);
        process.stderr.write("Shells disponibles: bash, zsh, fish, powershell\n");
        process.exit(1);
      }

      const programName = "pt";
      let script = "";
      let installMsg = "";

      switch (shellType) {
        case "bash":
          script = generateBashCompletion(programName, AVAILABLE_COMMANDS);
          installMsg = BASH_INSTALL;
          break;
        case "zsh":
          script = generateZshCompletion(programName, AVAILABLE_COMMANDS);
          installMsg = ZSH_INSTALL;
          break;
        case "fish":
          script = generateFishCompletion(programName, AVAILABLE_COMMANDS, COMMAND_SUMMARIES);
          installMsg = FISH_INSTALL;
          break;
        case "powershell":
          script = generatePowerShellCompletion(programName, AVAILABLE_COMMANDS, COMMAND_SUMMARIES);
          installMsg = POWERSHELL_INSTALL;
          break;
      }

      process.stdout.write(script.endsWith("\n") ? script : `${script}\n`);

      if (options.installHelp) {
        process.stderr.write("\n");
        process.stderr.write("=".repeat(60));
        process.stderr.write("\n📝 INSTRUCCIONES DE INSTALACIÓN\n");
        process.stderr.write("=".repeat(60));
        process.stderr.write("\n");
        process.stderr.write(installMsg);
        process.stderr.write("\n");
      }
    });
}
