// PT_DEVICE_TYPE_CONSTANTS, PT_CABLE_TYPE_CONSTANTS, PT_API_METHOD_INDEX

/**
 * Verified PT 9.0 device typeId constants.
 * Source: PT-API-COMPLETE.md live-extracted map (authoritative).
 * NOTE: addDevice(typeId, model, x, y) — some typeIds return null (broken in PT 9.0):
 *   - cloud (7): addDevice returns null — use PT UI to add clouds
 *   - laptop (18): use model "Laptop-PT"
 *   - ipPhone (12): use model "7960"
 * Use pt-constants.ts PT_HELPER_MAPS.DEVICE_TYPES for the full runtime map.
 */
export const PT_DEVICE_TYPE_CONSTANTS: Record<string, number> = {
  router: 0,
  switch: 1,
  hub: 2,
  bridge: 3,
  repeater: 4,
  coaxialSplitter: 5,
  wireless: 7,
  pc: 8,
  server: 9,
  printer: 10,
  wirelessRouter: 11,
  ipPhone: 12,
  dslModem: 13,
  cableModem: 14,
  multilayerSwitch: 16,
  laptop: 18,
  tablet: 19,
  smartphone: 20,
  wirelessEndDevice: 21,
  wiredEndDevice: 22,
  tv: 23,
  homeVoip: 24,
  analogPhone: 25,
  firewall: 27, // ASA
  iot: 34,
  sniffer: 35,
  mcu: 36,
  sbc: 37,
};

export const PT_CABLE_TYPE_CONSTANTS: Record<string, number> = {
  auto: -1,
  straight: 0,
  cross: 1,
  fiber: 2,
  serial: 3,
  console: 4,
  phone: 5,
  cable: 6,
  roll: 7,
  wireless: 8,
  coaxial: 9,
  custom: 10,
  octal: 11,
  cellular: 12,
  usb: 13,
};

export const PT_API_METHOD_INDEX: Record<string, string[]> = {
  PTIpc: [
    "network",
    "appWindow",
    "systemFileManager",
    "simulation",
    "hardwareFactory",
    "ipcManager",
    "multiUserManager",
    "userAppManager",
    "commandLog",
    "options",
  ],
  PTAppWindow: [
    "getActiveWorkspace",
    "getVersion",
    "fileNew",
    "fileOpen",
    "fileSave",
    "fileSaveAs",
    "fileSaveAsPkz",
    "getClipboardText",
    "setClipboardText",
    "openURL",
    "getWidth",
    "getHeight",
    "getX",
    "getY",
    "showNormal",
    "showMaximized",
    "showMinimized",
    "setWindowGeometry",
  ],
  PTWorkspace: [
    "getLogicalWorkspace",
    "getGeoView",
    "getRackView",
    "zoomIn",
    "zoomOut",
    "zoomReset",
    "getEnvironmentTimeInSeconds",
    "pauseEnvironmentTime",
    "resumeEnvironmentTime",
    "resetEnvironment",
  ],
  PTLogicalWorkspace: [
    "addDevice",
    "removeDevice",
    "removeObject",
    "deleteObject",
    "createLink",
    "autoConnectDevices",
    "deleteLink",
    "addCluster",
    "addNote",
    "addTextPopup",
    "addRemoteNetwork",
    "changeNoteText",
    "setCanvasItemRealPos",
    "setDeviceCustomImage",
    "clearLayer",
    "drawCircle",
    "drawLine",
    "getCanvasRectIds",
    "getCanvasEllipseIds",
    "getCanvasItemIds",
    "getCanvasNoteIds",
    "getRectItemData",
    "centerOn",
    "centerOnComponentByName",
    "devicesAt",
  ],
  PTNetwork: ["getDevice", "getDeviceAt", "getDeviceCount", "getLinkAt", "getLinkCount"],
  PTDevice: [
    "getName",
    "setName",
    "getModel",
    "getType",
    "getPower",
    "setPower",
    "skipBoot",
    "getCommandLine",
    "getPortCount",
    "getPortAt",
    "getPort",
    "addModule",
    "removeModule",
    "setDhcpFlag",
    "getDhcpFlag",
    "moveToLocation",
    "moveToLocationCentered",
    "getX",
    "getY",
    "serializeToXml",
    "getProcess",
    "getRootModule",
    "isBooting",
    "restoreToDefault",
    "getUpTime",
    "getSerialNumber",
  ],
  PTModule: [
    "getSlotCount",
    "getSlotTypeAt",
    "getModuleCount",
    "getModuleAt",
    "addModuleAt",
    "removeModuleAt",
    "getPortCount",
    "getPortAt",
    "getOwnerDevice",
  ],
  PTServer: [
    "enableCip",
    "disableCip",
    "enableOpc",
    "disableOpc",
    "enableProfinet",
    "disableProfinet",
    "addProgrammingSerialOutputs",
    "clearProgrammingSerialOutputs",
    "addUserDesktopApp",
    "removeUserDesktopApp",
    "isDesktopAvailable",
  ],
  PTAsa: [
    "addBookmark",
    "removeBookmark",
    "getBookmarkCount",
    "getWebvpnUserManager",
    "setHostName",
    "setEnablePassword",
    "setEnableSecret",
  ],
  PTCloud: [
    "addPhoneConnection",
    "addPortConnection",
    "addSubLinkConnection",
    "removePortConnection",
    "removeAllPortConnection",
    "isDslConnection",
  ],
  PTMcu: [
    "analogWrite",
    "digitalWrite",
    "analogRead",
    "digitalRead",
    "getSlotsCount",
    "getAnalogSlotsCount",
    "getDigitalSlotsCount",
    "getComponentAtSlot",
    "getComponentByName",
    "enableIec61850",
    "disableIec61850",
    "enableGoosePublisherOnPort",
    "setSubComponentIndex",
  ],
  PTWirelessRouter: ["addNatEntry", "removeNatEntry", "setDMZEntry", "isRemoteManagementEnable"],
  PTSimulation: [
    "backward",
    "forward",
    "resetSimulation",
    "setSimulationMode",
    "isSimulationMode",
    "createFrameInstance",
    "getCurrentSimTime",
  ],
  PTOptions: [
    "setAnimation",
    "setSound",
    "setHideDevLabel",
    "setDeviceModelShown",
    "setMainToolbarShown",
    "setCliTabHidden",
  ],
  PTCommandLog: ["getLogCount", "getLogAt", "clearLog"],
  PTCommandLine: [
    "enterCommand",
    "getPrompt",
    "getMode",
    "getCommandInput",
    "enterChar",
    "registerEvent",
    "unregisterEvent",
  ],
  PTPort: [
    "getName",
    "getIpAddress",
    "getSubnetMask",
    "setIpSubnetMask",
    "getDefaultGateway",
    "setDefaultGateway",
    "getDnsServerIp",
    "setDnsServerIp",
    "setDhcpEnabled",
    "setDhcpClientFlag",
    "isDhcpClientOn",
    "setIpv6Enabled",
    "getIpv6Enabled",
    "getIpv6Address",
    "setIpv6AddressAutoConfig",
    "setv6DefaultGateway",
    "getv6DefaultGateway",
    "setv6ServerIp",
    "getv6ServerIp",
    "setIpv6Mtu",
    "getIpv6Mtu",
    "isPortUp",
    "isProtocolUp",
    "isPowerOn",
    "setPower",
    "setInboundFirewallService",
    "getInboundFirewallService",
    "setMtu",
    "getMtu",
    "setIpMtu",
    "getIpMtu",
    "getBia",
    "isEthernetPort",
    "isWirelessPort",
    "getBandwidth",
    "setBandwidth",
    "getDelay",
    "setDelay",
    "isFullDuplex",
    "setFullDuplex",
  ],
  PTRouterPort: [
    "getOspfCost",
    "setOspfCost",
    "getOspfPriority",
    "setOspfPriority",
    "getOspfHelloInterval",
    "getOspfDeadInterval",
    "getOspfAuthKey",
    "getOspfAuthType",
    "addOspfMd5Key",
    "removeOspfMd5Key",
    "addEntryEigrpPassive",
    "removeEntryEigrpPassive",
    "isRipPassive",
    "setRipPassive",
    "isRipSplitHorizon",
    "setRipSplitHorizon",
    "getIpv6Addresses",
    "addIpv6Address",
    "getNatMode",
    "setNatMode",
    "getAclInID",
    "setAclInID",
    "getAclOutID",
    "setAclOutID",
    "setZoneMemberName",
    "getZoneMemberName",
    "getClockRate",
    "setClockRate",
  ],
  PTSwitchPort: [
    "getAccessVlan",
    "setAccessVlan",
    "getNativeVlanId",
    "setNativeVlanId",
    "getVoipVlanId",
    "setVoipVlanId",
    "addTrunkVlans",
    "removeTrunkVlans",
    "isAccessPort",
    "isAdminModeSet",
    "isNonegotiate",
    "setNonegotiateFlag",
    "getPortSecurity",
    "getStpStatus",
  ],
  PTRoutedSwitchPort: ["isRoutedPort", "setRoutedPort"],
  PTCloudSerialPort: ["addDlci", "removeDlci", "getDlciCount", "getDlciAt"],
  PTCloudPotsPort: ["getPhoneNumber", "setPhoneNumber"],
};