// ============================================================================
// AUTO-GENERATED MODULE MAP - DO NOT EDIT MANUALLY
// Generated by: generate-module-map.ts
// Source: @cisco-ai/catalog (modules.ts, routers.ts)
//
// Mapeo de módulos válidos y slots por modelo
// ============================================================================

var PT_MODULE_CATALOG = {
  "HWIC-2T": {
    "code": "HWIC-2T",
    "slotType": "hwic",
    "name": "2-Port Serial WAN Interface Card"
  },
  "HWIC-4ESW": {
    "code": "HWIC-4ESW",
    "slotType": "hwic",
    "name": "4-Port Ethernet Switch HWIC"
  },
  "HWIC-1GE-SFP": {
    "code": "HWIC-1GE-SFP",
    "slotType": "hwic",
    "name": "1-Port Gigabit Ethernet SFP HWIC"
  },
  "HWIC-AP": {
    "code": "HWIC-AP",
    "slotType": "hwic",
    "name": "Wireless Access Point HWIC"
  },
  "HWIC-4A/S": {
    "code": "HWIC-4A/S",
    "slotType": "hwic",
    "name": "4-Port Async/Sync Serial HWIC"
  },
  "WIC-2T": {
    "code": "WIC-2T",
    "slotType": "wic",
    "name": "2-Port Serial WAN Interface Card"
  },
  "WIC-1ENET": {
    "code": "WIC-1ENET",
    "slotType": "wic",
    "name": "1-Port Ethernet WIC"
  },
  "WIC-1ADSL": {
    "code": "WIC-1ADSL",
    "slotType": "wic",
    "name": "1-Port ADSL WIC"
  },
  "NM-16ESW": {
    "code": "NM-16ESW",
    "slotType": "nm",
    "name": "16-Port Ethernet Switch Network Module"
  },
  "NM-1FE-TX": {
    "code": "NM-1FE-TX",
    "slotType": "nm",
    "name": "1-Port Fast Ethernet Network Module"
  },
  "NM-4A/S": {
    "code": "NM-4A/S",
    "slotType": "nm",
    "name": "4-Port Async/Sync Network Module"
  },
  "NME-16ES-1G": {
    "code": "NME-16ES-1G",
    "slotType": "nme",
    "name": "16-Port Ethernet Switch with 1 GE Uplink"
  },
  "NME-X-23ES-1G": {
    "code": "NME-X-23ES-1G",
    "slotType": "nme",
    "name": "23-Port Ethernet Switch with 1 GE Uplink"
  },
  "SM-ES2-24": {
    "code": "SM-ES2-24",
    "slotType": "sm",
    "name": "24-Port Ethernet Switch Service Module"
  },
  "SM-ES3-24-P": {
    "code": "SM-ES3-24-P",
    "slotType": "sm",
    "name": "24-Port PoE Ethernet Switch Service Module"
  },
  "PVDM3-16": {
    "code": "PVDM3-16",
    "slotType": "pvdm",
    "name": "PVDM3 16-Channel DSP Module"
  },
  "PVDM3-32": {
    "code": "PVDM3-32",
    "slotType": "pvdm",
    "name": "PVDM3 32-Channel DSP Module"
  },
  "PVDM3-64": {
    "code": "PVDM3-64",
    "slotType": "pvdm",
    "name": "PVDM3 64-Channel DSP Module"
  }
};

var PT_DEVICE_MODULE_SLOTS = {
  "1841": [
    {
      "type": "hwic",
      "count": 2,
      "supportedModules": [
        "HWIC-2T",
        "HWIC-4ESW"
      ]
    }
  ],
  "1941": [
    {
      "type": "hwic",
      "count": 2,
      "supportedModules": [
        "HWIC-2T",
        "HWIC-4ESW",
        "HWIC-AP"
      ]
    }
  ],
  "2811": [
    {
      "type": "hwic",
      "count": 4,
      "supportedModules": [
        "HWIC-2T",
        "HWIC-4ESW"
      ]
    },
    {
      "type": "nm",
      "count": 1,
      "supportedModules": [
        "NM-16ESW"
      ]
    }
  ],
  "2901": [
    {
      "type": "hwic",
      "count": 2,
      "supportedModules": [
        "HWIC-2T",
        "HWIC-4ESW",
        "HWIC-AP"
      ]
    },
    {
      "type": "pvdm",
      "count": 2,
      "supportedModules": [
        "PVDM3-16",
        "PVDM3-32"
      ]
    }
  ],
  "2911": [
    {
      "type": "hwic",
      "count": 4,
      "supportedModules": [
        "HWIC-2T",
        "HWIC-4ESW",
        "HWIC-AP"
      ]
    },
    {
      "type": "pvdm",
      "count": 3,
      "supportedModules": [
        "PVDM3-16",
        "PVDM3-32"
      ]
    }
  ],
  "ISR4321": [
    {
      "type": "nme",
      "count": 1,
      "supportedModules": [
        "NME-16ES-1G"
      ]
    }
  ],
  "ISR4331": [
    {
      "type": "nme",
      "count": 2,
      "supportedModules": [
        "NME-16ES-1G",
        "NME-X-23ES-1G"
      ]
    }
  ],
  "2620XM": [
    {
      "type": "wic",
      "count": 2,
      "supportedModules": [
        "WIC-2T"
      ]
    },
    {
      "type": "nm",
      "count": 1,
      "supportedModules": [
        "NM-16ESW"
      ]
    }
  ],
  "2621XM": [
    {
      "type": "wic",
      "count": 2,
      "supportedModules": [
        "WIC-2T"
      ]
    },
    {
      "type": "nm",
      "count": 1,
      "supportedModules": [
        "NM-16ESW"
      ]
    }
  ],
  "CGR1240": [
    {
      "type": "hwic",
      "count": 2,
      "supportedModules": [
        "HWIC-2T"
      ]
    }
  ],
  "C8200": [
    {
      "type": "nme",
      "count": 2,
      "supportedModules": [
        "NME-16ES-1G"
      ]
    }
  ]
};
