// ============================================================================
// Terminal Regression Profile - Smoke tests para terminal IOS y host
// ============================================================================

export interface TerminalRegressionCase {
  id: string;
  description: string;
  device: string;
  deviceKind: "ios" | "host";
  command: string;
  preCommands?: string[];
  postCommands?: string[];
  expectedOk: boolean;
  tags: string[];
  expectedPromptPattern?: string;
  expectedModeAfter?: string;
  expectedOutputIncludes?: string[];
  expectedErrorCode?: string;
  expectedErrorIncludes?: string[];
  maxDurationMs: number;
  tier?: "smoke" | "full";
  unstable?: boolean;
}

export const terminalRegressionCases: TerminalRegressionCase[] = [
  // ========================================================================
  // IOS básico
  // ========================================================================
  {
    id: "ios-show-clock",
    description: "show clock responde con hora IOS",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show clock",
    expectedOk: true,
    tags: ["ios", "show", "short-output"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    expectedOutputIncludes: ["show clock", "UTC"],
    postCommands: ["enable"],
    maxDurationMs: 10000,
  },
  {
    id: "ios-show-version",
    description: "show version muestra info del dispositivo",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show version",
    expectedOk: true,
    tags: ["ios", "show"],
    expectedOutputIncludes: ["Cisco IOS Software"],
    maxDurationMs: 10000,
  },
  {
    id: "ios-show-privilege",
    description: "show privilege preserva el modo actual y muestra nivel",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show privilege",
    expectedOk: true,
    tags: ["ios", "show", "privilege"],
    expectedOutputIncludes: ["privilege level"],
    maxDurationMs: 10000,
  },
  {
    id: "ios-show-privilege-user-exec",
    description: "show privilege desde user exec preserva modo y muestra privilege level 1",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["disable"],
    command: "show privilege",
    expectedOk: true,
    tags: ["ios", "show", "privilege", "preserve-mode"],
    expectedPromptPattern: ">",
    expectedModeAfter: "user-exec",
    expectedOutputIncludes: ["Current privilege level"],
    postCommands: ["enable"],
    maxDurationMs: 15000,
  },
  {
    id: "ios-show-privilege-privileged-exec",
    description: "show privilege desde privileged exec preserva modo y muestra privilege level 15",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show privilege",
    expectedOk: true,
    tags: ["ios", "show", "privilege", "preserve-mode"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    expectedOutputIncludes: ["Current privilege level"],
    maxDurationMs: 15000,
  },
  {
    id: "ios-show-privilege-after-running-config",
    description: "show privilege no debe colgarse despues de show running-config paginado",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable", "show running-config"],
    command: "show privilege",
    expectedOk: true,
    tags: ["ios", "show", "privilege", "pager-regression"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    expectedOutputIncludes: ["Current privilege level"],
    maxDurationMs: 20000,
  },
  {
    id: "ios-enable",
    description: "enable entra a privileged exec",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: [],
    command: "enable",
    expectedOk: true,
    tags: ["ios", "mode"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    maxDurationMs: 10000,
  },
  {
    id: "ios-disable",
    description: "disable vuelve a user exec desde privileged exec",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "disable",
    expectedOk: true,
    tags: ["ios", "mode", "disable"],
    expectedPromptPattern: ">",
    expectedModeAfter: "user-exec",
    expectedOutputIncludes: ["disable"],
    postCommands: ["enable"],
    maxDurationMs: 15000,
  },
  {
    id: "ios-disable-after-show-running-config",
    description: "disable no debe colgarse despues de show running-config paginado",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable", "show running-config"],
    command: "disable",
    expectedOk: true,
    tags: ["ios", "mode", "pager-regression", "disable"],
    expectedPromptPattern: ">",
    expectedModeAfter: "user-exec",
    expectedOutputIncludes: ["disable"],
    postCommands: ["enable"],
    maxDurationMs: 20000,
  },
  {
    id: "ios-config-t",
    description: "conf t entra a configure terminal",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "conf t",
    expectedOk: true,
    tags: ["ios", "config", "mode"],
    expectedPromptPattern: "(config)#",
    expectedModeAfter: "global-config",
    postCommands: ["end"],
    maxDurationMs: 10000,
  },
  {
    id: "ios-interface",
    description: "interface fa0/1 entra a config-if",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable", "conf t"],
    command: "interface fa0/1",
    expectedOk: true,
    tags: ["ios", "config", "submode"],
    expectedPromptPattern: "(config-if)#",
    expectedModeAfter: "config-if",
    postCommands: ["end"],
    maxDurationMs: 10000,
  },
  {
    id: "ios-exit",
    description: "exit desde config-if vuelve a global-config",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable", "conf t", "interface fa0/1"],
    command: "exit",
    expectedOk: true,
    tags: ["ios", "config", "mode"],
    expectedPromptPattern: "(config)#",
    expectedModeAfter: "global-config",
    postCommands: ["end"],
    maxDurationMs: 10000,
  },
  {
    id: "ios-end",
    description: "end desde config-if vuelve a privileged exec",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable", "conf t", "interface fa0/1"],
    command: "end",
    expectedOk: true,
    tags: ["ios", "config", "mode"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    maxDurationMs: 10000,
  },

  // ========================================================================
  // Pager (casos críticos)
  // ========================================================================
  {
    id: "ios-show-running-config",
    description: "show running-config con paginacion automatica",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show running-config",
    expectedOk: true,
    tags: ["ios", "show", "pager", "long-output"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    expectedOutputIncludes: ["Building configuration", "Current configuration"],
    maxDurationMs: 70000,
    tier: "full",
  },
  {
    id: "ios-show-interfaces",
    description: "show interfaces con paginacion",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show interfaces",
    expectedOk: true,
    tags: ["ios", "show", "pager"],
    expectedOutputIncludes: ["FastEthernet0/1"],
    maxDurationMs: 70000,
    tier: "full",
  },
  {
    id: "ios-show-spanning-tree",
    description: "show spanning-tree con paginacion",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show spanning-tree",
    expectedOk: true,
    tags: ["ios", "show", "pager"],
    expectedOutputIncludes: ["Spanning Tree"],
    maxDurationMs: 70000,
    tier: "full",
  },
  {
    id: "ios-show-mac-address-table",
    description: "show mac address-table dynamic",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show mac address-table dynamic",
    expectedOk: true,
    tags: ["ios", "show", "pager"],
    expectedOutputIncludes: ["MAC Address"],
    maxDurationMs: 70000,
    tier: "full",
  },

  // ========================================================================
  // Confirm prompts
  // ========================================================================
  {
    id: "ios-copy-running-config",
    description: "copy running-config startup-config con confirmacion",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "copy running-config startup-config",
    expectedOk: true,
    tags: ["ios", "config", "confirm", "unstable"],
    expectedOutputIncludes: ["Destination filename"],
    maxDurationMs: 30000,
    tier: "full",
    unstable: true,
  },
  {
    id: "ios-write-memory",
    description: "write memory con confirmacion",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "write memory",
    expectedOk: true,
    tags: ["ios", "config", "confirm"],
    expectedOutputIncludes: ["Building configuration"],
    maxDurationMs: 30000,
    tier: "full",
  },

  // ========================================================================
  // Errores semánticos
  // ========================================================================
  {
    id: "ios-invalid-input",
    description: "comando invalido genera error IOS",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show esto-no-existe",
    expectedOk: false,
    tags: ["ios", "semantic-error"],
    expectedErrorCode: "IOS_INVALID_INPUT",
    expectedErrorIncludes: ["% Invalid input detected"],
    postCommands: [],
    maxDurationMs: 10000,
  },
  {
    id: "ios-incomplete",
    description: "comando incompleto genera error",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show",
    expectedOk: false,
    tags: ["ios", "semantic-error"],
    expectedErrorCode: "IOS_INCOMPLETE_COMMAND",
    expectedErrorIncludes: ["% Incomplete command"],
    postCommands: [],
    maxDurationMs: 10000,
  },
  {
    id: "ios-ambiguous",
    description: "comando ambiguo genera error cuando PT/modelo lo soporte",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show i",
    expectedOk: false,
    tags: ["ios", "semantic-error", "unstable"],
    expectedErrorCode: "IOS_AMBIGUOUS_COMMAND",
    expectedErrorIncludes: ["% Ambiguous command"],
    postCommands: [],
    maxDurationMs: 10000,
    tier: "full",
    unstable: true,
  },
  {
    id: "ios-show-running-config-auto-enable",
    description: "show running-config desde user exec auto-eleva a privileged exec y devuelve config",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["disable"],
    command: "show running-config",
    expectedOk: true,
    tags: ["ios", "show", "pager", "auto-enable"],
    expectedPromptPattern: "#",
    expectedModeAfter: "privileged-exec",
    expectedOutputIncludes: ["Building configuration", "Current configuration"],
    maxDurationMs: 70000,
    tier: "full",
  },

  // ========================================================================
  // Host
  // ========================================================================
  {
    id: "host-ipconfig",
    description: "IPCONFIG /all para ver IP completa",
    device: "PC0",
    deviceKind: "host",
    command: "ipconfig /all",
    expectedOk: true,
    tags: ["host", "show"],
    expectedOutputIncludes: ["IPv4 Address", "Subnet Mask"],
    maxDurationMs: 10000,
  },
  {
    id: "host-ping-success",
    description: "ping exitoso a localhost",
    device: "PC0",
    deviceKind: "host",
    command: "ping 127.0.0.1",
    expectedOk: true,
    tags: ["host", "ping"],
    expectedOutputIncludes: ["Reply from 127.0.0.1"],
    maxDurationMs: 15000,
  },
  {
    id: "host-ping-timeout",
    description: "ping timeout esperado debe reportarse como fallo semántico",
    device: "PC0",
    deviceKind: "host",
    command: "ping 10.255.255.255",
    expectedOk: false,
    tags: ["host", "ping", "timeout-expected", "semantic-error"],
    expectedErrorCode: "HOST_NETWORK_TIMEOUT",
    expectedErrorIncludes: ["Request timed out"],
    maxDurationMs: 20000,
    tier: "full",
  },
  {
    id: "host-invalid",
    description: "comando host invalido debe fallar semanticamente",
    device: "PC0",
    deviceKind: "host",
    command: "comando-invalido",
    expectedOk: false,
    tags: ["host", "semantic-error"],
    expectedErrorCode: "HOST_INVALID_COMMAND",
    expectedErrorIncludes: ["invalid", "not recognized", "bad command"],
    maxDurationMs: 10000,
  },

  // ========================================================================
  // Edge cases
  // ========================================================================
  {
    id: "ios-short-output",
    description: "comando show valido de salida corta en Catalyst 2960",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show vlan brief",
    expectedOk: true,
    tags: ["ios", "show", "short-output"],
    expectedOutputIncludes: ["VLAN", "Name", "Status"],
    maxDurationMs: 15000,
  },
  {
    id: "ios-show-log",
    description: "show log con salida larga",
    device: "ABEJITA",
    deviceKind: "ios",
    preCommands: ["enable"],
    command: "show log",
    expectedOk: true,
    tags: ["ios", "show", "pager", "long-output"],
    maxDurationMs: 70000,
  },
];